### ISSUE TITLE
The weapon selection screen in Vanark (USA) flickers with all renderers

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#479] opened 2020-05-23 18:03 UTC
![SLUS-01035_2020-05-21_06-17-36](https://user-images.githubusercontent.com/31968468/82737291-6c2e6080-9d73-11ea-88c1-5d9712f9dac7.png)

![SLUS-01035_2020-05-21_06-17-31](https://user-images.githubusercontent.com/31968468/82737297-7ea89a00-9d73-11ea-87b6-4f301ae111b0.png)

**Comment by stenzek** [comment] 2020-06-05 13:30
Might be GPU timing/DMA related, needs more research

**Comment by stenzek** [comment] 2020-08-15 05:06
Duplicate of https://github.com/stenzek/duckstation/issues/725

**Closed by stenzek** 2020-08-15 05:06 UTC
Labels: DMA, GPU, Needs Investigation
