### ISSUE TITLE
PBP Rom Format

### ISSUE THREAD

**Issue by dhanial** [stenzek/duckstation#1638] opened 2021-02-13 14:00 UTC
> (Request)

Please add .pbp rom format compatibility

**Comment by stenzek** [comment] 2021-02-13 14:05
Please use the search feature before creating new issues.

Duplicate of https://github.com/stenzek/duckstation/issues/17

I'd recommend migrating to CHD anyway. It compresses better, and is lossless unlike PBP.

**Closed by stenzek** 2021-02-13 14:05 UTC

**Comment by dhanial** [comment] 2021-02-13 21:26
# actually i've compressed all my rom to pbp using fpse, but i wish you will add this ability
