### ISSUE TITLE
Chrono Cross (USA) multiple observations

### ISSUE THREAD

**Issue by Konkonfaux** [stenzek/duckstation#553] opened 2020-06-18 06:55 UTC
1- Chrono Cross will not automatically start the controller in analogue mode. It needs to be manually activated, requiring binding a key to do it. This is probably not an issue to look into since and is the usual behaviour of the game.

2- The 480i menu is all scrambled. Switching character status screen (possibly only to Kid) will cause the game to hang. The graphics also don't display properly. There is some flickering, and some details are invisible.

3- I believe I've observed those behaviours in both software and D3D11 renderers. I didn't test openGL.

**Comment by stenzek** [comment] 2020-06-18 07:23
> 1- Chrono Cross will not automatically start the controller in analogue mode. It needs to be manually activated, requiring binding a key to do it. This is probably not an issue to look into since and is the usual behaviour of the game.
I'm planning on adding an (optional) auto analog enable setting to solve this. FWIW I bind the analog toggle to the xbox/guide button on my controller

> 2- The 480i menu is all scrambled. Switching character status screen (possibly only to Kid) will cause the game to hang. The graphics also don't display properly. There is some flickering, and some details are invisible.
Interesting - this was working before, but only hung on the Japanese version. I'm guessing the recent changes to GPU timings might've broke it, but it seems like only every other field is broken. Will look into it.

**Comment by stenzek** [comment] 2020-06-18 07:39
480i menu should be fixed with https://github.com/stenzek/duckstation/commit/47138aa9cf008d98e142c7bb2745dc29b6a5d5f6

I'm guessing the hang is the same issue as #503 - IIRC the game got stuck polling some variable waiting for an interrupt, but can't remember for sure. Need to debug it again.

**Comment by stenzek** [comment] 2020-08-17 02:17
Is this issue still happening on the latest build? The latest round of GPU changes might have fixed it, I can't seem to get it to hang anymore.

**Comment by stenzek** [comment] 2020-08-18 08:55
Closing as I can no longer reproduce the issue. Please comment if it is still happening on your end.

**Closed by stenzek** 2020-08-18 08:55 UTC
Labels: Needs Investigation

**Comment by mirrornoir** [comment] 2021-04-23 00:38
> Please comment if it is still happening on your end.

Not sure if this deserves a new issue here, I'm able to reproduce the hang for opening the Status menu on `SLUS-01041 - Chrono Cross (USA) (Disc 1)` using `0.1-3862-g8f821c77 (dev)` on Win 10 x86_64. Graphics are no longer corrupted and software renderer functions as intended. However using any hardware renderer when opening the Status screen will cause the hang. Displaying only a black screen and audio hanging until it fades out.

Reproducable as soon as you gain control of your character in game

**Comment by stenzek** [comment] 2021-04-23 17:13
Setting "DMA Max Slice Ticks" to 100 in Game Properties -> Compatibility Settings will sort out the hang.

I'll add it to the main database next release.
