### ISSUE TITLE
Capitan Commando graphical glitch issue.

### ISSUE THREAD

**Issue by TheBanana78** [stenzek/duckstation#2137] opened 2021-05-19 17:23 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated whenever this happens in Captain Commando. Whenever you reach a boss, there seem to be graphical issue with it. The sprites are messed up. 
![image](https://user-images.githubusercontent.com/82652849/118843930-c3600600-b8df-11eb-8649-b58a2b196657.png)

**Describe the solution you'd like**
I think bringing the **CD Load to pre-cache** would fix this issue. 

**Describe alternatives you've considered**
That was the only solution I got for this. sadly.

**Additional context**
![Screenshot 2021-05-19 213854](https://user-images.githubusercontent.com/82652849/118856398-25bf0380-b8ec-11eb-8a01-e0a1b9d0f738.png)

**Comment by foxsevent** [comment] 2021-05-19 17:30
Here's another idea to try, disable enhancrments maybe one of them is not playing well with this game.
CD load pre cache wouldn't really work and besides pre load to ram does that already but to the whole disc, but even that won't help as the PS1 has to load things at specific timings and speed otherwise things will break.

**Comment by stenzek** [comment] 2021-05-19 17:32
Known issue, this game is really sensitive to cd timings. Hopefully will be fixed when I get a chance to finish writing a better model...

Duplicate of https://github.com/stenzek/duckstation/issues/356

**Closed by stenzek** 2021-05-19 17:32 UTC

**Comment by stenzek** [comment] 2021-05-19 17:33
Also, please don't open issues when you have cd speedup enhancement enabled. IT DOES BREAK GAMES. That's why there's a big warning every time you start a game with it enabled.

**Comment by foxsevent** [comment] 2021-05-19 17:37
> Also, please don't open issues when you have cd speedup enhancement enabled. IT DOES BREAK GAMES. That's why there's a big warning every time you start a game with it enabled.

It would probably help just slightly if said warnings were excluded from the option " show osd messages" so people won't just disable and ignore.

If that's already the case then please ignore this, haven't tested if it's the case or not.

**Comment by stenzek** [comment] 2021-05-19 17:38
Then they'd complain that the"show osd messages" option is broken.

**Comment by foxsevent** [comment] 2021-05-19 17:41
> Then they'd complain that the"show osd messages" option is broken.

You just can't win. :/

**Comment by SerdarSaglam** [comment] 2021-10-10 01:35
I think the problem is with the Captain Commando.bin we downloaded. Because I burned it to cd and ran it on ps1, the same error appears there.

I wish there was a new backup from the original cd.

**Comment by dezraj** [comment] 2021-11-02 07:14
> 
> 
> I think the problem is with the Captain Commando.bin we downloaded. Because I burned it to cd and ran it on ps1, the same error appears there.
> 
> I wish there was a new backup from the original cd.

I've just came across this issue too and came to see if it had already been reported. The one I've downloaded is from a "redump.org" collection available on Internet Archive, so I expected it to be perfect.

**Comment by stenzek** [comment] 2021-11-02 07:21
Please do not discuss piracy here.
