### ISSUE TITLE
[Feature Request] Fast Forward and Rewind for the BIOS CD player

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#610] opened 2020-07-13 04:35 UTC
Currently neither of these functions are implemented and choosing them while a CD is playing causes the CD player to crash and the emulator to freeze. 

![Capture](https://user-images.githubusercontent.com/31968468/87271287-1fb30600-c516-11ea-9d71-4c45dbd943d6.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/87271292-22156000-c516-11ea-8f2b-ce4a755b35bc.PNG)

![Capture3](https://user-images.githubusercontent.com/31968468/87271296-2477ba00-c516-11ea-8230-ec4c4475b8dc.PNG)

**Comment by stenzek** [comment] 2020-09-22 12:44
Duplicate of https://github.com/stenzek/duckstation/issues/874

**Closed by stenzek** 2020-09-22 12:44 UTC
Labels: CD-ROM
