### ISSUE TITLE
Not reading full Psx collection (Directory)

### ISSUE THREAD

**Issue by jvhellraiser** [stenzek/duckstation#687] opened 2020-08-02 18:59 UTC
i notice that when i select a directory where my collection is Duckstation is not reading them all
it only reads like 30 out of 50 titles has reading from multiple folders been add to Duckstation?
also i notice all the titles that it found the ones with only .bin without no cue are the ones not
being read or scan at all & if the game has multiple disks in the same folder too.

**Comment by Shideravan** [comment] 2020-08-02 20:22
Can't reproduce here. And yes, I have a HUGE collection. Try to mark the _Recursive_ checkbox option if some of the game images are in subfolders, this may help you. 
![image](https://user-images.githubusercontent.com/12163923/89131623-8d829a00-d4e4-11ea-831a-d1f31fb9d7a2.png)
Anyway_ you need the .cue for any .bin in the folder if you want the discs be properly recognized. The .cue file serves as an header of the .bin, which contains the disc sectors, then being part of the file in this file format.
If you don't have the .cues anymore, you can use https://nielsbuus.dk/pg/psx_cue_maker/

**Comment by jvhellraiser** [comment] 2020-08-03 00:06
I mange to find something out about it my .bin are not recognize without the cue files
and did cue maker on all the .bin images and duckstation recognize all of them, now i have 1 question
games that are 4 cd's for example i did a cue that covers all the bin files will that be a problem when changing
cd's to continue the story?.

**Comment by stenzek** [comment] 2020-08-03 07:26
Yeah, incorrect .cue files could be the cause here. If you enable the system console log in advanced settings, and set it to developer level (although error would work too), it should tell you why it's failing to load whichever images are missing.

**Comment by stenzek** [comment] 2020-08-03 07:27
> games that are 4 cd's for example i did a cue that covers all the bin files will that be a problem when changing
cd's to continue the story?.

You should have a separate cue file for each disc. A single cue file would effectively make each disc a separate track, and that would not work. Switching discs is pretty straightforward - run the game, when you get to the disc change point, click change disc -> from game list, and select the next disc.

**Comment by zeraln** [comment] 2020-08-03 12:02
Some discs don't appear on the list for me either.
I realized that disks from different regions or with changed id (by patch / hack). The program only natively recognizes official discs (but not all).
You can still start the disc manually by selecting the "Start disc" option.

**Comment by stenzek** [comment] 2020-08-03 12:11
@zeraln can you get a snippet of the log where it's failing to list those games?

**Comment by zeraln** [comment] 2020-08-03 16:49
> @zeraln can you get a snippet of the log where it's failing to list those games?

![Log Duckstation](https://user-images.githubusercontent.com/13677990/89206509-c592e700-d58f-11ea-94ab-85f9d190cfa2.jpg)

**Comment by zeraln** [comment] 2020-08-03 16:50
> @zeraln can you get a snippet of the log where it's failing to list those games?

![Log Duckstation](https://user-images.githubusercontent.com/13677990/89206895-494cd380-d590-11ea-9e07-f938516c7137.jpg)

**Comment by stenzek** [comment] 2020-08-03 17:35
Sounds like your cue files are bad. Make sure the filenames in the cue match the .bin filenames **exactly**.

**Comment by stenzek** [comment] 2020-08-03 17:36
The Mega Man one is interesting - could you upload the cuesheet? (it's okay to share, it contains no game data).

**Comment by zeraln** [comment] 2020-08-03 17:57
> The Mega Man one is interesting - could you upload the cuesheet? (it's okay to share, it contains no game data).

[Megaman X4.zip](https://github.com/stenzek/duckstation/files/5017489/Megaman.X4.zip)

**Comment by stenzek** [comment] 2020-08-04 10:27
@zeraln That cuesheet seems fine. I was referring to Mega Man X6 in your screenshot above.

**Comment by zeraln** [comment] 2020-08-04 11:36
[Mega Man X6 (USA) (v1.1) [Tweaks v2.5 ].zip](https://github.com/stenzek/duckstation/files/5021776/Mega.Man.X6.USA.v1.1.Tweaks.v2.5.zip)

**Comment by stenzek** [comment] 2020-08-04 17:20
Mega Man should be fixed with https://github.com/stenzek/duckstation/commit/a7dbb9ab2894b5de66a0e039621a6d73a1fd379e

As for the others, you'll need to fix your cuesheets :)

If this is still an issue, please post a snippet of the relevant log section, as well as the cuesheet of the problematic game.

**Closed by stenzek** 2020-08-04 17:20 UTC
