### ISSUE TITLE
Please put the app on the Nvidia Shield Google Play store (Android TV)

### ISSUE THREAD

**Issue by stagestage** [stenzek/duckstation#1397] opened 2021-01-05 23:42 UTC
It can be sideloaded but I have to keep checking for updates manually and then transferring the new apk to my Shield.

Thank you

**Comment by stenzek** [comment] 2021-01-06 02:19
Duplicate of https://github.com/stenzek/duckstation/issues/1093

**Closed by stenzek** 2021-01-06 02:19 UTC
