### ISSUE TITLE
Visual/logical bugs introduced by Depth Buffer on Parasite Eve 2

### ISSUE THREAD

**Issue by fefo-dev** [stenzek/duckstation#1453] opened 2021-01-13 04:04 UTC
Numerous violations to the rules, but I still found it worth a report for further investigation/narrowing. Setup info at the bottom.

---

After a few minutes in game, in different sessions, I had these happen to me:

https://youtu.be/vpHT6uI7Hag?t=1935 - glitches on the hit animation and the his grenade trajectory (32:53); on 45:30 you can see a proper grenade shoot.

https://youtu.be/4tE63ZA_Y7I?t=3800 - the lasers should be tracking my character. Other instances of this in 1:00:48, 1:01:42 and 1:02:10 - the last one would hit me normally. There are 2 cases of another enemy affected by this in 1:02:24 (fast) and 1:02:45 - the laser would be pointed at me until he shoot, which was unaffected by the bug there.

https://youtu.be/4tE63ZA_Y7I?t=3828 character model goes crazy. There you can listen me disabling Depth Buffer a few seconds latter, which fixed the issue.

https://files.catbox.moe/spyx3j.m4v - the most severe example where this boss just bugs out completely. Here you can see an example of his normal behaviour: https://youtu.be/vpHT6uI7Hag?t=5383 (same session as the first example, with Depth Buffer disabled)

In all cases I was able to recheck later with the option disabled and nothing unexpected happened. No bug happened on a short session, all were from 30+ minutes at least. This makes testing harder, but I'll see what I can do. Any suggestion would be aprecciated.

---

Reference info:
Game: Parasite Eve II USA (SLUS-01042 and 01055)
System: Windows 10, i7 10750H, 2060 Mobile on driver 460.89

DuckStation 0.1-2882-gbc6444b6 (dev)
CPU mode: Recompiler
Renderer: Vulkan
Aspect Ratio: 4:3
Internal resolution: x4
MSAA: 2x
Texture filtering: xBR
Checked: True Color Rendering, Force NTSC Timings, Geometry Correction, Depth Buffer (at the time)
Hacks: Texture Replacement, Dump VRAM, Set VRAM Alpha Channel
Unlisted settings are default

**Comment by stenzek** [comment] 2021-01-13 04:40
Duplicate of #1454.

**Closed by stenzek** 2021-01-13 04:40 UTC
