### ISSUE TITLE
Tool Assisted/Input Recording support

### ISSUE THREAD

**Issue by LingKuja** [stenzek/duckstation#2566] opened 2021-08-29 23:18 UTC
**Is your feature request related to a problem? Please describe.**
Not really a problem, but I'd love to use Duckstation to make Tool Assisted.

**Describe the solution you'd like**
I need way to record the inputs. Something reliable that won't desync.

**Describe alternatives you've considered**
Already tried with bizhawk, but I'd much rather use Duckstation.

**Additional context**
I don't know much about coding, but I know that making such a feature must be time and resource consuming, in fact I'd just like to know if you're considering adding this in a future release. I hope you'll consider adding it.

**Comment by stenzek** [comment] 2021-08-30 01:24
Duplicate of https://github.com/stenzek/duckstation/issues/752.

Not something I'm interested in spending the time to implement, but pull requests welcome of course.

**Closed by stenzek** 2021-08-30 01:24 UTC
