### ISSUE TITLE
Otona No Asobi (Japan) instantly hangs after BIOS

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#320] opened 2020-04-21 22:21 UTC
![Capture](https://user-images.githubusercontent.com/31968468/79919719-452df780-8472-11ea-85c5-ecb86c2a3ba2.PNG)

**Comment by stenzek** [comment] 2020-05-20 14:08
Can't reproduce, might've been fixed at some point.

**Comment by stenzek** [comment] 2020-06-01 07:23
Seems to have regressed.

**Comment by stenzek** [comment] 2020-06-01 12:43
Should be fixed (again) by https://github.com/stenzek/duckstation/commit/e5fc47a00836d6a4c873d8dbefb102f7765ee34a

**Comment by Zet-sensei** [comment] 2020-10-12 00:58
Should be closed after verification on 0.1-1998-g43bafe1a.

**Comment by stenzek** [comment] 2020-10-12 01:00
Thanks for verifying.

**Closed by stenzek** 2020-10-12 01:00 UTC
Labels: Needs Investigation
