### ISSUE TITLE
Massive slowdown in Xenogears on the first realtime scene on Pi4

### ISSUE THREAD

**Issue by vanfanel** [stenzek/duckstation#2274] opened 2021-06-17 22:59 UTC
**Game details**
[Serial Code, Region]
SLUS-00664 Xenogears CD1 (USA)

**Description of the issue / bug**
Massive slowdown on the first cutscene, when the gears are battling in Lahan village.

**Steps to reproduce**
Simply start the game, and let the first realtime 3D cutscene play, where some "gears" (mechas) battle in the middle of Lahan village, sorrounded by heat and fire effects.

**Enhancements information**
All enhancements disabled.

**Hardware/software**
Raspberry Pi 4 running aach64 GNU/Linux, latest stable MESA (21.1.2 as of today), and DuckStation NOGUI using the Vulkan HW renderer.

**Emulator version**
Latest GIT code (main branch).

**Additional context**
Any other games I have tested on the PI4 using the aforementioned configuration run perfectly fine without any hiccups or slowdowns.
This includes very demanding games like the Final Fantasy games or Tekken 3: they all run perfectly well on Pi4/Vulkan.

So, any idea on what is Xenogears doing during the first 3D realtime cutscene to cause such massive slowdown that can't be seen anywhere else?
(A similar situation happened with FF7 whirl effect, which eventually improved).

My guess here is that Xenogears is doing something "strange" to simulate the heat effect on that scene: maybe reading the video buffer and applying some distortion?

**Comment by stenzek** [comment] 2021-06-18 01:50
Performance problems on very low end hardware is not a bug in the emulator, closing. You also didn't check the software renderer to see if it's a GPU/driver bottleneck.

I'll check what it's doing here when I get a chance, maybe readbacks (in which case using sw for readbacks will help).

**Closed by stenzek** 2021-06-18 01:50 UTC

**Comment by stenzek** [comment] 2021-06-18 08:06
This scene would be very heavy even on the PS1. It renders the screen, copies it, then uses it as a texture for post-processing. Given how slow the Pi's GPU is at copying textures, it's not surprising it struggles.

Not much which be done here. Use the software renderer, or a board with a more powerful GPU.

**Comment by vanfanel** [comment] 2021-06-18 10:45
@stenzek I have completed the initial report with information regarding the software renderer: it's not affected by the slowdown.
In other words, the same realtime scene works fullspeed with the software renderer.
OTOH, the software renderer is actually slower in all other situations (Tekken 3 menu is not fullspeed, even BIOS is not fullspeed with software renderer).

I am very thankful for your research around this. More than a solution for the Vulkan renderer, which is probably impossible on a Pi4, I wanted to confirm the framebuffer readback and manipulation theory I had, which the game uses to simulate the heat effect in the scene.

Just as a final try: could you point the culprit Vulkan function? Just in case I can tell the MESA developers about this. Maybe we could get lucky as with the FF7 whirl effect...

**Comment by stenzek** [comment] 2021-06-18 11:23
> OTOH, the software renderer is actually slower in all other situations (Tekken 3 menu is not fullspeed, even BIOS is not fullspeed with software renderer).

Something wrong on your end, it runs full speed for me (much more than full speed, in fact).

> I wanted to confirm the framebuffer readback and manipulation theory I had, which the game uses to simulate the heat effect in the scene.

It's not a readback, it's a copy. And because it's using the framebuffer as a texture, both where it's drawing and elsewhere, these copies effectively happen over 100 times in one frame (once to update shadow texture for the overlapping copy, another for the actual copy, repeat a bunch of times).

> Just as a final try: could you point the culprit Vulkan function? Just in case I can tell the MESA developers about this. Maybe we could get lucky as with the FF7 whirl effect...

The Vulkan renderer is not the problem. This scene runs at over 200fps on my Snapdragon 845 phone at 4x resolution scale using it. Even the G52 in my N2 manages 90fps at 2x with OpenGL.

There's nothing really to optimize in the driver here. It's just a pathetically slow GPU which is incredibly memory bandwidth bound, and this workload makes it very apparent.

**Comment by vanfanel** [comment] 2021-06-18 13:09
@stenzek Ok, understood. Thanks for the extensive detail :+1: 

Now, what could be wrong on my side regarding the software renderer?
-Pi4 overclocked to 1.8Ghz and PERFORMANCE governor, so there's no CPU speed throttling, but stable 1.8Ghz always.
-Pi4 running aarch64 with latest stable MESA and libDRM (are you using the Broadcom graphics stack or are you using real KMS mode on your Pi4?).
-Video mode used by DuckStation is 1360x768
-Threaded video is ON
-Optimal pacing is ON
-VSYNC is ON (could it be that you are seeing fullspeed Tekken 3 menu with the SW renderer with VSYNC OFF instead? That could be the key difference).
-AUDIO SYNC is ON
-SYNC to host refresh rate is ON
-CUBEB audio backend in use

Anything you can see that could be at play here on my setup versus yours, please?

**Comment by stenzek** [comment] 2021-06-20 13:07
Looks like it does indeed struggle to hold 60fps with vsync on, probably a frame pacing issue. I'll look into it when I have time.

**Comment by vanfanel** [comment] 2021-06-20 17:58
@stenzek That's very good to hear, that you could reproduce the issue on your side!

What could be at play here? I used to know KMSDRM internals pretty well, maybe if you refresh my mind I can give ideas :)

As an initial idea... are you blocking until vsync arrives (double buffering scheme, like in blocking for vsync immediately after issuing the pageflip) or using a triple buffer?

**Comment by stenzek** [comment] 2021-06-21 12:26
I took a quick look, there were a couple of issues here:

1. A performance regression in the dynarec, but only on A32/A64.
2. `glTexImage2D()` when streaming from a PBO seems to be quite slow on this driver for some reason. I don't have time to investigate at the moment, but doing an extra copy client-side knocks 2-3ms off the call... It should be completely asynchronous and free with the PBO, that's the whole point of using them. So I've disabled it for now on Broadcom GPUs (as well as Qualcomm, where they're half broken).

Seems to make it a bit more reliable. Still seeing frame drops during FMVs, but it runs at 250fps when fast forwarding so there's still some pacing issues here.

> As an initial idea... are you blocking until vsync arrives (double buffering scheme, like in blocking for vsync immediately after issuing the pageflip) or using a triple buffer?

Buffer swapping blocks until the page flip completes, which should be at vblank if I'm reading the documentation correctly.

**Comment by vanfanel** [comment] 2021-06-21 13:25
@stenzek Isn't `glTexImage2D()` a GLES function? In my experience, current Vulkan MESA implementation is way faster than GLES on the Broadcom GPU.
(I originally reported the massive slowdown on Vulkan because of that: VK seems to be the way to go with these GPUs if I am not mistaken).
So, should I test Xenogears with the GL renderer instead of using Vulkan renderer?

**Comment by stenzek** [comment] 2021-06-21 13:35
It uses GL for displaying when using the software renderer. Don't use vulkan with this game on the pi, the GPU is just too slow,

**Comment by vanfanel** [comment] 2021-06-21 16:01
@stenzek I have just built and tested latest GIT code, and everything is fullspeed now in Xenogears using the software renderer.
Not only that: BIOS is also fullspeed with the software renderer now!!
Just incredible what you did... :O
BTW, if you haven't played Xenogears, please do if you can. That game is not a normal RPG. It's beyond words what that game means for the PSX library.

**Comment by stenzek** [comment] 2021-06-21 16:09
I still get slowdowns in the Tekken 3 FMV, but only when vsync is on. So something else is still taking too long, since it runs at 250fps uncapped. Menu/ingame is fine.

**Comment by vanfanel** [comment] 2021-06-21 16:42
@stenzek Yes, I can see the slowdowns in Tekken 3 FMV too...

**Comment by vanfanel** [comment] 2021-06-29 22:06
@stenzek Another situation where I am seeing slowdowns is in the (static) **file selection screen in Castlevania SOTN.**
Can you see it too? Could it be caused by the same problem as Tekken 3 FMV?
Slowdowns in a static screen is intriguing, only **music XA decoding** is happening.
