### ISSUE TITLE
Ape Escape (USA) cannot move character

### ISSUE THREAD

**Issue by benderscruffy** [stenzek/duckstation#64] opened 2020-03-08 01:14 UTC
even after i choose dualshock and map out the  button bindings cannot move the character only the camera moves around

**Comment by stenzek** [comment] 2020-03-08 02:57
This was working okay for me last time I tried. Are you using a controller? If so, please screenshot your pad configuration.

Currently, the analog sticks can only be mapped to a controller axis, you won't be able to simulate them with the keyboard.

**Comment by benderscruffy** [comment] 2020-03-08 09:25
yes i am using a controller
G-Shark GS-GP702 is what it is being detected as through Duckstation
it just uses the win 7 driver

**Comment by stenzek** [comment] 2020-03-08 14:13
Seems to be working okay for me, here's the configuration I'm using for a Wired Xbox One Controller:

![image](https://user-images.githubusercontent.com/11288319/76164453-c2d7c580-619a-11ea-95ea-14ca28c32372.png)

**Comment by kurayami6** [comment] 2020-03-08 14:34
I'm having the same problem. All the buttons work but the analog stick just moves the camera and not the character. I also tried Using the D-pad and it also just moves the camera. I'm using Windows 7 with a wired Xbox One controller. I'm sure it's something obvious and I just bound the controls wrong. 

Here's my setup

![Capture](https://user-images.githubusercontent.com/31968468/76164808-f4a25980-61a5-11ea-933e-54e7359312ff.PNG)

**Comment by stenzek** [comment] 2020-03-08 14:37
@kurayami6 you need to bind the axises at the bottom to your pad sticks, and the buttons to the dpad. It should match my screenshot then.

This isn't very clear, so it could use better documentation in the UI, or sensible defaults for common controllers. Will look into it when I have a chance.

**Comment by benderscruffy** [comment] 2020-03-08 14:39
![controller](https://user-images.githubusercontent.com/2696404/76164914-92d5f580-618d-11ea-83de-392080f635cf.PNG)
doesnt detect the other pad properly

**Comment by stenzek** [comment] 2020-03-24 15:35
I may have fixed this the other day, controller type changes weren't applying when the emu was running. Try changing your controller type either while it's running now, outside the game, then do a fast/full boot, not resume (right click in the game list). Otherwise, it'll load the save state with the old controller type.

**Comment by benderscruffy** [comment] 2020-03-26 09:35
did what you said but no change still not fixed

**Comment by stenzek** [comment] 2020-03-26 10:15
Not sure how I can fix it then if I can't reproduce it.

I'd suggest trying a pad test program such as https://www.psx-place.com/resources/padtest.396/ and seeing if the inputs are registering in there.

**Comment by benderscruffy** [comment] 2020-03-26 10:49
no not registering properly in Analog Controller
it works properly in RPCS3 
I will just have to stick to digital controller

**Comment by stenzek** [comment] 2020-03-26 11:08
I just noticed that your screenshot has all the axis bindings listed as "Controller0/Axis2". Maybe it needs a larger deadzone. That or it's a SDL issue.

**Comment by benderscruffy** [comment] 2020-03-26 12:53
yes it doesnt detect my right pad properly

**Comment by stenzek** [comment] 2020-03-28 01:47
Are you binding each axis individually? If you use the "rebind all" feature with axises it breaks and spams a single binding across all controls (I need to add a delay).

**Comment by benderscruffy** [comment] 2020-03-28 03:22
yes i am binding each individually

**Comment by benderscruffy** [comment] 2020-03-29 01:24
when i go to this site to test my joypad it works correctly
https://html5gamepad.com/
my joypad is 0079-0006-USB Joystick

**Comment by stenzek** [comment] 2020-05-17 09:42
Closing as this is probably an SDL issue. If I eventually add a DirectInput/XInput controller interface this may be resolved.

**Closed by stenzek** 2020-05-17 09:42 UTC

**Comment by Bekon241** [comment] 2020-12-21 16:21
Hi im from Poland my eng. not great but i wont sey something.

I use controler psx and adapter usb +SDL all work great but one option is missed.
Orginal in game Tenchu 2 on dualshoc controler when you use analod mode (analog stick left only work in game) and d-pad also, for the same move. Is any chance implement one option in control setting to force d-pad and analog stick left work in the same time when analog control is on? Coz now when i off analog on controler game not work with dpad, when i change to digital mode d-pad work but analog no. When analog only analog work but off dpad. For tenchu on orginal psx best controls is when d-pad and left analog stick work together in analog mode. Game in orginal is great then becouse, some move is better on d-pad like side steps, but running and hook and camra angle better on analog. How i can force controler be in analog mode and still work as digitalfor d-pad? Thanks i wait for answer.

**Comment by DevGabrielDeSouza** [comment] 2021-08-15 03:31
Maybe this is not related to this issue, but I don't know how to map the analog stick press and make my character swim down...
Is there any way to map the "stick button"?
![image](https://user-images.githubusercontent.com/9301442/129466087-37e529cd-662a-4175-8ecc-703e85b8764b.png)
