### ISSUE TITLE
[SLPS-01762] Pepsiman game - No music

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#655] opened 2020-07-24 03:07 UTC
**Version**
0.1-1333-g5a955a4

**Game**
SLPS-01762 - Pepsiman (Japan)

No music ingame (just FX Sounds). Tested in both SDL and cubeb.

Tested the same CHD in MAME and the sound plays correctly.

Could be a regression with 0.1-941-g2e64f77 which has an entry in the compatibility list or something that may be missed by the first tester.

**Comment by stenzek** [comment] 2020-07-24 03:11
Could you screenshot your game properties page with the hashes computed? This game uses CD audio, so might be related.

As far as I can tell it should be fine...

**Comment by stenzek** [comment] 2020-07-24 03:13
Also probably worth checking the CD-ROM debug window while playing.

**Comment by stenzek** [comment] 2020-07-24 03:48
Might be an issue with CHDs. See if https://github.com/stenzek/duckstation/commit/10f23667c90364e6c54e34fbc25b4733c095d246 makes any difference.

**Comment by Shideravan** [comment] 2020-07-24 04:03
![image](https://user-images.githubusercontent.com/12163923/88359535-5cb69e00-cd49-11ea-9edd-9e97d5d7084c.png)

Unfortunatelly, the problem continues in this latest version (https://github.com/stenzek/duckstation/commit/10f23667c90364e6c54e34fbc25b4733c095d246)

**Comment by Shideravan** [comment] 2020-07-24 04:06
![image](https://user-images.githubusercontent.com/12163923/88359652-d2bb0500-cd49-11ea-8e15-08656c9f3a33.png)

**Comment by Shideravan** [comment] 2020-07-24 04:06
![image](https://user-images.githubusercontent.com/12163923/88359678-ebc3b600-cd49-11ea-9400-ff7f37a47988.png)

**Comment by Shideravan** [comment] 2020-07-24 04:07
Seeking and Playing CDDA is changing fast from one to another, don't know if this is normal behavior.

**Comment by Shideravan** [comment] 2020-07-24 04:15
Interesting fact: if I boot the BIOS and play the game disk with the CD Player (in DuckStation) the tracks plays normally... Hmmm

**Comment by stenzek** [comment] 2020-07-24 04:27
Yeah, those lengths (and hashes) definitely aren't correct. Did the latest commit change anything?

**Comment by mirrornoir** [comment] 2020-07-24 08:48
I can confirm this issue with a redump verified copy of Pepsiman (Japan). In gameplay the music track repeats a second of music over and over again. Each loop of audio lasting about a second. 

I'm using CHD for this title which may prove your suspicions right, Stenzek

**Comment by stenzek** [comment] 2020-07-24 16:51
I can't seem to reproduce this, even using CHDs.

I wonder if there was an issue with an earlier version of chdman, generating different files or something. Because while the audio tracks won't show the correct hash due to an issue with reading the pregap, even the data track's hash is incorrect in your screenshot (see http://redump.org/disc/18737/), but correct in mine.

**Comment by mirrornoir** [comment] 2020-07-24 18:02
Yeah looks like you were right about the pregap. Redump hashes were used as the original in both cases, but I've had my old CHD of Pepsiman around for a while. I've made a new one to compare and the pregap is completely different.

Old Copy:
```chdman info -i Pepsiman\ \(Japan\).chd
chdman - MAME Compressed Hunks of Data (CHD) manager 0.222 (unknown)
Input file:   Pepsiman (Japan).chd
File Version: 5
Logical size: 225,137,664 bytes
Hunk Size:    19,584 bytes
Total Hunks:  11,496
Unit Size:    2,448 bytes
Total Units:  91,968
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     115,839,858 bytes
Ratio:        51.5%
SHA1:         5c7231f526986446d7e9c254af0697477e246ee9
Data SHA1:    a9d6719fe9c7076eb9e73d56a2e4dbcb2da2a418
Metadata:     Tag='CHT2'  Index=0  Length=92 bytes
              TRACK:1 TYPE:MODE2_RAW SUBTYPE:NONE FRAMES:52791 PREGAP:0 PG
Metadata:     Tag='CHT2'  Index=1  Length=89 bytes
              TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:4800 PREGAP:150 PGTYP
Metadata:     Tag='CHT2'  Index=2  Length=87 bytes
              TRACK:3 TYPE:AUDIO SUBTYPE:NONE FRAMES:4650 PREGAP:0 PGTYPE:
Metadata:     Tag='CHT2'  Index=3  Length=87 bytes
              TRACK:4 TYPE:AUDIO SUBTYPE:NONE FRAMES:4650 PREGAP:0 PGTYPE:
Metadata:     Tag='CHT2'  Index=4  Length=87 bytes
              TRACK:5 TYPE:AUDIO SUBTYPE:NONE FRAMES:4650 PREGAP:0 PGTYPE:
Metadata:     Tag='CHT2'  Index=5  Length=87 bytes
              TRACK:6 TYPE:AUDIO SUBTYPE:NONE FRAMES:4650 PREGAP:0 PGTYPE:
Metadata:     Tag='CHT2'  Index=6  Length=87 bytes
              TRACK:7 TYPE:AUDIO SUBTYPE:NONE FRAMES:2394 PREGAP:0 PGTYPE:
Metadata:     Tag='CHT2'  Index=7  Length=88 bytes
              TRACK:8 TYPE:AUDIO SUBTYPE:NONE FRAMES:13369 PREGAP:0 PGTYPE
```

New Copy:
```chdman info -i Pepsiman\ \(Japan\).chd
chdman - MAME Compressed Hunks of Data (CHD) manager 0.222 (unknown)
Input file:   Pepsiman (Japan).chd
File Version: 5
Logical size: 225,509,760 bytes
Hunk Size:    19,584 bytes
Total Hunks:  11,515
Unit Size:    2,448 bytes
Total Units:  92,120
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     114,891,514 bytes
Ratio:        50.9%
SHA1:         267bf15054334a23405ed9597d93e0149a7ce75b
Data SHA1:    8e3f807bc76fcaec86bcc491fd1cbcde6b457496
Metadata:     Tag='CHT2'  Index=0  Length=92 bytes
              TRACK:1 TYPE:MODE2_RAW SUBTYPE:NONE FRAMES:52791 PREGAP:0 PG
Metadata:     Tag='CHT2'  Index=1  Length=90 bytes
              TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:4650 PREGAP:150 PGTYP
Metadata:     Tag='CHT2'  Index=2  Length=90 bytes
              TRACK:3 TYPE:AUDIO SUBTYPE:NONE FRAMES:4650 PREGAP:150 PGTYP
Metadata:     Tag='CHT2'  Index=3  Length=90 bytes
              TRACK:4 TYPE:AUDIO SUBTYPE:NONE FRAMES:4650 PREGAP:150 PGTYP
Metadata:     Tag='CHT2'  Index=4  Length=90 bytes
              TRACK:5 TYPE:AUDIO SUBTYPE:NONE FRAMES:4650 PREGAP:150 PGTYP
Metadata:     Tag='CHT2'  Index=5  Length=90 bytes
              TRACK:6 TYPE:AUDIO SUBTYPE:NONE FRAMES:4650 PREGAP:150 PGTYP
Metadata:     Tag='CHT2'  Index=6  Length=90 bytes
              TRACK:7 TYPE:AUDIO SUBTYPE:NONE FRAMES:2394 PREGAP:150 PGTYP
Metadata:     Tag='CHT2'  Index=7  Length=91 bytes
              TRACK:8 TYPE:AUDIO SUBTYPE:NONE FRAMES:13669 PREGAP:150 PGTY
```

**Comment by Shideravan** [comment] 2020-07-24 18:49
```
chdman - MAME Compressed Hunks of Data (CHD) manager 0.222 (mame0222)
Input file:   pepsiman the running hero (japan) [slps-01762].chd
File Version: 5
Logical size: 225,872,064 bytes
Hunk Size:    19,584 bytes
Total Hunks:  11,534
Unit Size:    2,448 bytes
Total Units:  92,268
Compression:  cdlz (CD LZMA), cdzl (CD Deflate), cdfl (CD FLAC)
CHD size:     113,691,387 bytes
Ratio:        50.3%
SHA1:         05059038170ed7837dfe291422458e7a3bf6d806
Data SHA1:    d10ff61024048154c13e39d8fb795f5b8d040f8d
Metadata:     Tag='CHT2'  Index=0  Length=90 bytes
              TRACK:1 TYPE:MODE2_RAW SUBTYPE:NONE FRAMES:52941 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0.
Metadata:     Tag='CHT2'  Index=1  Length=87 bytes
              TRACK:2 TYPE:AUDIO SUBTYPE:NONE FRAMES:4800 PREGAP:150 PGTYPE:MODE1 PGSUB:RW POSTGAP:0.
Metadata:     Tag='CHT2'  Index=2  Length=85 bytes
              TRACK:3 TYPE:AUDIO SUBTYPE:NONE FRAMES:4650 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0.
Metadata:     Tag='CHT2'  Index=3  Length=85 bytes
              TRACK:4 TYPE:AUDIO SUBTYPE:NONE FRAMES:4650 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0.
Metadata:     Tag='CHT2'  Index=4  Length=85 bytes
              TRACK:5 TYPE:AUDIO SUBTYPE:NONE FRAMES:4650 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0.
Metadata:     Tag='CHT2'  Index=5  Length=85 bytes
              TRACK:6 TYPE:AUDIO SUBTYPE:NONE FRAMES:4650 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0.
Metadata:     Tag='CHT2'  Index=6  Length=85 bytes
              TRACK:7 TYPE:AUDIO SUBTYPE:NONE FRAMES:2394 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0.
Metadata:     Tag='CHT2'  Index=7  Length=86 bytes
              TRACK:8 TYPE:AUDIO SUBTYPE:NONE FRAMES:13519 PREGAP:0 PGTYPE:MODE1 PGSUB:RW POSTGAP:0.

     Hunks  Percent  Name
----------  -------  ------------------------------------
     1,952    16.9%  Copy from self
     4,574    39.7%  CD LZMA
     2,026    17.6%  CD Deflate
     2,982    25.9%  CD FLAC
```

**Comment by stenzek** [comment] 2020-07-24 18:54
Same issue with the missing pregap. Seems like I might have to hardcode it to insert one if it's missing..

**Comment by Shideravan** [comment] 2020-07-24 18:56
Also, my copy is also verified with MAME's PSX.xml

```
<software name="pepsiman" supported="no">
		<!-- Unknown source
		<rom name="Pepsiman The Running Hero (Japan) (Track 1) [SLPS-01762].bin" size="124517232" crc="14990a8c" sha1="48385eb2ea9496280cfc6257f60b0195f2e2c4cf"/>
		<rom name="Pepsiman The Running Hero (Japan) (Track 2) [SLPS-01762].bin" size="11289600" crc="83b6bd1c" sha1="a0858ee5f767817d0429a34ea21fbf273e8e9d25"/>
		<rom name="Pepsiman The Running Hero (Japan) (Track 3) [SLPS-01762].bin" size="10936800" crc="74347927" sha1="35ece03e17d7aac5e044470be7f8f5a799c32618"/>
		<rom name="Pepsiman The Running Hero (Japan) (Track 4) [SLPS-01762].bin" size="10936800" crc="b49e2757" sha1="8cc3ab123f2ed9a963966fbadac8f7b984ca833a"/>
		<rom name="Pepsiman The Running Hero (Japan) (Track 5) [SLPS-01762].bin" size="10936800" crc="d6d357aa" sha1="0b0cb32442fd01c883ce45008782adb11832aead"/>
		<rom name="Pepsiman The Running Hero (Japan) (Track 6) [SLPS-01762].bin" size="10936800" crc="e057c53a" sha1="627a556b9a1dfd6f1acc85e8f5b5f25322791c71"/>
		<rom name="Pepsiman The Running Hero (Japan) (Track 7) [SLPS-01762].bin" size="5630688" crc="cc23b224" sha1="9e28885751a09fbd87cc078d8579ac8d6a61d6db"/>
		<rom name="Pepsiman The Running Hero (Japan) (Track 8) [SLPS-01762].bin" size="31796688" crc="e9e0563b" sha1="f4ff2ee8d5e2f4560806a33338fc87375082445f"/>
		<rom name="Pepsiman The Running Hero (Japan) [SLPS-01762].cue" size="962" crc="c6eef03f" sha1="df0ba180679637c7fa438cfc98cacb57ee142539"/>
		-->
		<description>Pepsiman (Jpn)</description>
		<year>1999</year>
		<publisher>KID</publisher>
		<info name="serial" value="SLPS-01762" />
		<info name="release" value="19990304" />
		<info name="alt_title" value="ペプシマン"/>
		<sharedfeat name="compatibility" value="NTSC-J"/>
		<part name="cdrom" interface="psx_cdrom">
			<diskarea name="cdrom">
				<disk name="pepsiman the running hero (japan) [slps-01762]" sha1="05059038170ed7837dfe291422458e7a3bf6d806"/>
			</diskarea>
		</part>
	</software>
```

**Comment by stenzek** [comment] 2020-07-24 19:01
Interesting that MAME and redump disagree on the hash for the first track.

**Comment by Shideravan** [comment] 2020-07-24 19:02
Well, don't mean that MAME is 100% correct. I'm thinking to submit a commit there to change it if it's wrong LOL

**Comment by stenzek** [comment] 2020-07-29 16:04
Marking as invalid since this appears to be a dump issue (pregap is missing from tracks >2), and the latest version of `chdman` produces the correct layout. In theory I could special case/hack a check in for the older/incorrect layout, but it seems silly for the emu to work around an image problem.

**Closed** 2020-07-31 10:11 UTC
Labels: invalid
