### ISSUE TITLE
Texture filtering at >1x resolution scale has visible lines

### ISSUE THREAD

**Issue by Blackbird88** [stenzek/duckstation#35] opened 2020-02-26 12:36 UTC
I didn't see issue for this so my bad if this is known, but upscaling currently leaves visible lines. Both D3D11 and OpenGL renderers are affected. Software is obviously fine.

DuckStation
![image](https://user-images.githubusercontent.com/4414625/75345432-01b57380-589d-11ea-98d8-81219f599cd0.png)

ePSXe (Pete's OpenGL2 plugin)
![image](https://user-images.githubusercontent.com/4414625/75346020-180fff00-589e-11ea-8616-a7ff95a38398.png)

**Comment by stenzek** [comment] 2020-02-28 13:32
Looks like an issue with texture filtering more than upscaling. I can't reproduce it with filtering disabled.

**Comment by Blackbird88** [comment] 2020-02-28 17:40
Ah you are right. Without **Bilinear Filtering** it's fine, but pixely.

**Comment by stenzek** [comment] 2020-08-10 13:39
Fixed with https://github.com/stenzek/duckstation/commit/5c6e92cdfc8a5533c153580385415e19c2dcc382

**Closed by stenzek** 2020-08-10 13:39 UTC
Labels: GPU, enhancement
