### ISSUE TITLE
Ghost in the Shell (USA) - Missing Textures and Incorrect Effects

### ISSUE THREAD

**Issue by mirrornoir** [stenzek/duckstation#364] opened 2020-04-28 17:12 UTC
Ghost in the Shell has missing textures and inaccurate menu effect while using OpenGL hardware rendering. If the game is started in software mode and then toggled back to hardware, textures will be present in hardware rendering. There's also a flashing graphical wrap around in mission breifing screens in software rendering that is also present in beetle-psx-hw. Widescreen screenshots since there's in game support for it.

## Menu Issue:
Hardware
![SLUS-00552_2020-04-28_12-22-20](https://user-images.githubusercontent.com/19215655/80512626-c7735b80-894b-11ea-8963-759c5761c70d.png)

Software
![SLUS-00552_2020-04-28_12-32-30](https://user-images.githubusercontent.com/19215655/80513814-9c8a0700-894d-11ea-8715-2c7de19151b3.png)

## Briefing Screen Wrap Around (see right side):
Software
![SLUS-00552_2020-04-28_12-58-17](https://user-images.githubusercontent.com/19215655/80515472-073c4200-8950-11ea-88f2-1dc2b0234c52.png)

Same issue in beetle-psx-hw
![Screenshot_2020-04-28_12-25-08](https://user-images.githubusercontent.com/19215655/80514685-d7406f00-894e-11ea-82f2-cd77e15080fa.png)

## Missing Textures: 
Hardware
![SLUS-00552_2020-04-28_12-23-12](https://user-images.githubusercontent.com/19215655/80512675-da862b80-894b-11ea-862d-a7f7763b4660.png)
![SLUS-00552_2020-04-28_12-41-16](https://user-images.githubusercontent.com/19215655/80514975-428a4100-894f-11ea-8ff5-a95a9f1da47e.png)

Software
![SLUS-00552_2020-04-28_12-39-40](https://user-images.githubusercontent.com/19215655/80513879-b75c7b80-894d-11ea-8077-7709e2959cd7.png)
![SLUS-00552_2020-04-28_12-39-48](https://user-images.githubusercontent.com/19215655/80514969-4027e700-894f-11ea-9d01-1592e0e40b32.png)

Toggle Hardware back on after Software start:
![SLUS-00552_2020-04-28_12-40-07](https://user-images.githubusercontent.com/19215655/80515620-3e125800-8950-11ea-871b-1aa5ea3b714c.png)

## Hardware Rendering Log:
[log.txt](https://github.com/stenzek/duckstation/files/4547173/log.txt)

**Comment by stenzek** [comment] 2020-04-29 12:51
The issue on the menu is caused by a lack of mask bit check emulation - the same issue which breaks Silent Hill and a handful of other games. I have an implementation almost finished with this, it's just waiting until I can figure out a workaround for a difference between D3D and OpenGL.

The wrap-around you're seeing in the in the briefing seems like it should normally be hidden by overscan - setting the crop mode to "only overscan area" will fix this.

I can't seem to reproduce the texture issue on either D3D or OpenGL on Intel or NVIDIA drivers. It could be caused by some enhancement or other issue.

**Comment by stenzek** [comment] 2020-05-03 07:16
Menu effect should be fixed in the latest build.

I still haven't had any luck reproducing the broken textures/palettes - could you please check if this is still occurring on new build when you have time?

**Comment by mirrornoir** [comment] 2020-05-07 20:55
Sorry for the delayed response, I can confirm the menu issue and missing texture issue have been fixed on OpenGL renderer in the latest build, thanks. The briefing screen wrap around is indeed also fixed by crop "only overscan area".

I think this issue can be safely closed. :+1:

**Closed** 2020-05-07 23:33 UTC
Labels: GPU Issue
