### ISSUE TITLE
Reset Settings and Issue w/ SLUS-00292 

### ISSUE THREAD

**Issue by platyhooks** [stenzek/duckstation#1033] opened 2020-11-01 15:12 UTC
I apologize if anything here as been considered/known or this isn't the right place.

1. Have reset to default settings button 
When troubleshooting the below issue it would have been nice to go back to baseline quickly instead of finding everything that has been checked. (Maybe i am just missing it?)

2. SLUS-00292 - Suikoden 1.0 - Nighttime scene
No difference in any renderer.

Beetle HW

![Suikoden (USA) (v1 0 BugFix)-201101-092658](https://user-images.githubusercontent.com/73786333/97806265-c25bd580-1c28-11eb-9047-190e6794e759.png)
Duckstation

![SLUS-00292_2020-11-01_09-36-10](https://user-images.githubusercontent.com/73786333/97806269-d1db1e80-1c28-11eb-9e14-a585f5dba762.png)

**Comment by stenzek** [comment] 2020-11-02 08:28
Can't reproduce the rendering issue. Do you have any enhancements enabled?

![image](https://user-images.githubusercontent.com/11288319/97846017-1d7ced80-1d39-11eb-9a22-92eeb68a0771.png)

**Comment by platyhooks** [comment] 2020-11-02 23:26
Only thing on is scaled dithering. Switching CPU mode to Interpreter seems to have solved it for me.  
I was on Recompiler. Cached has the same issue,

![Screenshot 2020-11-02 182524](https://user-images.githubusercontent.com/73786333/97930213-da227f00-1d38-11eb-844c-f07ff79552b8.jpg)

**Comment by stenzek** [comment] 2020-11-03 00:01
I was definitely using recompiler.

**Comment by platyhooks** [comment] 2020-11-03 01:05
I tried blowing away the install directory and the Documents\Duckstation and reinstalling. I get the same results and switching to  Interpreter makes it go away. I'm running on a 5700xt maybe there is something in Radeon Software screwing with it,

**Comment by stenzek** [comment] 2020-11-03 01:44
Seems very strange. I also tried a clean install and it looked fine with recompiler. But this was on an NVIDIA GPU, I can test AMD later.

Are you saying it immediately corrects itself when switching CPU modes, or do you have to restart the game?

**Comment by platyhooks** [comment] 2020-11-03 02:06
Restart the game or load a save state just before. It doesn't correct in the scene.

**Comment by stenzek** [comment] 2020-11-03 02:07
What about in the software renderer? That should be independent of any driver diferences.

**Comment by platyhooks** [comment] 2020-11-03 02:41
No Difference. I tried from a save and a new game.

**Comment by platyhooks** [comment] 2020-11-03 03:07
Same results with a 1650 super.

**Comment by stenzek** [comment] 2020-11-05 02:11
No idea what's going on then, I can't reproduce this at all. Even tried on the GitHub build.

Maybe check that your dump is valid?

**Comment by platyhooks** [comment] 2020-11-19 23:46
Interestingly v1.1 seems to work fine. Both checked against redump. I dunno, this is the only issue I've noticed so far ingame. Selfishly it works well enough for my purposes.

![Screenshot 2020-11-19 184104](https://user-images.githubusercontent.com/73786333/99737963-75d12080-2a97-11eb-9372-5d75ac8aed23.png)

**Comment by stenzek** [comment] 2020-12-06 03:50
Fixed in https://github.com/stenzek/duckstation/commit/1e322191ea92559df1e64545cfbd5d7164fb0938

This game calls BIOS memmove() in uncached memory a bunch of times, which takes several frames to complete. Version 1.0 will corrupt palettes if this completes too quickly.

Interestingly, they changed this behavior in v1.1, replacing it with a bunch of seemingly-meaningless printfs.

**Closed by stenzek** 2020-12-06 03:50 UTC
