### ISSUE TITLE
Game database doesn't recognize revisions

### ISSUE THREAD

**Issue by levonnn** [stenzek/duckstation#1794] opened 2021-03-13 05:28 UTC
**Game details**
(from redump.org)
Akumajou Dracula X: Gekka no Yasoukyoku [SLPM 86023]
Akumajou Dracula X: Gekka no Yasoukyoku (Rev 1) [SLPM 86023]
Akumajou Dracula X: Gekka no Yasoukyoku (Rev 2) [SLPM 86073, SLPM 87328]

**Description of the issue / bug**
Database from redump.org doesn't recognize revisions and all three versions are titled "Akumajou Dracula X - Gekka no Yasoukyoku (Japan) (Rev 1)".

**Steps to reproduce**
It's in the game list.

**Emulator version**
0.1-3431

**Comment by stenzek** [comment] 2021-03-13 05:52
Not really a bug - if the games have the same serial, they're going to get the same title.

Duplicate of #1460 and #1077.

**Closed by stenzek** 2021-03-13 05:52 UTC
