### ISSUE TITLE
[Feature Request] Enable Hotkeys with buttons combo

### ISSUE THREAD

**Issue by babywin** [stenzek/duckstation#2429] opened 2021-07-20 13:11 UTC
When I'm playing with a gamepad (Xbox 360 controller) I can't access the Hotkeys, because I have bound all the buttons.

It seems to me that it would be ideal to be able to have the option of combining buttons to access the Hotkeys.

I edited the settings manually like this (see example), but it doesn't work. The first button activates the Hotkey and the "+ButtonX" is ignored.

Example:
```
[Hotkeys]
FastForward = Controller0/Button4+Button14
TogglePause = Keyboard/Space
ToggleFullscreen = Keyboard/Alt+Return
Screenshot = Keyboard/F10
PowerOff = Keyboard/Escape
LoadSelectedSaveState = Keyboard/F1
SaveSelectedSaveState = Keyboard/F2
SelectPreviousSaveStateSlot = Keyboard/F3
SelectNextSaveStateSlot = Keyboard/F4
OpenQuickMenu = Controller0/Button4+Button12
```

**Comment by stenzek** [comment] 2021-07-21 03:39
Duplicate of https://github.com/stenzek/duckstation/issues/1603

**Closed by stenzek** 2021-07-21 03:39 UTC
