### ISSUE TITLE
Basic game play recording for reporting issues.

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#1128] opened 2020-12-02 14:44 UTC
As the titles say, I know that people most likely already requested of some feature to record/stream directly from Ducko and I understand that's way to much hassle when something like OBS can do that for them.

What am proposing that you'd implement the most basic and simplest way to record game play so people will be able to showcase issues without a wall of google translated text or having to install and fiddle with some randoms recording programs from the net.

Cheers.

**Comment by stenzek** [comment] 2020-12-02 14:56
Duplicate of https://github.com/stenzek/duckstation/issues/752

This is built into Windows 10 - Windows key + G.

I've looked into using the media foundation framework for encoding video, but it's very picky about resolution. I also don't want to ship ffmpeg with the emulator because it would bloat the download size.

**Closed by stenzek** 2020-12-02 14:56 UTC

**Comment by foxsevent** [comment] 2020-12-02 15:07
Ah apologies then wasn't even aware of this feature in windows, maybe add this to the reporting issues template? it' definitely would make reporting issues easier.
