### ISSUE TITLE
PocketStation

### ISSUE THREAD

**Issue by 3gatsudarker** [stenzek/duckstation#1510] opened 2021-01-25 22:57 UTC
This might be a stretch and in the realm of emulating something else entirely but I was wondering if there were any plans or if its even possible to add support for this peripheral.

There's a list of games that use it on Wikipedia but some require it to even run like the Pocket Digimon World games, this peripheral was also emulated on the Playstation Vita and can still be downloaded from the Japanese PSN store and can be used with a bunch of PSX classics on the Japanese store like the Rockman 1-6 games as long as you have a save file for the supported games

**Comment by stenzek** [comment] 2021-01-26 03:25
Duplicate of #1009 (as ggrtk said, full system emulation is required in some cases for the cards alone).

**Closed by stenzek** 2021-01-26 03:25 UTC
