### ISSUE TITLE
Championship Motocross 2001 featuring Ricky Carmichael (USA) - Driver isn't rendered

### ISSUE THREAD

**Issue by HeroponRikiBestest** [stenzek/duckstation#272] opened 2020-04-10 18:05 UTC
It's exactly what it sounds like.
![image](https://user-images.githubusercontent.com/50224630/79012487-429adc00-7b1b-11ea-8e40-60e2c33d4050.png)

**Comment by kurayami6** [comment] 2020-04-11 02:38
Already reported it a month ago. I went through Mednafen's bug list and checked all of them in this emulator.

**Comment by stenzek** [comment] 2020-04-11 02:58
Duplicate of https://github.com/stenzek/duckstation/issues/43

I still have no idea what's causing this. The game doesn't send any of the driver's polygons to the GPU at all... might be timing related

**Closed by stenzek** 2020-04-11 02:58 UTC
