### ISSUE TITLE
[Request] [Libretro] disc management / change

### ISSUE THREAD

**Issue by DarthDarklorD** [stenzek/duckstation#623] opened 2020-07-18 02:47 UTC
Can't seem to find a workaround to swap disc image for Ducktation Retroarch core.
FANTASTIC performance otherwise.
No Disc control or m3u support found.
Can't seem to get renaming saves right either.
Metal Gear Solid in particular, as it doesn't prompt player to save upon disc change.
Thanks for your time!

**Comment by stenzek** [comment] 2020-07-18 02:57
Duplicate of #619 

For multi-disc games, the save file will change when you change the disc. So the first time you save on the second disc, it will be written to a new memory card.

**Closed by stenzek** 2020-07-18 02:57 UTC

**Comment by DarthDarklorD** [comment] 2020-07-20 11:09
I understand, however am also unable to locate a "disc control" feature or its equivalent.
This seems to preclude the user from utilizing the traditional .m3u method.
Certain games like Metal Gear Solid, require a "tray open" and "tray closed" status to begin initializing another disc / image.
No saves can be performed on the disc change screen in this game.
Attempts to move and modify saves have also failed on my part.
I've seen disc control on the standalone Duckstation interface but not the Retroarch core.
Again thank you for this amazing and efficient Emulator, adds replay value to my entire PSX library.
