### ISSUE TITLE
[PBPX-95002] Interactive CD Sampler Disc Volume 4 (USA) - Hangs in Armored Core demo

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#751] opened 2020-08-12 17:21 UTC
**Version**
0.1-1490-g76978986

**Issue**
If choose Armored Core demo, it freezes in black screen. the actual Armored Core game doesn't hag, just the demo in the Interactive CD Sampler 4. Tested in both interpreter and recompiler.

**Comment by stenzek** [comment] 2020-10-24 11:45
Closing due to inability to reproduce.

**Closed by stenzek** 2020-10-24 11:45 UTC

**Comment by Shideravan** [comment] 2020-12-03 18:57
It's solved in recents versions
