### ISSUE TITLE
RetroArch shaders support or some script for convertation :D ?

### ISSUE THREAD

**Issue by PavelDurov1488** [stenzek/duckstation#1479] opened 2021-01-20 12:50 UTC
I know that most propably the answer will be no, but actually RA has biggest shader pack

IMHO, mostly they are very incorrect (if we talk about CRT shaders), they need calibration and the goal should be not 1:1 CRT look like if you distance to your tv is 10 cm, it should be like your distance to tv is 1-2 meters

As for me, i made this with crt easymode(halation) + image calibration

Original
![image](https://user-images.githubusercontent.com/74456272/105177242-e6251c80-5b82-11eb-9ea3-785ed6067f31.png)
calibration+easymode-halation
![image](https://user-images.githubusercontent.com/74456272/105176656-ff799900-5b81-11eb-8e6c-2dd3aaf91e8a.png)
calibration+easymode
![image](https://user-images.githubusercontent.com/74456272/105177144-c261d680-5b82-11eb-902f-d57573c1950a.png)

Or maybe, if you are very clever and have time+original hardware, you can calibrate it for yourself with measures

**Comment by stenzek** [comment] 2021-01-20 15:29
Duplicate of https://github.com/stenzek/duckstation/issues/1133

slang is one of the formats I am considering using for post-processing. But I don't find it very interesting, so it may be some time before I work on it.

**Closed by stenzek** 2021-01-20 15:29 UTC

**Comment by PavelDurov1488** [comment] 2021-01-20 15:35
Retroarch has glsl pack too
https://github.com/libretro/glsl-shaders

**Comment by stenzek** [comment] 2021-01-20 15:36
That's great, but it doesn't help write a parser for these formats and integration.

**Comment by PavelDurov1488** [comment] 2021-01-20 18:56
![image](https://user-images.githubusercontent.com/74456272/105221549-bfcca480-5bb5-11eb-8df7-b41e47535aca.png)
