### ISSUE TITLE
Relative Mouse not carried over into Game Specific input properties

### ISSUE THREAD

**Issue by TheKins** [stenzek/duckstation#1673] opened 2021-02-22 18:40 UTC
**Game details**
All games, in general, but tested using SLUS-00757 - Quake II (USA)

**Description of the issue / bug**
When setting a controller profile in the Input Settings of a game's profile, the "Relative Mouse Mode" checkbox is ignored in favor of whatever the user has set in the "Duckstation Settings" window (or in favor of having it disabled if a mouse isn't set in the user's current Duckstation Settings)

**Controller Troubleshoot Report**
I use DS4Windows with no problems on that side.
Steam is open in the background, but I do not use its input stuff.
The SDL controller backend is used.

**Steps to reproduce**
1.) Save a controller profile that has the mouse plugged into an appropriate slot with Relative Mouse checked.
2.) Change your controls to something else (I set it to the "Xbox Controller" profile).
3.) Open the Game Properties window for a game that uses the mouse, and set the "Input Profile For Bindings" to your saved profile.
4.) Run the game. Relative Mouse will use the global properties instead of the game-specific ones.

**Enhancements information**
All enhancements were disabled via the Tweaks/Hacks menu before testing.

**Hardware/software**
Windows 10 Home v1909
AMD Ryzen 5 1600
GeForce GTX 1070

**Emulator version**
DuckStation 0.1-3250-g9d05aa21 (dev)

**Comment by stenzek** [comment] 2021-02-23 00:15
Actually much more difficult than you'd think - only bindings are loaded from the input profile (that's why it says bindings in the UI). Need to write a proper layered config system.

**Comment by stenzek** [comment] 2021-04-07 11:18
Duplicate of https://github.com/stenzek/duckstation/issues/1365

**Closed by stenzek** 2021-04-07 11:18 UTC
Labels: Feature Request
