### ISSUE TITLE
use the same filename format for the memory card of other libretro cores

### ISSUE THREAD

**Issue by eadmaster** [stenzek/duckstation#1132] opened 2020-12-02 19:07 UTC
Duckstation creates:
`Game Tile_1.mcd`
While other cores create:
`Game Tile.srm`

This will help sharing the memory card saves with other libretro cores without the need of manually renaming  for every game.

**Comment by stenzek** [comment] 2020-12-03 01:27
Duplicate of https://github.com/stenzek/duckstation/issues/1064

**Closed by stenzek** 2020-12-03 01:27 UTC
