### ISSUE TITLE
PGXP futur support?

### ISSUE THREAD

**Issue by legionpheonix** [stenzek/duckstation#666] opened 2020-07-25 10:47 UTC
Will there be Parallel / Precision Geometry Transform Pipeline support?

**Comment by stenzek** [comment] 2020-07-25 11:32
Duplicate of https://github.com/stenzek/duckstation/issues/6.

Yes, I have a branch with it, but it needs more work/optimizing.

**Closed by stenzek** 2020-07-25 11:32 UTC
