### ISSUE TITLE
Yellow bar on the right side of the screen in Muppet Monster Adventure (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#193] opened 2020-03-30 01:56 UTC
Happens with both OpenGL and D3D11.

![Capture2](https://user-images.githubusercontent.com/31968468/77868173-e8318e00-7285-11ea-949d-5b5c1525986a.PNG)

**Comment by stenzek** [comment] 2020-04-01 02:30
Unable to reproduce. Might've been fixed with the overscan changes.

**Closed** 2020-04-01 02:33 UTC
