### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by Anuskuss** [stenzek/duckstation#689] opened 2020-08-03 03:46 UTC
First I was very sceptical about this emulator since we already have a plethora of good alternatives for PlayStation 1 but after testing it I must admit that you did a pretty good job @stenzek 👍 . Here are my suggestions:
- [ ] Vulkan flickers when fast forwarding (same as [Dolphin](https://bugs.dolphin-emu.org/issues/11883#note-9)). A solution (for those without `VK_PRESENT_MODE_MAILBOX_KHR`) would be to just skip the frames/flips.
- [ ] Smart preloading into RAM, meaning preloading only the important parts and then loading the rest asynchronously in the background.
- [ ] Per-game configuration for overscan or automatic detection of black borders. Mednafen offers `psx.slstartp`/`psx.slendp` so we could collect those values and put them in a database (I could offer 10 values already).
- [ ] Advances configuration for inputs (similar to Dolphin). This would allow me to map `SHARE`+`OPTIONS` (DualShock 4) to *Analog*.
- [ ] Define recommended PS1 BIOSes and present the [hashes](https://github.com/stenzek/duckstation/blob/1f9fc6ab74798f4ef6a5c4822b6c6e9c261573f6/src/core/bios.cpp#L39) more prominently. Are there any known incompatibilities between revisions?
- [ ] Exit on close / Exit hotkey.
- [ ] `sbi` directory.
- [ ] Multitap.
- [ ] (CRT) Shaders (big fan of [blaarg's work](http://blargg.8bitalley.com/libs/ntsc.html)).

**Comment by stenzek** [comment] 2020-08-03 04:27
Closing, as there is already a thread for UI suggestions - https://github.com/stenzek/duckstation/issues/362. Other ideas should have their individual threads, as it better separates discussion.

> Vulkan flickers when fast forwarding (same as Dolphin). A solution (for those without VK_PRESENT_MODE_MAILBOX_KHR) would be to just skip the frames/flips.
Easier said than done. The Vulkan API provides no way to query whether vblank has passed yet.

> Smart preloading into RAM, meaning preloading only the important parts and then loading the rest asynchronously in the background.
Not really sure how one could do this. What is an "important" part? How would we find a general solution to identify these? For what it's worth, preloading an image only takes a couple of seconds off a NVMe SSD. Takes longer for CHD because decompression.

> Per-game configuration for overscan or automatic detection of black borders. Mednafen offers psx.slstartp/psx.slendp so we could collect those values and put them in a database (I could offer 10 values already).
Duplicate of https://github.com/stenzek/duckstation/issues/41

>  Advances configuration for inputs (similar to Dolphin). This would allow me to map SHARE+OPTIONS (DualShock 4) to Analog.
Should have its own thread.

>  Define recommended PS1 BIOSes and present the hashes more prominently. Are there any known incompatibilities between revisions?
Should go in the UI thread.

> Exit on close / Exit hotkey.
There's already a stop hotkey, but I guess an exit hotkey could be added too.

> sbi directory.
What's wrong with keeping the sbi files alongside the images? The names have to match anyway. I believe this is the same as other emus. Loading sbis based on game code would require non-trivial modifications to how CD images are loaded.

> Multitap.
Should have its own thread.

> (CRT) Shaders (big fan of blaarg's work).
Duplicate of https://github.com/stenzek/duckstation/issues/589

**Closed by stenzek** 2020-08-03 04:27 UTC

**Comment by Anuskuss** [comment] 2020-08-03 06:03
I'm sorry that some of those points were already being discussed in separate issues but I was just listing my suggestions in one convenient place as to not flood your repo with new issues.

> Easier said than done. The Vulkan API provides no way to query whether vblank has passed yet.

Well, at some point you're probably going to implement a frameskip anyway and that would be the perfect time to fix Vulkan (look for example at [PPSSPP's implementation](https://github.com/unknownbrackets/ppsspp/blob/cebcfb1bbd02512d8d3201cd28e5cb2b9da2266c/Core/HLE/sceDisplay.cpp#L563)).

> Not really sure how one could do this. What is an "important" part?

The important part would be the EXE where you're emulator reads everything synchronously until things get going and when it's done loads the rest of the image asynchronously into memory. Again, I'll refer to the incredible emulator that is [PPSSPP](https://github.com/hrydgard/ppsspp/pull/8278).

> Duplicate of #41

You totally ignored the second part of that suggestion: automatically detecting black borders (I think that's how Dolphin does it).

> Should go in the UI thread.

README should be fine. And I'm assuming by not answering the question in that suggestion that the answer is no (incompatibilities between revisions).

> What's wrong with keeping the sbi files alongside the images? The names have to match anyway.

Same name but different location. ROM organisation tools (like ClrmamePro) demand a separation between ROMs and "extra data" (well technically it's part of the disc but that's another story). My point was that it would still look for the `name.sbi` but first in the ROM folder and then in the `sbi` folder.

**Comment by stenzek** [comment] 2020-08-03 06:49
> I'm sorry that some of those points were already being discussed in separate issues but I was just listing my suggestions in one convenient place as to not flood your repo with new issues.
> 
> > Easier said than done. The Vulkan API provides no way to query whether vblank has passed yet.
> 
> Well, at some point you're probably going to implement a frameskip anyway and that would be the perfect time to fix Vulkan (look for example at [PPSSPP's implementation](https://github.com/unknownbrackets/ppsspp/blob/cebcfb1bbd02512d8d3201cd28e5cb2b9da2266c/Core/HLE/sceDisplay.cpp#L563)).

Why would I need frame skipping? Running with vsync off/immediate present works fine.


> 
> > Not really sure how one could do this. What is an "important" part?
> 
> The important part would be the EXE where you're emulator reads everything synchronously until things get going and when it's done loads the rest of the image asynchronously into memory. Again, I'll refer to the incredible emulator that is [PPSSPP](https://github.com/hrydgard/ppsspp/pull/8278).

Loading the whole image in the background is a possible solution. Feel free to create a separate issue for it.

> 
> > Duplicate of #41
> 
> You totally ignored the second part of that suggestion: automatically detecting black borders (I think that's how Dolphin does it).

Crop settings including start/end horizontal ticks and lines is something I will be including in gameinis, as well as disabling problematic enhancements, and forcing interlacing on. FWIW, as far as I'm aware Dolphin doesn't have per-game values for overscan.

> 
> > Should go in the UI thread.
> 
> README should be fine. And I'm assuming by not answering the question in that suggestion that the answer is no (incompatibilities between revisions).
> 

You can find the hashes/filenames by googling easily enough. Other users have suggested automatic scanning of all files in a directory based on hash for detecting BIOSes, and that's probably the route I'd go down. I'm not aware of any issues with mismatching BIOSes, but DS will still attempt to use the appropriate BIOS for the region of game you're running.

> > What's wrong with keeping the sbi files alongside the images? The names have to match anyway.
> 
> Same name but different location. ROM organisation tools (like ClrmamePro) demand a separation between ROMs and "extra data" (well technically it's part of the disc but that's another story). My point was that it would still look for the `name.sbi` but first in the ROM folder and then in the `sbi` folder.

I really dislike the idea of complicating logic to handle some third-party program. Why should the emulator have to confirm to some tool's convention, especially when it is **not** the standard amongst other emulators.

**Comment by Anuskuss** [comment] 2020-08-03 07:19
> Why would I need frame skipping?

For weaker devices?

>Why should the emulator have to confirm to some tool's convention, especially when it is not the standard amongst other emulators.

Don't focus too much on the "other tool's convention" but look at it from a customizability standpoint. You know what `$PATH` is right? Same thing, you start by looking in the game directory, then the `sbi` directory and if both these checks fail you return false. Keeping everything organized is important for maintainability.

**Comment by stenzek** [comment] 2020-08-03 07:21
> For weaker devices?

Do you mean frame skipping as in skipping presentation or skipping rendering? Skipping rendering is something I will **never** do, it will break way too many games. If you want frame skipping, use an emulator from the 90s/00s. Weaker devices can already run DS fine, so long as they meet the modest requirements (64-bit, GLES 3 GPU).

> Don't focus too much on the "other tool's convention" but look at it from a customizability standpoint. You know what $PATH is right? Same thing, you start by looking in the game directory, then the sbi directory and if both these checks fail you return false. Keeping everything organized is important for maintainability.

The CD image loader takes an absolute path. Having it search multiple directories complicates that logic, although not _too_ much. I just don't see why I should have to support some third party tool that I do not care about, even more so when other emulators don't do this.

**Comment by Richard-L** [comment] 2020-08-03 07:30
ClrMamePro is a pretty big deal though Stenzek, if you're unaware.

I get why you're reluctant though.

**Comment by stenzek** [comment] 2020-08-03 07:39
> ClrMamePro is a pretty big deal though Stenzek, if you're unaware.

Clearly it's only intended for MAME, because otherwise they wouldn't be forcing a different standard on everyone else.

If I was to improve sbi handling, what I would probably do would be to search a `sbi` directory in the duckstation folder, using the game's serial/code as a name to lookup (e.g. `SCES-02834.sbi`). That would be more straightforward for users, as they wouldn't have to worry about ensuring the name of the sbi matches the disc image. However, that would break with the handful games where the serial can't be obtained (missing `SYSTEM.CNF`).

**Comment by Anuskuss** [comment] 2020-08-03 07:54
It's kinda becoming a moot point but don't look at this that way; it's not about conforming to the rules set by another tool. It's about having the freedom to decide and keeping you're collections tidy. I don't put my cutlery in the same place as my dishes for the same reason you keep the settings of duckstation inside *My Documents* instead of besides the binary. Now you're conforming to the rules set by some company without even questioning it ;)

> If I was to improve sbi handling, what I would probably do would be to search a `sbi` directory in the duckstation folder, using the game's serial/code as a name to lookup (e.g. `SCES-02834.sbi`). That would be more straightforward for users, as they wouldn't have to worry about ensuring the name of the sbi matches the disc image. However, that would break with the handful games where the serial can't be obtained (missing `SYSTEM.CNF`).

Don't overengineer it. Just get the filename, remove the extension, and look for `My Documents/duckstation/sbi/<FNAME>.sbi`.

**Comment by stenzek** [comment] 2020-08-03 07:59
> Don't overengineer it. Just get the filename, remove the extension, and look for My Documents/duckstation/sbi/<FNAME>.sbi.

If I'm going to make it more complex it'll be to solve an issue I've seen from users - that is they don't realize they have to rename the sbi file to match their disc image.

I'm still very much against this idea of separating sbi files from the image anyway. The subchannel data is **part of the disc image**, so why should it go somewhere else? It really should be part of the CHD, CHD does actually store the subchannel data, just none of the tools support merging bin/cue with sbi.
