### ISSUE TITLE
[SLUS-01019] Threads of Fate (USA) - Graphical errors in "Recompiler mode"

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#710] opened 2020-08-05 01:22 UTC
**Version**
0.1-1419-g34a515cd

**Issue**
Broken polygons in "recompiler mode".

![image](https://user-images.githubusercontent.com/12163923/89361161-e860f080-d6a0-11ea-8ed4-482ed347cd37.png)
![image](https://user-images.githubusercontent.com/12163923/89361167-ed25a480-d6a0-11ea-9d63-75c7a93ad9ce.png)

**Comment by stenzek** [comment] 2020-08-05 03:15
Duplicate of https://github.com/stenzek/duckstation/issues/358

**Closed by stenzek** 2020-08-05 03:15 UTC
