### ISSUE TITLE
Duckstation problems on Retroarch Android

### ISSUE THREAD

**Issue by Deivmsr** [stenzek/duckstation#599] opened 2020-07-11 02:07 UTC
I tested the duckstation core on Android and found some problems. When starting a game, a distorted image of the virtual controls appears as shown in the attached image. In Vulkam, the emulator is in black screen.
Tested the latest version on my Galaxy Note 9, SD 845.
![Screenshot_20200710-212803](https://user-images.githubusercontent.com/40547165/87214364-be165000-c2f9-11ea-8396-5f99b498c5e5.jpg)

**Comment by stenzek** [comment] 2020-07-11 05:57
Hmm, strange that it's messing with the controls. Will have to throw it at renderdoc if I can get it working on Android.

I'm aware of the Vulkan issue, it crashes on Mali too. Need to debug it further.

**Comment by stenzek** [comment] 2020-07-11 14:49
I'm not able to reproduce the broken screen on OpenGL with my device, it must be specific to Adreno. Will have to try to get it working on one of my Adreno phones.

Vulkan is working on Mali as of https://github.com/stenzek/duckstation/commit/113b0f57d65639e89ed80052c885f7710e7f6573 (or the latest build), hopefully will also work with Adreno.

**Comment by Deivmsr** [comment] 2020-07-11 22:14
I tested version 8febf5d, and the distortion in the controls only occurs in OpenGL. Vulkan is now working, but the 2x upscale option does not have the same effect as in OpenGL. Vulkan is having this checkered effect on the image (image attached).
![Screenshot_20200711-175411](https://user-images.githubusercontent.com/40547165/87234738-06894880-c3a2-11ea-9443-001293d66829.jpg)

**Comment by stenzek** [comment] 2020-07-12 02:36
Looks normal to me. What you're seeing is the dithering pattern present in most games.

It's more noticeable in RetroArch than in the standalone version because by default it doesn't use bilinear filtering. If you enable bilinear filtering in your video options and up the internal resolution, it should smooth it out a bit.

Alternatively, you can enable true colour in the DuckStation core options - but this will break some games.

**Comment by stenzek** [comment] 2020-08-04 10:38
I think this is fixed now - worked around an Adreno driver bug a little while back.

**Closed by stenzek** 2020-08-04 10:38 UTC
