### ISSUE TITLE
Vulkan choice crashes DS on hardware not Vulkan-compatible

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#668] opened 2020-07-25 15:24 UTC
If possible, perhaps grey out Vulkan when the hardware does not support it. Currently it just kills DS when running a game with Vulkan selected.

**Comment by stenzek** [comment] 2020-08-02 16:18
I'm not seeing a crash - just two failure messages.

I could enumerate GPUs and remove it when there's none, but the problem is that would add a delay to opening the settings dialog, freezing it for a couple of seconds (it's worse on laptops with discrete GPUs).

**Comment by Richard-L** [comment] 2020-08-02 16:57
I've had both cases where it survives or crashes.

And I see what you mean. Is there something that can fail very quickly if there's no Vulkan available, which would act as a hidden test upon launching emulation, to then prompt a message "Your GPU does not support Vulkan" or similar?

**Comment by stenzek** [comment] 2020-11-30 16:18
Fixed in https://github.com/stenzek/duckstation/commit/bccecdbf1864761364c4ae588f01c67bcbf2aa32

**Closed by stenzek** 2020-11-30 16:18 UTC
