### ISSUE TITLE
performance issue: slow battle transition [tales of phantasia]

### ISSUE THREAD

**Issue by negativeExponent** [stenzek/duckstation#653] opened 2020-07-23 04:03 UTC
just a quick test on current game im finishing (or trying to anyways). just notice battle transitions takes way too long regardless if running software,gl,vulkan or the different cpu modes.

heres an example scene: (no video)
![duckstation-slowbattletransition-issue](https://user-images.githubusercontent.com/54053706/88251155-7ff73400-ccdc-11ea-81b9-44bec8bde058.png)

**Comment by Sanaki** [comment] 2020-09-27 04:37
I reproduced this reliably myself in the libretro core using 8342fec2c865c03379750ba77969db5a9716e8fb on x86_64 Linux, with default settings. It took 17 seconds for the battle animation to finish and the battle to start. Tried various setting tweaks, including glcore/vulkan/software, preload to RAM, interpreter, synchronous CD access, CD region check enabling, etc. to no avail. I tested both bin+cue and chd, both from my SSD. My copy of the game has been verified against redump's information. The issue is specific to this core as well.

**Comment by stenzek** [comment] 2020-09-28 12:07
This is due to the GPU draw timing approximation failing for the types of triangles the game is drawing here (large and narrow).

See here: 
![image](https://user-images.githubusercontent.com/11288319/94430163-cf734800-01d6-11eb-8ffc-483548af90a6.png)

Still searching for a solution which doesn't involve disabling GPU draw timings completely, and is efficient enough to use with the hardware renderers.

**Comment by stenzek** [comment] 2020-09-28 13:19
I have a potential fix, just needs some more testing in case of regressions.

**Comment by stenzek** [comment] 2020-10-03 14:15
Should be fixed with https://github.com/stenzek/duckstation/commit/50b025c75aa5a13e0dba83ede19f28a8bd7472ce. Haven't tested in libretro, but it shouldn't be any different.

**Closed by stenzek** 2020-10-03 14:15 UTC
