### ISSUE TITLE
[SCUS-94449] - Omega Boost (USA) graphical errors in pre-mission screen

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#1137] opened 2020-12-03 20:19 UTC
**Game details**
[SCUS-94449] - Omega Boost (USA) 

**Description of the issue / bug**
[Describe what you are seeing and/or hearing during gameplay]
![image](https://user-images.githubusercontent.com/12163923/101083152-4f2ce280-358b-11eb-82e0-fd26673ddb6b.png)

**Steps to Reproduce**
Just start the game, in this screen we'll see the error. The green info don't even "blinks" in original hardware.
Take a look what is spected: https://youtu.be/1L2BJ-TCU9k?t=344

**Hardware/software**
Windows 10, i7-4790, Geforce 1070

**Emulator version**
0.1-2433-g9089c973

**Comment by stenzek** [comment] 2020-12-04 15:15
Seems to be due to the GPU being too slow.

**Comment by Nucleoprotein** [comment] 2020-12-04 15:50
Reproduced here, blinks like crazy.

**Comment by stenzek** [comment] 2020-12-04 16:02
A workaround for now is to overclock to 125%, but there's probably something else going on here.

**Comment by Nucleoprotein** [comment] 2020-12-04 16:19
It happens on interpreter with software renderer too.
Also in interpreter mode with software rendering FMV displays incorrectly:
![SCUS-94449_2020-12-04_17-19-36](https://user-images.githubusercontent.com/8019035/101187619-e01bc080-3654-11eb-9beb-531307f7b7d0.png)

**Comment by stenzek** [comment] 2020-12-05 15:20
Fixed in https://github.com/stenzek/duckstation/commit/5e05a14f9719c6a20a999d6767963ba9709d8eab.

**Closed by stenzek** 2020-12-05 15:20 UTC
Labels: GPU
