### ISSUE TITLE
Medievil (Italy) probably anti-piracy measure

### ISSUE THREAD

**Issue by Hereward-GH** [stenzek/duckstation#1114] opened 2020-11-28 10:56 UTC
Every time i've tried to play "The Hilltop Mausoleum" the game stops with this image.
![SCES-01494_2020-11-28_11-51-49](https://user-images.githubusercontent.com/16437893/100513882-9e7ca880-3170-11eb-9dd8-e504eb0cc32f.png)

**Comment by stenzek** [comment] 2020-11-28 10:57
Have you added the sbi file alongside the image?

**Comment by Hereward-GH** [comment] 2020-11-28 10:58
Ehm... no.

**Comment by stenzek** [comment] 2020-11-28 11:03
For libcrypt games you need the sbi file with the same name as your disc image. You can get the sbi files from redump.org or other sources.

**Comment by Zet-sensei** [comment] 2020-11-28 11:31
Confirmed.
Anti-piracy protection with that icon on the game.

**Comment by stenzek** [comment] 2020-11-28 11:43
Thanks @Zet-sensei , I'll close this since I'm assuming it works fine with the sbi.

**Closed by stenzek** 2020-11-28 11:43 UTC
Labels: Possibly Invalid
