### ISSUE TITLE
Mouse won't lock at the center of the screen when using the PS Mouse input.

### ISSUE THREAD

**Issue by Skynet19972029** [stenzek/duckstation#1124] opened 2020-12-01 14:54 UTC
No matter which game you try that uses the PS Mouse, the mouse won't lock and by proxy, you can't do 360 degree turns, since the mouse will hit the border of your screen.

The hobo... eSHITe does this for example.

**Comment by stenzek** [comment] 2020-12-01 14:57
Duplicate of https://github.com/stenzek/duckstation/issues/739

**Closed by stenzek** 2020-12-01 14:57 UTC
