### ISSUE TITLE
Video recording

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#351] opened 2020-04-26 21:19 UTC
The emulator already has the ability to record audio. Recording video would be very useful as well. There are quite a few bugs I've found that can't be seen with just a screenshot and need to be recorded.

**Comment by stenzek** [comment] 2020-04-27 02:54
Easier said than done, I'd rather not bloat the emulator by including something like ffmpeg, so it'd have to use the native OS APIs.

**Comment by stenzek** [comment] 2020-08-18 08:57
Duplicate of #752.

**Closed by stenzek** 2020-08-18 08:57 UTC
Labels: enhancement
