### ISSUE TITLE
Graphical and audio bugs in Lyapis Trubetskoy (Russia) (Unl)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#393] opened 2020-05-05 03:34 UTC
BIOS screen doesn't fade out properly and the BIOS reverb continues forever. It never stops no matter how long you play for. 

![2020-05-05_13-28-36](https://user-images.githubusercontent.com/31968468/81032924-03229e00-8ed5-11ea-9b2f-d5027adbfab2.png)

**Comment by stenzek** [comment] 2020-10-24 12:06
Duplicate of https://github.com/stenzek/duckstation/issues/407

**Closed by stenzek** 2020-10-24 12:06 UTC
