### ISSUE TITLE
[Android] Navigation Bar does not get themed in Android 10

### ISSUE THREAD

**Issue by hhromic** [stenzek/duckstation#1591] opened 2021-02-06 21:59 UTC
**Game details**
N/A

**Description of the issue / bug**
DuckStation does not properly color the *Navigation Bar* in my stock Samsung Galaxy A70 nor a Galaxy A50, both with Android 10. As you can see below, the navigation bar remains "light themed" despite the app being using the Dark Theme.

![image](https://user-images.githubusercontent.com/5802993/107130441-69ee4100-68c5-11eb-8231-acbce4516977.png)

For reference, Lemuroid on the same phone does properly color the navigation bar:

![image](https://user-images.githubusercontent.com/5802993/107130502-f6006880-68c5-11eb-88b1-cb9ddd2b09ae.png)

I'm no Android developer, however after inspecting a bit Lemuroid's source code, it looks like that DuckStation is just missing navigation bar coloring properties?

https://github.com/Swordfish90/Lemuroid/blob/master/lemuroid-app/src/main/res/values/styles.xml

Home Assistant is another application that I use on the same phone and that also colors the navigation bar properly. I found th relevant source code for that app in here:

https://github.com/home-assistant/android/blob/bd0d10d316fcd575295bdf98bb0f734e107138a7/app/src/main/java/io/homeassistant/companion/android/webview/WebViewActivity.kt#L782-L792

Hope any of that is useful somehow.

**Controller Troubleshoot Report**
N/A

**Note:**
Both phones are pretty stock, there are no optimisation apps installed.

**Steps to reproduce**
Just open DuckStation in a Samsung Galaxy A70, or Galaxy A50, with Android 10 (highly likely not only restricted to this model) and observe the Navigation Bar not going dark colored when using the Dark Theme.

**Enhancements information**
N/A

**Hardware/software**
Samsung Galaxy A70 / Android 10
Samsung Galaxy A50 / Android 10

**Emulator version**
0.1-3019-g3c2b11fc (master)

**Additional context**
N/A

**Comment by hhromic** [comment] 2021-02-06 22:19
Just tested with a Galaxy A50, also with Android 10, and the issue is also present.

**Comment by Nucleoprotein** [comment] 2021-02-07 08:12
I think navbar is black by design, because in light theme it's blueish.

**Comment by hhromic** [comment] 2021-02-07 08:53
> I think navbar is black by design, because in light theme it's blueish.

Can you elaborate more what do you mean? In Light Mode the nav bar remains the same light-gray,  not blueish:

![Screenshot_20210207-084443_DuckStation](https://user-images.githubusercontent.com/5802993/107141557-64bedf80-6921-11eb-96fe-bdc1d406a512.png)

Btw, I just realised that Lemuroid doesn't follow the system dark mode settings, but is always dark. I.e. has a fixed style. 

Anyway, DuckStation seems to be not be setting any navbar color thus it just remains default light gray regardless of chosen theme. I think the home assistant example code is better (changes according to theme). Lemuroid on the other hand is always black (fixed style).

**Comment by hhromic** [comment] 2021-02-07 08:56
Just in case there is a confusion, the Navigation Bar is the one with the Home, Menu, Back buttons down below:

![20210207_085535](https://user-images.githubusercontent.com/5802993/107141681-689f3180-6922-11eb-94bb-fd8065d3a4d6.png)

**Comment by Nucleoprotein** [comment] 2021-02-07 09:33
sorry, i was thinking about top bar, i dont have that bar, i use gestures

**Comment by stenzek** [comment] 2021-02-07 15:24
Fixed in https://github.com/stenzek/duckstation/commit/515b85fa36da947765595298d11f102bdb202a9c

**Closed by stenzek** 2021-02-07 15:24 UTC

**Comment by hhromic** [comment] 2021-02-07 16:21
That's great! Thanks! Looking forward for the next version in the store to check it out.

I noticed that you used the same black navbar color for both, the regular and night values. Does this mean that the light theme also will have a black navbar?  Not a big deal but maybe is better to stick with the light-colored navbar for visual consistency?

As shown in my comment here: https://github.com/stenzek/duckstation/issues/1591#issuecomment-774637279

Thanks in any case for the fix, appreciated.

**Comment by stenzek** [comment] 2021-02-07 16:45
> Does this mean that the light theme also will have a black navbar? Not a big deal but maybe is better to stick with the light-colored navbar for visual consistency?

Yeah, but I couldn't find a colour which looked "good". Feel free to suggest one :)

> That's great! Thanks! Looking forward for the next version in the store to check it out.

I've pushed it to the open testing channel, if you enrol in the beta you should get it.

**Comment by hhromic** [comment] 2021-02-07 17:13
I enrolled in the beta program now. It looks good! I tested the light theme and it doesn't look that bad with a black navbar after all. So I would say just leave it like that for now. 

Moreover I found some apps like WhatsApp also keep the navbar black in light themes so.. 🤷‍♂️ 

<img src="https://user-images.githubusercontent.com/5802993/107153774-2d732180-6967-11eb-96ef-ac3dc5ce118a.png" width="33%" />

<img src="https://user-images.githubusercontent.com/5802993/107153780-34019900-6967-11eb-9a98-a37db850cd42.png" width="33%" />

Cheers!
