### ISSUE TITLE
Multitap Memcards

### ISSUE THREAD

**Issue by wheelmac92** [stenzek/duckstation#2294] opened 2021-06-21 02:11 UTC
While multitap is enabled, the memory card in Slot 1 is the only one that works. Slot 2 does not work, even with a card inserted in settings, Slot 3+4 dont exist.

Can there please be functionality for multiple memory cards while multitap is inserted? The prototypes for Crash Team Racing require a dongle in memory card slot 2, or they cannot boot. Therefore, the only way to play the prototypes with friends is to disable multitap in settings, then boot the game, then re-enable multitap.

The same applies to retail (non-prototype) games that support multiple memory card functionality with multitap

**Comment by stenzek** [comment] 2021-06-21 02:19
Issue template not completed, closing.

Working as intended though. Slot 2 becomes slot 5 when multitap is enabled on port 1. I don't support prototypes since they're technically piracy. If there's any retail games which need multitap memory cards, then I'd consider it a feature request.

**Closed by stenzek** 2021-06-21 02:19 UTC
