### ISSUE TITLE
Request: Rotate Game Screen

### ISSUE THREAD

**Issue by io3432iooivzs** [stenzek/duckstation#1894] opened 2021-03-31 15:06 UTC
Hi.
I enjoy PS1 Game on this  emulator.

Request, Rotate Game Screen or Window.
Some Games has a 90 degree rotate screen mode.
Like "Namuco Museum" Series, "Capcom Generation" Series, "Donpachi", etc

These games are Arcade Game, Original Game fitted vertical-longed monitor.
Most of these games have a normal screen (horizontal-longed) mode also, but some games have a little problem in normal mode.
For example, Donpachi's normal mode miss the Screen Edge, but 90 rotate screen mode is correct display.

I like that's Shooting Game, I hope you implement it.

**Comment by stenzek** [comment] 2021-03-31 15:13
> For example, Donpachi's normal mode miss the Screen Edge, but 90 rotate screen mode is correct display.
Try changing the crop mode.

Otherwise, rotation is duplicate of https://github.com/stenzek/duckstation/issues/770

**Closed by stenzek** 2021-03-31 15:13 UTC
