### ISSUE TITLE
an covers bug.

### ISSUE THREAD

**Issue by zkdpower** [stenzek/duckstation#1998] opened 2021-04-19 23:21 UTC
if the duckstaion user directory already have the game cover, especial same name with ISO, in this case, to assign the cover in game list/grid by hand would be ineffective.

**Comment by stenzek** [comment] 2021-04-22 04:02
Not sure what the issue is here - there was a bug in the preview build where file title-based cover matching was broken, but that was fixed in https://github.com/stenzek/duckstation/commit/c4891af00ea292cec16565f38cb59c1243c50e7e

**Closed by stenzek** 2021-04-22 04:02 UTC
