### ISSUE TITLE
Need Input Movie recorder

### ISSUE THREAD

**Issue by BCGamerYT** [stenzek/duckstation#2220] opened 2021-06-05 04:51 UTC
**Is your feature request related to a problem? Please describe.**
Input movie or movie recorder is a can replay game to view movie in the game. It can be re-record via savestates.

**Comment by stenzek** [comment] 2021-06-05 05:56
Duplicate of https://github.com/stenzek/duckstation/issues/752

**Closed by stenzek** 2021-06-05 05:56 UTC
