### ISSUE TITLE
Runahead with recompiler hangs FF9

### ISSUE THREAD

**Issue by realnc** [stenzek/duckstation#2789] opened 2021-12-28 19:26 UTC
**Game details**
SLUS-01251, USA

**Description of the issue / bug**
When enabling runahead, some battle transitions in Final Fantasy IX (1.1, USA) will cause the game to lock.

**Steps to reproduce**
* In "Console Settings," make sure "Execution Mode" is at its default setting, which is "Recompiler (Fastest)."
* In "Emulation Settings", set "Runahead" to 2.
* Start disc 1 of the game.
* Select "New Game."
* Fast-forward or tubo to quickly get past the intro video.
* Light the candle on the table in front of you.
* Confirm your character name.
* Advance the dialogue boxes until the battle starts.

When the boss enters the room and the game tries to transition to the battle screen, the game will be in a perpetual black screen with the battle screen never appearing.

**Enhancements information**
All settings in the "Enhancement Settings" section are at their defaults.

**Hardware/software**
Gentoo Linux AMD64
GTX 980 Ti
Software renderer

**Emulator version**
0.1-4854-gbee50481 (master)
(duckstation-qt-x64.AppImage)

**Comment by realnc** [comment] 2021-12-29 12:38
An additional note:

If during the black screen you change execution mode to "Interpreter", the game will unlock and the battle scene will load. If you then change execution mode back to recompiler, then there is a high chance the game (and this time audio too) will hard-lock during the battle when characters are attacking.

**Comment by stenzek** [comment] 2022-01-06 12:48
Duplicate of #2781, should be fixed by https://github.com/stenzek/duckstation/commit/541947c6f8f0bf674b38a647a5700fb6a647687e

**Closed by stenzek** 2022-01-06 12:48 UTC
