### ISSUE TITLE
BIOS screen doesn't fade out properly in Metamor Panic - Doki Doki Youma Busters!! (Japan)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#403] opened 2020-05-06 12:19 UTC
![SLPS-00039_2020-05-06_22-18-29](https://user-images.githubusercontent.com/31968468/81175936-b4b1f400-8fe7-11ea-907b-a03a7bd308a8.png)

**Comment by stenzek** [comment] 2020-05-08 04:10
As with the others this needs to be checked on console.

**Comment by ggrtk** [comment] 2020-10-24 10:58
This doesn't occur when tested on console, but I'm also unable to reproduce this issue both before and after the latest CRTC update, so was likely fixed by another change some while ago.

**Comment by stenzek** [comment] 2020-10-24 11:23
Thanks for checking!

**Closed by stenzek** 2020-10-24 11:23 UTC
Labels: Needs Console Verification
