### ISSUE TITLE
Changing discs when "preload to ram" is enabled issue.

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#1129] opened 2020-12-02 14:57 UTC
Not sure if this counts as a real issue since it's cause by "preload to ram" but I'll post it anyway.

**Game details**
SLUS-01042 Parasite Eve 2

**Description of the issue / bug**
As the tittle, if "preload to ram" is enabled and you switch discs in PE2 the game eventually freeze but not before showing some messed up 3D models, like streching them across the screen, even game logic is affected, targeting enemies doesn't work.

**Steps to Reproduce**
Basically switch discs in PE2 when 'preload to ram" is enabled.

**Hardware/software**
PC WIN10

**Emulator version**
Newest

![SLUS-01055_2020-12-02_15-51-55](https://user-images.githubusercontent.com/64225743/100888959-effd9e00-34b6-11eb-839b-9903c3d373a5.png)
![SLUS-01055_2020-12-02_15-51-58](https://user-images.githubusercontent.com/64225743/100888963-f12ecb00-34b6-11eb-8c5a-fcac410b989b.png)
![SLUS-01055_2020-12-02_15-52-00](https://user-images.githubusercontent.com/64225743/100888966-f12ecb00-34b6-11eb-8c87-c574413dff78.png)
It's had to tell, but that monster shouldn't look like that with it's back legs consistently in the air.

Obvious quick fix is to play with "preload to ram" disabled.

**Comment by foxsevent** [comment] 2020-12-02 15:24
Thanks to stenzek I learned something new today.:)
Here's a video of the issue and a memory card with that save, thou for some reasons windows doesn't record the menu when I switch discs, I just select change disc - playlist - disc two.
https://youtu.be/r1UD-vMWBFo
[Parasite Eve II_1.zip](https://github.com/stenzek/duckstation/files/5630274/Parasite.Eve.II_1.zip)

**Comment by Zet-sensei** [comment] 2020-12-02 15:55
We had the same problem with a user when he tried to play Valkyrie Profile some days ago & reported the problem on the Discord Support section.

You can't switch discs without issues when using the 'Preload into RAM' option.

**Comment by andercard0** [comment] 2020-12-02 16:06
Issue easily reproduceable:

Happened here with **Legend of Dragoon ** as quoted by Zet.

1.after load CD from 1 to 4

2.change multisample into 2x
Resulting:

![unknown.png](https://user-images.githubusercontent.com/43047877/100897788-d4869900-349e-11eb-8fdc-7063ed119333.png)

  Even if i try to return default values game does not at all.

**Comment by foxsevent** [comment] 2020-12-04 17:56
Yeah changing discs with "preload to ram" be broken now it just freezes the game, see clip below.
Basically I start the playlist which boots up disc 1 then I go change disc to disc 2 and reset, and I get a black screen.
https://youtu.be/BwRtjPdNLL8

**Comment by stenzek** [comment] 2020-12-05 15:20
I can't seem to reproduce this, only had it happen once.

It _could_ be memory allocations conflicting with the fastmem range, in which case https://github.com/stenzek/duckstation/commit/8b3426a96e24cd6456829166b49e8830c9a4464d might help mitigate it.

**Comment by foxsevent** [comment] 2020-12-05 15:56
> I can't seem to reproduce this, only had it happen once.
> 
> It _could_ be memory allocations conflicting with the fastmem range, in which case [8b3426a](https://github.com/stenzek/duckstation/commit/8b3426a96e24cd6456829166b49e8830c9a4464d) might help mitigate it.

Using the new version this issues seems to be fixed on my end at least, game no longer glitches like in the first video or freezes like the second.

I'll leave this open if the other two want to report if thier issue is fixed or if stenzek wants it can be closed.

**Comment by stenzek** [comment] 2020-12-12 01:55
I'll close this as nobody else has reported the issue is still happening. If it is, please update and I'll re-open.

**Closed by stenzek** 2020-12-12 01:55 UTC
