### ISSUE TITLE
Vampire Hunter D U [SLUS 01138], Duckstation Main Menu, Black Screen Problem

### ISSUE THREAD

**Issue by DarkFrost89** [stenzek/duckstation#495] opened 2020-05-26 09:21 UTC
Just Have Manin Manu Problem,Another ingame elements Works Good
[https://www.youtube.com/watch?v=RDwRkLiWKSI](url)

**Comment by stenzek** [comment] 2020-05-26 09:29
Duplicate of https://github.com/stenzek/duckstation/issues/121

**Closed by stenzek** 2020-05-26 09:29 UTC
