### ISSUE TITLE
Resume state for playlists

### ISSUE THREAD

**Issue by tycooko** [stenzek/duckstation#1727] opened 2021-03-02 23:00 UTC
Hello.
On both Windows and macOS, when trying to resume a game by clicking on an .m3u playlist file, the emulator reboots the game, whereas on an Android device it does what I would like it to do: it looks for the latest savestate for that game and starts that. I'm using the same game files (.bin, .cue, .m3u; also, the same memory cards files) for all the versions of the emulator.
My way of creating the playlists is to have the .bin files in the same folder as the .m3u file, which has the list of .bin files (ordered as the original discs) written in it. Initially, I had tried keeping both the .bin and the .cue and then write the list of .cue in the playlist file, but the emulator displayed both the individual discs and the playlist.
As said, this way of creating the .m3u playlists works well on Android, but, apparently, not with the desktop versions of DuckStation.
Any help is appreciated!

**Comment by stenzek** [comment] 2021-03-03 07:17
Duplicate of #1668 (the underlying issue is that the disc isn't remembered, thus it can't resume a state from it).

**Closed by stenzek** 2021-03-03 07:17 UTC
Labels: Feature Request

**Comment by tycooko** [comment] 2021-03-11 12:36
So...I don't know if these issues are also connected to this, but, since I suspect they are, I'll put them here instead of opening a new thread.

1) It is not possible to control the individual game's properties when you only have the playlist displayed (one could want to set certain properties for all discs belonging to that playlist, for instance): the right-click menu option is greyed out and selecting View --> Game Properties from the upper menu doesn't do anything. I've ended up setting them manually by writing them in gamesettings.ini .
2) Even with the workaround just mentioned above, **the playlist never saves the information for the texture filtering**, always reverting to whatever is being used globally, set in the main settings. I can literally see "GPUTextureFilter = whatever" set in gamesettings.ini, but the playlist simply ignores it (it's easy to confirm, as I can change the texture filtering while the game is on, and I see DuckStation compiling shaders as a result).
It's not a problem with a specific game (the game would be Final Fantasy VII, by the way): when I remove the .m3u file from the game's folder and I put .cue files so that DS may display the individual CDs, I can save whatever texture filter I want in each respective settings and it works.

**Comment by stenzek** [comment] 2021-03-11 13:07
That's because playlists aren't games. Game properties use the game serial as an identifier and playlists don't have an identifier. You can still set the properties on each game and it should apply, assuming the individual game was scanned.

I don't like the idea of playlists, they seem redundant with a game list, so I'm not planning on changing this.

Will check that texture filters are applying soon.

**Comment by tycooko** [comment] 2021-03-11 13:47
> That's because playlists aren't games. Game properties use the game serial as an identifier and playlists don't have an identifier. You can still set the properties on each game and it should apply, assuming the individual game was scanned.

What I'm saying is:
1) I have 2, 3 or whatever the number of CDs/bins is, inside the same folder. I don't create .cue files for the CDs. Instead, I directly create a .m3u file, so the first thing DuckStation ever shows of that game is a playlist with all the CDs/bins inside.
2) I edit the gamesettings.ini file and set a specific aspect ratio for all the CDs in the playlist as well as the texture filter.
3) The aspect ratio is respected and has an actual result on screen and, from that moment on, I can change the setting for the aspect ratio in the main menu all I want: the aspect ratio of all the files of that playlist won't change from what's in the gamesettings.ini .
4) The texture filter setting in gamesettings.ini is completely ignored and changing said option in the main menu changes the filter inside the game from that playlist.
5) If I were to remove the .m3u file and add the .cue files to the game's folder and set the texture filter in the properties of each CD inside DuckStation, DuckStation would respect that and changing the filter in the main menu wouldn't change it for those CDs.
6) If I then deleted the .cue files and inserted the .m3u file in the folder again, I would clearly still see the setting for "GPUTextureFilter" in gamesettings.ini, but DuckStation would be back at ignoring it.

> I don't like the idea of playlists, they seem redundant with a game list, so I'm not planning on changing this.

I couldn't care less about playlist files. In fact, I hate the idea of having to set things up for yet another file. 
What I do care about is, if possible, not having **ELEVEN CDs cluttering up DuckStation main window for just THREE games** (Final Fantasy 7, 8, 9), when I could have three images instead. 
If you gave us the possibility to create folders inside DuckStation or if you created a fake playlist that's really just for visuals because, when right-clicked or opened it actually works and gets displayed as several CDs, I wouldn't DREAM of having to create playlists in my life.

**Comment by stenzek** [comment] 2021-03-11 13:53
Honestly, if you insist on doing things the "non intended way" (using cues and the game list), you're on your own. The only potential issue here is the texture filter setting applying, which I'll check.

> If you gave us the possibility to create folders inside DuckStation or if you created a fake playlist that's really just for visuals because, when right-clicked or opened it actually works and gets displayed as several CDs, I wouldn't DREAM of having to create playlists in my life.

Not trying to be an ass, but you're welcome to implement this yourself and PR it. It's not really something I'm interested in, as the "unit" in the game list is the disc.

**Comment by tycooko** [comment] 2021-03-11 14:02
> Honestly, if you insist on doing things the "non intended way" (using cues and the game list), you're on your own. The only potential issue here is the texture filter setting applying, which I'll check.
> 
> > If you gave us the possibility to create folders inside DuckStation or if you created a fake playlist that's really just for visuals because, when right-clicked or opened it actually works and gets displayed as several CDs, I wouldn't DREAM of having to create playlists in my life.
> 
> Not trying to be an ass, but you're welcome to implement this yourself and PR it. It's not really something I'm interested in, as the "unit" in the game list is the disc.

Not trying to be an ass either, but if you want me to teach you one of the 7 languages I speak, give you knowledge about the world's cinema history, introduce you to the fields of photography and cinematography, especially on the post-production side (editing) or engage in any other of my fields of expertise, I would love to, for an honest price, of course.
On the other hand, as I thought I had already made abundantly clear, I couldn't be less useful in the field of software development as my skills don't go much further than basic HTML language.

What's non intended in using cues? What am I doing wrong?

**Comment by stenzek** [comment] 2021-03-11 15:52
The intended usage is cue sheets for each disc (so it scans them), and to switch via the game list.

The only reason playlists get listed is because they were needed for libretro, and since I dropped that, there's not much use for them. But removing features seems silly.

I only have a limited amount of spare time to work on this project, which I give away completely free and take no money for. Therefore I work on what I feel like working on, which means there's a limited scope and I can't satisfy all user requests. But it's open source, so anyone can add features if they like.

**Comment by stenzek** [comment] 2021-03-11 15:59
Game settings are applying fine here, including texture filtering.

It's probably the fact that you're bypassing the game list which is causing them to not be applied. Which is the same issue as #1784. (game settings are part of the game list entry)

**Comment by tycooko** [comment] 2021-03-11 16:28
> The intended usage is cue sheets for each disc (so it scans them), and to switch via the game list.
> 
> The only reason playlists get listed is because they were needed for libretro, and since I dropped that, there's not much use for them. But removing features seems silly.
> 
> I only have a limited amount of spare time to work on this project, which I give away completely free and take no money for. Therefore I work on what I feel like working on, which means there's a limited scope and I can't satisfy all user requests. But it's open source, so anyone can add features if they like.

Which is why I've never demanded anything on here and instead approached these channels you kindly gave us as an open and gentle discussion, and - just as an example - when, back in November, if I don't recall incorrectly, you told me that the MoltenVK issue was not a priority because it was Mac-related, I think my answer was "OK" and that ended that conversation for two months, until I decided to go talk to the team behind MoltenVK myself.

So, again: I know this is not your daily job, that you don't get paid, and that you're doing all of this out of passion and generosity, and I've repeatedly told you what a great project I think this is it and just how wonderful this app is, especially for Mac users. 

The problem is whenever I tell you - not to demand for it to be solved right away, mind you - that something's not working as intended, you react as if someone insulted your beautiful and only infant daughter. Which I understand, but still...it's hard to talk this way.

Anyways: thanks again for your time. Take care.

**Comment by stenzek** [comment] 2021-03-11 17:14
I'm not insulted.. :/ Fact is, while 95% of this project is me, I have to keep a realistic, achievable scope. You're welcome to make feature requests, but I'm not obliged to consider all of them, and some of them will be deemed out of scope. Others will be marked as feature requests and left open, with the possibility I'll get around to it some day. If you don't like that, there's plenty of alternatives around.

FWIW, the texture filter loading-from-ini was fixed in https://github.com/stenzek/duckstation/commit/eca0b510089cdb38ad1d1edca114dec4598b2674

**Comment by tycooko** [comment] 2021-03-11 18:05
> I'm not insulted.. :/ Fact is, while 95% of this project is me, I have to keep a realistic, achievable scope. You're welcome to make feature requests, but I'm not obliged to consider all of them, and some of them will be deemed out of scope. Others will be marked as feature requests and left open, with the possibility I'll get around to it some day. If you don't like that, there's plenty of alternatives around.
> 
> FWIW, the texture filter loading-from-ini was fixed in [eca0b51](https://github.com/stenzek/duckstation/commit/eca0b510089cdb38ad1d1edca114dec4598b2674)

I completely understand that.
I do editing work for other people's videos/movies for a living and, sometimes, I have to remind my customers that I'm a human being and that a day only has 24 hours, with a minimum of 6-7 of which I'd like to spend in my bed, sleeping. :P
Anyway, I'd love to help with the Italian, European Spanish and even (if anyone's interested) Catalan translation of DuckStation, but I'm afraid it would require more than looking at a list of words and sentences in English and writing a translation to their side with a program like Word.
If there's any guide that explains exactly what to do to translate softwares identical to DuckStation, I could give it a try.

**Comment by tycooko** [comment] 2021-03-11 21:54
> FWIW, the texture filter loading-from-ini was fixed in [eca0b51](https://github.com/stenzek/duckstation/commit/eca0b510089cdb38ad1d1edca114dec4598b2674)

The fix works perfectly. Thanks!

**Comment by tycooko** [comment] 2021-03-12 11:54
Although...watch out for the cheat manager: it works funny now. It seems that checking the boxes inside the main menu's tab doesn't really enable or disable the codes at the moment. I have to do it from the codes' list clicking on "Cheats".
It wasn't behaving like this until now, I'm afraid.

**Comment by tycooko** [comment] 2021-03-12 12:17
Although...watch out for the cheat manager: it works funny now.
1) enabling/disabling cheats from "Tools --> Cheat manager" doesn't trigger a text confirmation on screen (only enabling/disabling them from "Cheats --> Enabled Cheats" does), although the cheats are indeed enabled/disabled.
2) Enabling/disabling cheats from "Cheats --> Enabled Cheats" doesn't check/uncheck the corresponding checkboxes inside "Tools --> Cheat manager", although the cheats are indeed enabled/disabled.

I've already checked that this happens in both the Windows and macOS version with the latest update.
