### ISSUE TITLE
Main menu of Dragon Quest VII - Eden no Senshitachi (Japan) (Disc 1) (v1.0) is rendered incorrectly with OpenGL and D3D11

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#339] opened 2020-04-24 18:58 UTC
OpenGL and D3D11

![SLPM-86500_2020-04-25_04-53-41](https://user-images.githubusercontent.com/31968468/80247386-4c8f1400-86b1-11ea-8a53-30b1419a9286.png)

Software

![Capture](https://user-images.githubusercontent.com/31968468/80247409-56187c00-86b1-11ea-9a56-7fe8dc818a1c.PNG)

**Comment by stenzek** [comment] 2020-04-26 15:34
Do you have true colour turned on? Try with it off.

**Comment by Zet-sensei** [comment] 2020-04-26 15:51
Same problem with True Colour turned OFF.

**Comment by stenzek** [comment] 2020-04-28 07:58
The issues with the background look like an issue with true colour - but the menu is a valid issue.

**Comment by stenzek** [comment] 2020-04-28 08:06
Actually, turns out this is rather simple - it needs mask bit check emulation (same as https://github.com/stenzek/duckstation/issues/40).

Will be fixed once I merge it - it's almost done, I just have to get it working with OpenGL. It's blocked by some silly differences with vertex IDs compared to D3D/HLSL which I have to find a workaround for.

**Comment by stenzek** [comment] 2020-05-03 07:17
Please re-test on latest build.

**Comment by kurayami6** [comment] 2020-05-03 08:11
Text is fixed, background is still broken. 
![SLPM-86500_2020-05-03_18-09-24](https://user-images.githubusercontent.com/31968468/80909151-7e674100-8d69-11ea-9164-6ffcef1a221e.png)

**Comment by stenzek** [comment] 2020-05-03 08:12
Turn off true colour rendering.

**Comment by stenzek** [comment] 2020-05-03 08:14
This is likely the result of the way it's being drawn requiring dithering. There's a handful of games which need it, and with scaled dithering it doesn't look bad when upscaling. So, I'm considering making true-colour-disabled the default. Any thoughts?

**Comment by kurayami6** [comment] 2020-05-03 08:18
It is off. Want me to try anything else?

![Capture](https://user-images.githubusercontent.com/31968468/80909304-7c51b200-8d6a-11ea-9c73-941c5bfca5cf.PNG)

**Comment by stenzek** [comment] 2020-05-03 08:36
Ohh, looks like it's caused by upscaling.

It's rendering an.. interesting way. Will dig deeper, but depending on what it's doing it might not be fixable.

**Comment by kurayami6** [comment] 2020-05-03 08:48
It's fixed by turning off scaled dithering. Having it on was causing the same effect as having true colour rendering on. Does that mean this can be closed?

![Capture](https://user-images.githubusercontent.com/31968468/80909814-9a211600-8d6e-11ea-9e78-65e15f1e3096.PNG)

**Comment by stenzek** [comment] 2020-05-03 08:55
Yup, I also just found the same thing. From a quick look, it seems to render the colour gradient and then copy it back to the CPU, which forces it to be downscaled and then it eventually writes it back to the GPU. The problem is that an upscaled version with scaled dithering and without scaled dithering look quite different when downscaled.

Not sure there's a lot that could be done here. I'd be curious if any other emus handle this better.

Thanks for the investigation, I'll add it to the game's notes on the compatibility page.

**Closed** 2020-05-03 08:57 UTC
Labels: GPU Issue
