### ISSUE TITLE
I can't get shooting to work in Crypt Killer (USA)

### ISSUE THREAD

**Issue by Tiberius1437** [stenzek/duckstation#1398] opened 2021-01-06 06:20 UTC
The buttons for pause and special attack work fine but pressing the button to shoot does nothing. Here's my configuration. This should work fine, right? Sorry If I'm not understanding something. 

![crypt](https://user-images.githubusercontent.com/68873449/103736007-66a43300-5043-11eb-9951-45a058649298.PNG)

**Comment by stenzek** [comment] 2021-01-06 06:32
Based on nocash documentation, I think this game requires the justifier, not guncon (see https://github.com/stenzek/duckstation/issues/1131).

(

**Comment by Tiberius1437** [comment] 2021-01-06 06:45
I'll check. Strange that two out of three buttons would work though.

**Comment by stenzek** [comment] 2021-01-06 07:09
That's because the A/B buttons share the same index between Justifier/GunCon, but the trigger is a different index (bit 15 vs bit 13), and have a completely different method of determining the position (Justifier is less accurate).

Anyway, closing as it is a duplicate of #1131, and should work once Justifier is implemented. (I have it on a branch, it's just not accurate enough for some games)

**Closed by stenzek** 2021-01-06 07:09 UTC

**Comment by Tiberius1437** [comment] 2021-01-06 07:20
Thanks for the info.
