### ISSUE TITLE
Kellogg Original Waku Waku Doki Doki Ninki Game Chara Daishuugou! (Japan): Mr Driller startup issues

### ISSUE THREAD

**Issue by waspennator** [stenzek/duckstation#2012] opened 2021-04-22 01:18 UTC
**Game details**
SLPM-84002 Kellogg Original Waku Waku Doki Doki Ninki Game Chara Daishuugou! (Japan)
Redump Verified

**Description of the issue / bug**
I don't know if it's something going on with the game or the emulator, but for some reason, when I try to start the demo for Mr. Driller, once I click past the controller prompt, sometimes the game will start up normally, other times the game will just throw the controller prompt up an extra 1-2 times and restarting the audio before it actually starts the game up.

**Steps to reproduce**
Start it up, click on the first menu item on the list (Mr. Driller), Start the demo and then click past the display for the controls, sometimes it should load without issue and other times it should toss up the same control display a few times, if you click past enough times eventually it should start up.

**Hardware/software**
i5 6600k
Geforce GTX 1070
Windows 10
Vulkan 

**Emulator version**
0.1-3850 Preview Build

**Additional Context**

https://user-images.githubusercontent.com/78768499/115641028-7f281880-a2d5-11eb-8859-644a70bd2695.mp4

**Comment by stenzek** [comment] 2021-04-22 02:30
Strange. Doesn't sound like it's crashing, it'd usually restart with the shell or hang completely.

**Comment by waspennator** [comment] 2021-04-22 02:58
Weird thing about it is that sometimes it happens once or twice, sometimes I can get into the demo without any issues at all. I'm still able to play the game cause it only does it a few times before working, it just seems to be random when it does and doesn't happen.

**Comment by waspennator** [comment] 2021-04-22 05:05
Decided to test it out with actual hardware and it doesn't seem to happen there, so I decided to test some other emulators to see how they handled it.
Ares: Tried 3 times and it booted without looping
Beetle: Tried 3 times and it booted without looping
Mednafen: Tried once and it looped twice before booting

**Comment by stenzek** [comment] 2021-04-22 06:50
Odd thing to try, but see if experimenting with memory card or controller types makes any difference (e.g. using two memory cards, no memory cards, digital controller, etc)

**Comment by waspennator** [comment] 2021-04-22 07:21
I'm trying to test this out with the different types, but this seems to be weirdly on and off when it happens, it went multiple times without doing it with no memory cards plugged in so I thought that was causing it, but another test later it happened again.

I also checked the logs again while testing and noticed that if it successfully transitions over to the game introduction, it spits out LBA 22774 and 22918 immediately after the two unknown SPU write and the one time I was able to look at the log when it happened, it didn't spew out anything at all right away and then it suddenly looped.

**Comment by stenzek** [comment] 2021-04-26 16:29
Probably CD-ROM related - it spams reset commands. I'm planning some refactors to the CD-ROM implementation soon which will make this more faithful to the hardware.

**Comment by stenzek** [comment] 2021-06-12 08:25
Hopefully this should be fixed by https://github.com/stenzek/duckstation/commit/36bfc461f9c7ecbbe2d6ffb4817e98e28a2de64e.

**Closed by stenzek** 2021-06-12 08:25 UTC
Labels: CD-ROM

**Comment by waspennator** [comment] 2021-06-13 00:40
Tested again and can confirm the issue has not been fixed yet, here's a pic of the log from when I pressed start for the game again.
![Duckstation log7](https://user-images.githubusercontent.com/78768499/121792051-b3b9a180-cbad-11eb-913c-646db0e03201.png)

**Comment by stenzek** [comment] 2021-06-13 01:25
Seems fine as far as I can tell. Are you sure it's not just a quirk and working as intended?

**Comment by waspennator** [comment] 2021-06-13 01:41
I'm still unsure how to get it to consistently happen every time, but I do know that when I tested it after updating, it happened twice in a row the first time, haven't been able to get it to happen again after that.

**Comment by stenzek** [comment] 2021-06-13 01:56
If it was actually a disc emulation issue, it'd be unlikely that it would "reload" the same screen, instead it'd usually just hang/crash.
