### ISSUE TITLE
Minor defects when building with Wayland

### ISSUE THREAD

**Issue by DarkSwan86** [stenzek/duckstation#1161] opened 2020-12-06 18:22 UTC
Hi @stenzek , here is a list of very minor defects that DS has when building with Wayland. They are very minor so...treat them as very low priority :smile: 

![minor annoiance](https://user-images.githubusercontent.com/24975273/101288573-97e8d380-37f7-11eb-91bf-6e6b9c5e0b93.png)

~~1)Can you make building with Wayland as a default as discussed in https://github.com/stenzek/duckstation/issues/979#issuecomment-709879741 ?~~

2)Can you make the columns "Type,code, size, Title,ecc..." movable so we can rearrange them?

~~3)As you can see, the Wayland build uses the default wayland icon (the yellow W) instead of duckstation icon on both main window and the tray. Can it be fixed?~~

4)On the column "Type" the disk icon is all on the left side, leaving a lot of space on the right. Can it be placed in the center for visual consistency?

Please don't hate me! :smile:

**Comment by DarkSwan86** [comment] 2021-05-10 11:58
Small update on this, as https://github.com/stenzek/duckstation/commit/b51a4856d7615e8df42bce09d1362d03c95c275a :

1)Now it's built with wayland as default and works correctly.
2)No change here.
3)Now the icon works perfectly.
4)Still all aligned to left.

2 and 4 are still very low priority :) so no hurry here!

**Comment by stenzek** [comment] 2021-05-27 07:31
The columns is a duplicate of #1408.

**Closed by stenzek** 2021-05-27 07:31 UTC
Labels: Feature Request
