### ISSUE TITLE
Store settings in subdirectories of Duckstation

### ISSUE THREAD

**Issue by davidmarshall15** [stenzek/duckstation#1123] opened 2020-12-01 11:09 UTC
This is related to Windows but might be relevant to other operating systems.

When wanting to run Duckstation on multiple devices, possibly using a USB drive or something like nextcloud for automated distribution, save states and settings are not included.

An option to store all settings under the root Duckstation directory
Also if files such as bios's are at the same level as Duckstation, the ability to reference using ../bios rather than the full path.

Thank you for the emulator, finding it to work very well.

**Comment by stenzek** [comment] 2020-12-01 11:12
Have you read https://github.com/stenzek/duckstation#user-directories (portable mode)?

You can use relative settings in the config, it's relative to settings.ini

**Comment by davidmarshall15** [comment] 2020-12-01 11:36
I did read that, my settings.ini is using a windows env directory and not the duckstation root.
As I was using a different emulator previously, the bios file were on a different drive and I did not want to move them to the windows system drive.

**Comment by davidmarshall15** [comment] 2020-12-01 11:39
I moved the settings.ini to the root Duckstation directory and this has resulted in the creation of a number of directories, including bios.

So this is resolved for me but someone might want to check the logic of creating the settings.ini.
I used the zip download but did run duckstation-sdl-x64-ReleaseLTCG.exe first, maybe this was a mistake on my part.

**Comment by stenzek** [comment] 2020-12-01 11:48
Yes, that's working as intended. To activate portable mode, it checks for the presence of either portable.txt or settings.ini.

It creates the bios directory (and others) because that's what would normally be created in the documents directory. You don't have to put the bios there, you can change the path in settings (and a relative path will work fine there)

**Comment by stenzek** [comment] 2020-12-01 15:46
Closing as unless I'm misunderstanding, portable mode provides what you're after.

**Closed by stenzek** 2020-12-01 15:46 UTC
