### ISSUE TITLE
Gamelist With Artbox

### ISSUE THREAD

**Issue by mohsinous** [stenzek/duckstation#302] opened 2020-04-16 19:36 UTC
it would be realy nice to have art box in game list

**Comment by kurayami6** [comment] 2020-04-16 19:55
I don't think an emulator is allowed to ship with copyrighted boxes and artwork.

**Comment by stenzek** [comment] 2020-04-17 16:23
We can potentially pull them from a source somewhere. But regardless, duplicate of #109.

**Closed by stenzek** 2020-04-17 16:23 UTC
