### ISSUE TITLE
Crash Team Racing SCES_021.05 Not Boot

### ISSUE THREAD

**Issue by diegoginard** [stenzek/duckstation#932] opened 2020-10-05 20:23 UTC
<entry code="SCES-02105" title="Crash Team Racing-PSX-PAL" region="PAL" compatibility="1">
    <compatibility>Doesn't Boot</compatibility>
    <version-tested>0.1-1932-g395f5e2c</version-tested>
    <comments>freezes on the first screen after bios boot</comments>
</entry>

**Comment by stenzek** [comment] 2020-10-06 00:48
Duplicate of #933.

**Closed by stenzek** 2020-10-06 00:48 UTC
