### ISSUE TITLE
Mutiple issues in Castrol Honda Superbike Racing (USA)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#181] opened 2020-03-27 04:00 UTC
Firstly the opening logos only appear for a fraction of a second and then there's just several seconds of black screen before the game starts. 

![SLUS-00882_2020-03-27_14-53-20](https://user-images.githubusercontent.com/31968468/77720189-43237500-703b-11ea-8dff-6435b88a4d8f.png)

They play at normal speed in Beetle PSX.

![Castrol Honda Superbike Racing (USA)-200327-144935](https://user-images.githubusercontent.com/31968468/77720211-5a626280-703b-11ea-896f-ec76630ecc94.png)

![Castrol Honda Superbike Racing (USA)-200327-144941](https://user-images.githubusercontent.com/31968468/77720214-5d5d5300-703b-11ea-9498-1d2e411f2da2.png)

Secondly the loading screen breaks if you select Padang Raceway. The picture of the rider flashes in and out of existence.

![SLUS-00882_2020-03-27_14-53-58](https://user-images.githubusercontent.com/31968468/77720308-a90ffc80-703b-11ea-80e1-2600f66a1aa8.png)

![SLUS-00882_2020-03-26_13-59-57](https://user-images.githubusercontent.com/31968468/77720290-9f869480-703b-11ea-9dfb-4df726b26da5.png)

**Comment by and468860** [comment] 2020-03-27 09:22
have to use emulation speed maximum emulator cpu start,  Oh! emulator needs faster emulator engine .
the game gran turismo 2 psx is too slow to read memory card not carega game races 
 correction graph

**Comment by stenzek** [comment] 2020-03-29 07:51
Wasn't able to reproduce the second issue with the loading screen - this might be that DX11 bug again. Nor the logos cancelling early, but I can confirm the title screen missing.

**Comment by kurayami6** [comment] 2020-06-03 13:34
Both issues still happen as of the latest version.

**Comment by Shideravan** [comment] 2020-12-08 18:59
I can confirm both issues happening in 0.1-2499-g770dd5a6.

**Comment by Kurayami7** [comment] 2021-03-08 14:05
Logos still go by too fast even with the latest changes and icache and recompiler on in per game settings.

**Comment by Shideravan** [comment] 2021-09-15 23:24
> Secondly the loading screen breaks if you select Padang Raceway. The picture of the rider flashes in and out of existence.
> 
> ![SLUS-00882_2020-03-27_14-53-58](https://user-images.githubusercontent.com/31968468/77720308-a90ffc80-703b-11ea-80e1-2600f66a1aa8.png)
> 
> ![SLUS-00882_2020-03-26_13-59-57](https://user-images.githubusercontent.com/31968468/77720290-9f869480-703b-11ea-9dfb-4df726b26da5.png)

This part seems to been fixed as of 0.1-4736-gbacd8348.
The issue with logo still happening tho

**Comment by stenzek** [comment] 2024-05-01 15:19
Fixed in https://github.com/stenzek/duckstation/commit/1185f8f6aa99e8e48e31fa78dbf28815b3260039. Requires software renderer, no point forcing it just for a title screen.

**Closed by stenzek** 2024-05-01 15:19 UTC
