### ISSUE TITLE
Increase PSX Memory

### ISSUE THREAD

**Issue by barisyild** [stenzek/duckstation#991] opened 2020-10-20 17:46 UTC
Increase PSX Memory feature can help remove some limitations with a patch in heap memory supported games.

Additional memory must be located in dma.

Development Consoles has 8mb dma but retail consoles has 2mb dma

There are even people who have modified their console on the internet to use 8mb dma. (useless for homebrew development or heap memory increased games)

Resources:

SCPH-5502 8MB Modification: http://www.psxdev.net/forum/viewtopic.php?t=660
https://retrocomputing.stackexchange.com/questions/13551/how-much-memory-did-the-playstation-development-kit-have

Note:

Preferably, it would be nice if the amount of RAM could be adjusted.

**Comment by stenzek** [comment] 2020-10-21 12:40
Not super forward, since some games depend on the RAM mirrors behaving as mirrors.

I'd probably just implement the memory control register documented here: https://problemkaputt.de/psx-spx.htm#memorycontrol

**Comment by barisyild** [comment] 2020-10-21 23:55
> Not super straightforward, since some games depend on the RAM mirrors behaving as mirrors.
> 
> I'd probably just implement the memory control register documented here: https://problemkaputt.de/psx-spx.htm#memorycontrol

We patched PCSX-R emulator and added 8MB DMA support.
[pcsxr-master-8mb-source (1).zip](https://github.com/stenzek/duckstation/files/5419226/pcsxr-master-8mb-source.1.zip)

Alse we patched CTR's heap memory and added 8MB DMA Support!
![image](https://user-images.githubusercontent.com/25794892/96801980-8dbe7180-1411-11eb-8f4d-51bdf841448d.png)

We checked the RAM with the application.:
[RAMTEST.zip](https://github.com/stenzek/duckstation/files/5419232/RAMTEST.zip)


CTR with 8MB DMA:
https://www.youtube.com/watch?v=KO3ayiXBB5w

**Comment by stenzek** [comment] 2021-04-06 08:32
Duplicate of https://github.com/stenzek/duckstation/issues/16

**Closed by stenzek** 2021-04-06 08:32 UTC
Labels: Feature Request
