### ISSUE TITLE
folder name column (sorting, favorite, filter, category)

### ISSUE THREAD

**Issue by PAL123** [stenzek/duckstation#1832] opened 2021-03-17 18:40 UTC
it would be great if duckstation had a column showing the folder names. this could be used, for example, to create categories such as racing, strategy games, etc.

![2021 03 17-19 38 54](https://user-images.githubusercontent.com/40403757/111520680-a0d33480-8758-11eb-8e50-ecb255a7f74e.png)

**Comment by stenzek** [comment] 2021-05-12 12:24
The new game database has genre listed, otherwise this is custom metadata and a duplicate of https://github.com/stenzek/duckstation/issues/1077

**Closed by stenzek** 2021-05-12 12:24 UTC
Labels: Feature Request
