### ISSUE TITLE
Support for 7z files

### ISSUE THREAD

**Issue by hardlevel** [stenzek/duckstation#2499] opened 2021-08-10 23:31 UTC
**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Is your feature request related to a problem? Please describe.**
Sometimes I use retroach and the support for 7z files is very useful, it helps to spare some space on hdd, this support also work with duckstation core

**Describe the solution you'd like**
add support for 7z files, like retroarch do

**Describe alternatives you've considered**
a support for zip files?

**Additional context**
I don't think I can share a screenshot...

**Comment by BailShamber** [comment] 2021-08-10 23:58
A good alternative is chd images which is already supported by duckstation, it compresses the data track with lzma (just like 7z), and audio tracks with flac, giving smaller sizes than 7z

**Comment by stenzek** [comment] 2021-08-11 01:36
No. Duplicate of #620. Quoting myself:

> The main issue is archive formats are not "seekable". In other words, you can't say "I want to read offset 2352 from file xyz" without decompressing the whole thing first.
> 
> Creating an "index" may be possible, then you can seek to the closest "block" and decompress from there. The other alternative is just to decompress into memory first, which I'll probably add when I add the option to preload disc images to RAM.
> 
> zip should be doable as I already ship zlib. RAR most likely no, because of license concerns. 7z, perhaps, depending on whether I pull in the libraries for the auto-updater when I write that.
> 
> My best advice would be to just use chd. It's compatible with most of the big-name emulators now, and compresses better than archive formats anyway.


> I still don't like this idea.
> 
> What happens if there's multiple files in the zip? Which one to load?
> 
> These would have to be cached on disk somewhere - where do we cache it? How many games do we save?
> 
> Honestly this just seems like a way for pirates to be lazy with their downloaded games, which is not the point of the emulator. Compressed disc formats work much better.

**Comment by stenzek** [comment] 2021-08-11 01:38
Also see https://github.com/stenzek/duckstation/issues/2472 -clearly it doesn't work very well in RA and has the issues I pointed out (not knowing which file to load)

**Closed by stenzek** 2021-08-11 01:38 UTC

**Comment by bslenul** [comment] 2021-08-11 10:50
If you use the "Load Archive" option in RetroArch it will extract the 1st file only, so it usually works fine with single track games.
But as soon as you start messing with multi-tracks games that means it will only extract the first track .bin file:

* It might work but you won't have any music in-game, yay...
* It might freeze when trying to access another track.
* It might not load at all if the core doesn't support loading games from .bin (Beetle PSX cores).

Even if you merged the .bin files into a single one, the file will be separated from the .cue so you'll get the same results.

If you use the "Browse Archive" option then select the .cue to load the game, the .cue file only will be extracted, and a .cue file alone is useless so the game won't boot at all.

And of course you have to wait until extraction is complete, so it may add a huge delay on launch. So... yeah... even if RA supports it, it's faaaaaaar from being flawless and it's never recommended. If you need the space save convert your games in .chd instead as recommended above.
