### ISSUE TITLE
Official PS1 CD Disc Support(like Playing An Actual PS1 Game From The Disc Drive On The Emulator)

### ISSUE THREAD

**Issue by WaveRunner7** [stenzek/duckstation#1844] opened 2021-03-19 19:53 UTC
It's Not Something I Really Want But it would be nice to have something like this in the emulator because before i found out
about this emulator i was using EPSXE which is an ok emulator but besides that the main reason i would use that emulator
was because you could actually play the original disc on pc which was really cool and it's the only reason i'll sometimes use it
from time to time, but if you guys put that feature in Duckstation I won't Have A reason to use EPSXE anymore.. like i said i don't
really want this feature but it would be nice thanks an advance.

**Comment by stenzek** [comment] 2021-03-20 01:16
Duplicate of https://github.com/stenzek/duckstation/issues/1271

**Closed by stenzek** 2021-03-20 01:16 UTC
