### ISSUE TITLE
[Feature Request] Mapping multiple buttons presses to a single input

### ISSUE THREAD

**Issue by noctilo** [stenzek/duckstation#2092] opened 2021-05-10 19:13 UTC
This would be very handy for games like Parasite Eve, in the game you control the character and the menu with the analog left stick, which is a pain, but if we had the ability to mapping multiple buttons presses to a single input (in this case the Analog left stick) we could then control the character with the Analog left stick and the menus with the D-pad. The PPSSPP emulator has the multiple buttons to a single input feature and works excellent. Please, consider my request. Apologies for my poor english. Thank you for your time.

**Comment by andercard0** [comment] 2021-05-10 19:15
> This would be very handy for games like Parasite Eve, in the game you control the character and the menu with the analog left stick, which is a pain, but if we had the ability to mapping multiple buttons presses to a single input (in this case the Analog left stick) we could then control the character with the Analog left stick and the menus with the D-pad. The PPSSPP emulator has the multiple buttons to a single input feature and works excellent. Please, consider my request. Apologies for my poor english. Thank you for your time.

would you please fill out the template  ? or your issue will closed as invalid. ty

**YOU MUST FILL OUT THIS ISSUE TEMPLATE. IT IS NOT OPTIONAL.** Issues which are not created with the template **will be ignored and closed**.

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by noctilo** [comment] 2021-05-10 20:32
how do i do that? is template the same as label? it doesnt give me any options.

**Comment by noctilo** [comment] 2021-05-10 21:12
How do i fill out the template? is template the same as Label? it doesnt give me any options, only to edit the title of my message or the message itself, nothing else. any help would be appreciated.

**Closed** 2021-05-11 01:34 UTC

**Comment by noctilo** [comment] 2021-05-11 04:21
> This is already a thing. Hold shift while clicking the binding. Please read the help text next time.


hi, apologies for any inconvenience. im using the emulator on android tv, with a ps5 controller. i connected a keyboard to use the "shift" button while i enter what would be the second button for an input, but it doesnt work. is there any other way to do it? maybe typing something in the PS5CONTROLLER.ini ?

**Comment by stenzek** [comment] 2021-05-11 04:37
No, you can't do this in Android.
