### ISSUE TITLE
Elder Gate (Japan) - artifacts in map screen

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#1135] opened 2020-12-03 19:29 UTC
**Game details**
SLPM-86494 - Elder Gate (Japan)

**Description of the issue / bug**
Artifacts in map screen, see below.

**Steps to Reproduce**
Go to the first map. This is the expected result: https://www.youtube.com/watch?v=HWeKF8hr2oc&ab_channel=%E3%83%95%E3%82%A1%E3%83%9F%E3%81%A3%E5%AD%90%E3%83%97%E3%83%AC%E3%82%A4%E5%8B%95%E7%94%BBretrogamer
This is what you get:
![image](https://user-images.githubusercontent.com/12163923/101078268-b3987380-3584-11eb-9f39-6d0d1cb0da61.png)

**Enhancements information**
No enhancement used

**Hardware/software**
Intel 4790, Geforce 1070, Windows 10 x64

**Emulator version**
0.1-2433-g9089c973

**Comment by stenzek** [comment] 2020-12-04 01:42
This game is very sensitive to DMA timing from what I remember. Duplicate of https://github.com/stenzek/duckstation/issues/256

**Closed by stenzek** 2020-12-04 01:42 UTC
