### ISSUE TITLE
Dino Crisis 2 bug on backgroungs with Bilinear Texture Filtering Enabled

### ISSUE THREAD

**Issue by Basmurd** [stenzek/duckstation#201] opened 2020-03-31 14:05 UTC
Bilinear Texture Filtering Enabled with Upscale
![79cIpe3Pdv](https://user-images.githubusercontent.com/61318181/78035009-3079aa80-7371-11ea-8217-276b713327aa.png)
![cUD62ZLjhI](https://user-images.githubusercontent.com/61318181/78035024-34a5c800-7371-11ea-9c91-9523e267c313.png)
![FZCV69xY6e](https://user-images.githubusercontent.com/61318181/78035031-366f8b80-7371-11ea-92fb-59b4c78997b2.png)
Bilinear Texture Filtering Enabled without Upscale
![OSLOBNAGsP](https://user-images.githubusercontent.com/61318181/78035235-7df61780-7371-11ea-86b8-b628f6ff3dfd.png)
![RmvHgCHHMF](https://user-images.githubusercontent.com/61318181/78035278-8d756080-7371-11ea-86f5-451d7e1b0bc5.png)
![laAch5SD6R](https://user-images.githubusercontent.com/61318181/78035286-91a17e00-7371-11ea-8370-71ea1a2b9cfa.png)
Bilinear Texture Filtering Disabled with Upscale
![LyPi2Oeaxj](https://user-images.githubusercontent.com/61318181/78035390-b695f100-7371-11ea-8dc5-3a96b370705d.png)
![pU24UtKCB2](https://user-images.githubusercontent.com/61318181/78035437-c9102a80-7371-11ea-8010-e564b3c3878e.png)
![FZCV69xY6e](https://user-images.githubusercontent.com/61318181/78035461-cf060b80-7371-11ea-86ea-edf2b90c4b3e.png)

**Comment by forz0i** [comment] 2020-03-31 14:43
[image: bandicam 2020-03-31 15-10-15-278.jpg]
Snobow Kids Plus CRASH

**Comment by stenzek** [comment] 2020-03-31 15:56
Yeah, the current texture filtering really struggles around transparent edges. I've got a slightly improved version done, but it's still not ideal yet.

**Comment by Basmurd** [comment] 2020-03-31 17:25
Waiting for test ;)

**Comment by stenzek** [comment] 2020-07-01 15:03
Duplicate of https://github.com/stenzek/duckstation/issues/35

**Closed by stenzek** 2020-07-01 15:03 UTC
