### ISSUE TITLE
Alien Resurrection door bug

### ISSUE THREAD

**Issue by Nightwalkerrrr** [stenzek/duckstation#1409] opened 2021-01-07 15:50 UTC
**Game details**
[Serial Code, Region]
SLUS-00633, Alien Resurrection (USA)

**Description of the issue / bug**
The door is bugged and won't open. Disabling all enhancements doesn't help
https://youtu.be/6Mx0CEYx_cU

In epsexe this bug can be fixed by switching audio plugin to eternal spu plugin lite 1.41:
https://youtu.be/0hX_bE_Hg30
Switching audio backends in duckstation doesn't help

You can reproduce this bug using my save file:
https://drive.google.com/file/d/1abARkfWeM-6kRCsxS66CDgcCWdGvkDLj/view?usp=sharing

**Hardware/software**
Ryzen r5 2600, rx5700, win10 x64 2004
[GPU Renderer - Any]

**Emulator version**
0.1-2854-g24c37324 (dev)

**Comment by stenzek** [comment] 2021-01-07 16:23
Interesting, might be SPU IRQ related then. Will look into this when I get a chance.

**Comment by stenzek** [comment] 2021-01-09 09:02
Needs SPU IRQs triggered on transfer. Have a fix pending, just need to fix the regressions.

**Comment by stenzek** [comment] 2021-01-09 17:16
Should be fixed with https://github.com/stenzek/duckstation/commit/15652b4c1f5511d231b10bbc20d0f69aa4f912bf (only in preview build for now)

**Comment by stenzek** [comment] 2021-01-20 04:11
Closing since as far as I'm aware, this has been fixed. If the issue is still occurring, please let me know and I'll investigate.

**Closed by stenzek** 2021-01-20 04:11 UTC
Labels: SPU
