### ISSUE TITLE
Include input binding profiles in User Settings 

### ISSUE THREAD

**Issue by Richard-L** [stenzek/duckstation#901] opened 2020-09-26 16:56 UTC
![image](https://user-images.githubusercontent.com/4934209/94345861-32bf7780-0029-11eb-9a05-48527bfcb3a2.png)

^while this wants to discern controller types, it would be terrific if user settings would allow saved input profiles here, so that bindings may change automatically upon game launch.

![image](https://user-images.githubusercontent.com/4934209/94346029-30a9e880-002a-11eb-9e43-b9a52cd66769.png)

**Related thought**: it would be nice if the controller settings could indicate if a mapping profile is currently "true". Perhaps after "Button Bindings: _profile name_", where the profile name just disappears if it's invalidated. This would help a lot once you juggle several profiles.

**Comment by stenzek** [comment] 2020-10-03 14:19
Duplicate of https://github.com/stenzek/duckstation/issues/877

**Closed by stenzek** 2020-10-03 14:19 UTC
