### ISSUE TITLE
No vibrations

### ISSUE THREAD

**Issue by backgamon** [stenzek/duckstation#1363] opened 2021-01-01 20:47 UTC
Hi,

I'm back after last solved problem https://github.com/stenzek/duckstation/issues/847
All buttons and axis work well...But i don't have any vibrations.
My 39960 Hama converter for Dualshock 2 support this...But doesn't have any.
I checked with SDL and Direct Input...
https://www.hama.com/00039960/hama-single-controller-adapter-for-playstation-2-to-usb#technical-details

**Comment by stenzek** [comment] 2021-01-02 08:12
DInput doesn't have vibration support yet.

Does the vibration work in other applications with this controller?

**Comment by Unicorngoulash** [comment] 2021-01-02 08:14
Are you making sure to run analog mode?

![image](https://user-images.githubusercontent.com/73665433/103453487-db413f80-4cda-11eb-8f6e-35d1835b9765.png)

**Comment by stenzek** [comment] 2021-01-02 08:34
Rumble should also be set to the controller (push any button to tell it the controller to use)

**Comment by backgamon** [comment] 2021-01-02 08:50
Sorry for time to answer.
Rumble work with ePSXe (burutter) and pcsx2 with lilypad.
I allready push the button on vibration tab.

**Comment by Nucleoprotein** [comment] 2021-01-02 08:54
ie. two emulators that are using DirectInput. Sten said: "DInput doesn't have vibration support yet." so i think you need to wait.

**Comment by backgamon** [comment] 2021-01-02 08:59
It seem my Hame doesn't like SDL yea...
Yuzu have same rumble issue...
Then i wait  :/

**Comment by Alien-Grey** [comment] 2021-01-02 09:15
Vibration only works with X-Input. I'm not sure if even that is working as it should. I notice the difference in vibration between DuckStation or other PSX emulators (ePSXe/Mednafen). This can easily be reproduced by running a WipEout game and trying to use boost start when a race begins.

Not sure if a button assignment for vibration or analog is necessary. This seems to just work with games that support it.

I can get a PS2 Dual Shock controller to work with SDL Input. Also tried a namco neGcon contoller. The buttons can be assigned for the namco negCon controller but the I button doesn't work if I run a game (possible also other buttons but can't start the game).

D-Input does nothing. Not possible to assign any button on my PS2 Dual  Shock controller (Windows 7 X64) or GPD Win (Windows 10 X64) that also has support for D-Input.

**Comment by stenzek** [comment] 2021-01-02 09:29
> I notice the difference in vibration between DuckStation or other PSX emulators (ePSXe/Mednafen). This can easily be reproduced by running a WipEout game and trying to use boost start when a race begins.

Please do not use epsxe as a ground truth. It's been shown time and time again to be incorrect - compare with console. DuckStation actually has the most accurate vibration emulation thanks to ggrtk's work.

> Not sure if a button assignment for vibration or analog is necessary. This seems to just work with games that support it.

The button is only to tell the emulator which controller to send the rumble too. It says that in the help text below. That's why it says "Controller0" and not "Controller0/ButtonN"

> Vibration only works with X-Input

Since I reverted the SDL version, I have working vibration in SDL mode with both an xbox one controller, as well as a dualshock 4 (doesn't even need DS4Windows).

> D-Input does nothing. Not possible to assign any button on my PS2 Dual Shock controller (Windows 7 X64) or GPD Win (Windows 10 X64) that also has support for D-Input.

Can't really do much about this, since it works fine with the only controllers I have. Maybe try an xinput wrapper.

**Comment by Nucleoprotein** [comment] 2021-01-02 09:30
You can try generic workaround - use Steam.
Enable in Steam Controller support fory you controller ie. for my DualShock 4 i have used PS4 controller support for you i think will be generic controller support, add Duckstation to Steam and start it trough it, then make sure it's using Xinput.

**Comment by Alien-Grey** [comment] 2021-01-02 10:19
D-Input can probably be removed because SDL Input does seem to work fine with D-Input controllers.

I mentioned ePSXe because it works really good with PCSX2 Lilypad and Mednafen PSX emulation for vibration. Vibration works exactly the same as a real PS1 hardware. Try WipEout 3 Specilal edition with DuckStation and X-Input vibration. Try to boost start the race. If you get the power level on the right spot for boost start the controller should start to vibrate. With DuckStation it doesn't but does start to vibrate as soon as the race begins.

I don't use Steam but X-Input works just fine with DuckStation. Response time seems better than any other PSX emulator and DuckStation is the only PSX emulator that runs just fine on low spec devices like my GPD Win. Never thought this would've been possible so I'm impressed. I don't need to disable any Intel GFX power saving option and I also disabled CPU bust speed. Pretty amazing.

**Comment by Alien-Grey** [comment] 2021-01-02 14:10
After the last update (DuckStation 0.1-2799-g0d281538) vibration now also longer works for me with X-Input.

**Comment by stenzek** [comment] 2021-01-02 15:29
> D-Input can probably be removed because SDL Input does seem to work fine with D-Input controllers.

I added dinput because apparently SDL 2.0.14 broke some controllers... not that it matters now since I reverted it.

> I mentioned ePSXe because it works really good with PCSX2 Lilypad and Mednafen PSX emulation for vibration. Vibration works exactly the same as a real PS1 hardware.

Last I checked, mednafen didn't even emulate vibration intensities. It was just on or off. Hardly "working the same".

> With DuckStation it doesn't but does start to vibrate as soon as the race begins.

Because duckstation does emulate the vibration intensity, depending on your controller, you might have to bias the value for it to be noticable.

> After the last update (DuckStation 0.1-2799-g0d281538) vibration now also longer works for me with X-Input.

It was working with an xbox one controller when I tested a couple of days ago. I can check again tomorrow, but nothing has changed...

**Comment by backgamon** [comment] 2021-01-02 16:27
Well i checked a couple of games and with Dinput i have another issue, i can't use the dpad with up+right and down+left, it doesn't work.
left+up and right+down work.
With SDL no issue at all.

**Comment by stenzek** [comment] 2021-01-02 16:28
Then use SDL? :) DInput is only there if you are having problems with SDL.

**Comment by CookiePLMonster** [comment] 2021-01-04 10:32
FWIW if SDL doesn't support your controller, you can add your own mappings via SDL's standard gamecontrollerdb.txt, like this one:
https://github.com/gabomdq/SDL_GameControllerDB/

**Comment by stenzek** [comment] 2021-03-08 09:50
Closing as I'm not planning on implementing rumble in dinput, and it should work via SDL anyway. If it doesn't, it may be an SDL issue.

**Closed by stenzek** 2021-03-08 09:50 UTC
