### ISSUE TITLE
[SLUS-01041] Chrono Cross (USA) (Disc 1) - The game crashes if you try to check status of a character.

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#702] opened 2020-08-03 21:58 UTC
**Version**
0.1-1409-ge198e315

**Issue**
Game freezes in black screen and music freezes too (internal crash) if you try to check status of a character ingame.
The issue happens in both interpreter and recompiler with both software or hardware renderers.

**Comment by stenzek** [comment] 2020-08-04 04:28
Duplicate of https://github.com/stenzek/duckstation/issues/553

**Closed by stenzek** 2020-08-04 04:28 UTC

**Comment by Shideravan** [comment] 2020-08-04 04:34
I don't think it's a duplicate, as Issue #553 says about graphical menu issues, this is about a crash ingame, a different issue AFAIK
