### ISSUE TITLE
Cheats Support

### ISSUE THREAD

**Issue by mrdeathjr28** [stenzek/duckstation#446] opened 2020-05-15 17:47 UTC
cheats support case epsxe

![epsxe](https://user-images.githubusercontent.com/6601480/82080440-29e98d00-96aa-11ea-91ab-c3db7778eefe.jpg)

**Comment by stenzek** [comment] 2020-05-17 09:42
Duplicate of #65.

**Closed by stenzek** 2020-05-17 09:42 UTC
Labels: enhancement
