### ISSUE TITLE
Crashes when trying to change Resolution Scale in Enhancement

### ISSUE THREAD

**Issue by TerraDev64** [stenzek/duckstation#1422] opened 2021-01-09 00:36 UTC
**Description of the issue / bug**
When changing the Resolution scale in the Enhancement settings of the GPU settings the program crashes.

I changed the renderer to vulkan

**Steps to reproduce**
Change the Renderer to Vulkan and then try to change the Resolution Scale while clicking on the arrow button
to open the resolution options

**Hardware/software**
AMD Ryzen 5 2600, AMD Radeon RX Vega 56, Windows 10
Vulkan

**Emulator version**
0.1-2862-g6fbffb6f (dev)

**Comment by stenzek** [comment] 2021-01-11 03:11
Can't reproduce any crash nor validation layer warnings when changing resolution here with a RX580 or GTX1080.

**Comment by kgbandido** [comment] 2021-01-12 14:55
Ive found it only happens in the sdl application

**Comment by TerraDev64** [comment] 2021-01-12 15:58
@kgbandido is right, it only happens in the sdl application

**Comment by stenzek** [comment] 2021-02-06 17:18
Closing as SDL is no longer available, but could be worth verifying on NoGUI as it shares a bunch of code.

**Closed by stenzek** 2021-02-06 17:18 UTC
