### ISSUE TITLE
Linux GUI Supersized

### ISSUE THREAD

**Issue by Carl393** [stenzek/duckstation#1963] opened 2021-04-13 04:25 UTC
For some reason I cannot figure out why my Duckstation GUI is so large..
See image attached

(Running Debian Bullseye 11)

Any thoughts?
As of right now it's not useable... (I cannot see where to navigate to or anything for that matter)
![example](https://user-images.githubusercontent.com/14049856/114496802-b9672b00-9bee-11eb-86ff-d6681010c079.png)

**Comment by stenzek** [comment] 2021-04-13 05:37
Are you using the appimage or building from source? I've seen this from outdated qt versions.

I'm going to be moving to qt6 soon anyway, which should solve all these version problems (since you'll have to use my build rather than some outdated distro version)

**Comment by Carl393** [comment] 2021-04-13 05:39
Yes I'm using your build :-)
You've got me, I'm no expert like you.

I'll test my audio 'glitch' via RCA output and report back to you (to see
if it makes a difference!)
Carl

**Comment by stenzek** [comment] 2021-05-27 07:27
Closing, since I couldn't reproduce this issue on the supported Linux environment (Ubuntu). Otherwise, qt6 might fix it when I move linux over (windows is already using it).

**Closed by stenzek** 2021-05-27 07:27 UTC
