### ISSUE TITLE
dino crisis graphics completely destroyed after the last update

### ISSUE THREAD

**Issue by ajkmetiuk** [stenzek/duckstation#2029] opened 2021-04-26 14:00 UTC
**Game details**
[SLUS-00922]
[Dino crisis (USA)]

**Description of the issue / bug**
graphics bugs and glitches
in dino crisis, graphics completely buggy after the last update. No matter which option you choose, the game does not return to normal, it is completely buggy and unplayable. The rendering of the models and the scenery was all compromised.

**Controller Troubleshoot Report**
1. no
2. analog dualshock

**Steps to reproduce**
[at the beginning of the game you can already see the problems (savestates too), menus are ok, only in 3d rendering/background ]

**Enhancements information**
[disabled all]

**Hardware/software**
[amd ryzen 5 1600, gtx 1070, win10]
[D3D11/OpenGL/Vulkan, i'm use opengl, but in all of them the same problem occurs]

**Emulator version**
[0.1 3881]

**Additional context**
[it doesn't have much to say, in the previous version it worked normal, after today update it doesn't work with any options, neither in software rendering nor in anything, as you can see in the attached images, they are bugs in 3d graphics rendering]

![SLUS-00922_2021-04-26_10-59-43](https://user-images.githubusercontent.com/46766099/116095274-a50b3f80-a67e-11eb-8bd6-f04d2482370b.png)
![SLUS-00922_2021-04-26_11-00-11](https://user-images.githubusercontent.com/46766099/116095280-a5a3d600-a67e-11eb-9ce5-e809a8da0a8a.png)
![SLUS-00922_2021-04-26_11-00-17](https://user-images.githubusercontent.com/46766099/116095284-a63c6c80-a67e-11eb-9053-ecda3f67ba5e.png)
![SLUS-00922_2021-04-26_11-00-28](https://user-images.githubusercontent.com/46766099/116095285-a6d50300-a67e-11eb-9326-3f374312c2e2.png)

**Comment by stenzek** [comment] 2021-04-26 14:02
You did not fill out the issue template.

**Comment by ajkmetiuk** [comment] 2021-04-26 14:12
sorry, I updated the post, now is it correct?

**Comment by stenzek** [comment] 2021-04-26 14:13
Sure. Does this happen if you reboot the game or only when loading state?

**Comment by ajkmetiuk** [comment] 2021-04-26 14:14
it makes no difference, both in savestate and starting a new game, the same thing happens

**Comment by stenzek** [comment] 2021-04-26 15:12
Try deleting settings.ini and starting fresh (and use dx11 not GL). I can't reproduce any issue here.

It could also be because you're forcing some option in your graphics control panel (e.g. anisotropic filtering)

**Comment by ajkmetiuk** [comment] 2021-04-26 16:02
Edit: Nevermind, I see it now. Not sure why it wasn't showing up before..

I also tried the sles version of the game, but the result is exactly the same, Glad you could reproduce the error as well.

**Comment by stenzek** [comment] 2021-04-26 16:26
Fixed in https://github.com/stenzek/duckstation/commit/e842abfa8a03e75e9822e0924e72645ed7622cd2

**Closed by stenzek** 2021-04-26 16:26 UTC

**Comment by ajkmetiuk** [comment] 2021-04-26 16:35
> Fixed in [e842abf](https://github.com/stenzek/duckstation/commit/e842abfa8a03e75e9822e0924e72645ed7622cd2)

oh, thanks for taking some of your time to fix this problem.

**Comment by stenzek** [comment] 2021-04-26 16:54
Thanks for reporting, this is why the preview build exists, to catch things like this.

Just a coincidence that it was Dino Crisis - someone reported it wasn't booting earlier today, and of course it works fine, hence my confusion :)
