### ISSUE TITLE
Graphical glitch in Boundary Gate - Daughter of Kingdom (Japan) using OpenGL

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#215] opened 2020-04-03 03:14 UTC
Using OpenGl, when you enter a building this glitchy line appears. 

![SLPS-00907_2020-04-03_14-10-18](https://user-images.githubusercontent.com/31968468/78320487-54c5c900-75b5-11ea-8959-0cf1055fb839.png)

It looks fine in software.

![Capture](https://user-images.githubusercontent.com/31968468/78320546-6e671080-75b5-11ea-83da-7ba5a1a06064.PNG)

**Comment by stenzek** [comment] 2020-05-17 09:35
Is this still happening on the latest build?

**Comment by kurayami6** [comment] 2020-05-17 09:51
It still happens. Turns out it also happens in D3D11.

**Comment by stenzek** [comment] 2020-05-17 10:36
Can't seem to reproduce it. Is there any more specific conditions?

**Comment by kurayami6** [comment] 2020-05-17 10:48
It might only happen in when entering certain buildings. From the start of the game walk forward through the two doors, then turn left and enter the tavern. 

![SLPS-00907_2020-05-17_20-47-21](https://user-images.githubusercontent.com/31968468/82142442-aed9cf80-987f-11ea-8d3c-6cd278a1a384.png)

![SLPS-00907_2020-05-17_20-45-17](https://user-images.githubusercontent.com/31968468/82142412-84881200-987f-11ea-9571-f9622553fbd2.png)

![SLPS-00907_2020-05-17_20-47-32](https://user-images.githubusercontent.com/31968468/82142445-b6997400-987f-11ea-9d1a-0c8c368aef8b.png)

**Comment by kurayami6** [comment] 2020-05-17 10:57
There are more glitches if you enter the shop next door to the inn. 

![SLPS-00907_2020-05-17_20-55-23](https://user-images.githubusercontent.com/31968468/82142615-f44acc80-9880-11ea-991b-3bb97955a2e9.png)

![SLPS-00907_2020-05-17_20-55-27](https://user-images.githubusercontent.com/31968468/82142616-fa40ad80-9880-11ea-97e2-2eff6f26b015.png)

**Comment by stenzek** [comment] 2020-08-18 09:02
OpenGL issue - closing as OpenGL renderer is "deprecated".

**Closed by stenzek** 2020-08-18 09:02 UTC
