### ISSUE TITLE
Dexter's Laboratory - Mandark's Lab (Europe) Bootup Bios noise doesn't properly stop

### ISSUE THREAD

**Issue by waspennator** [stenzek/duckstation#1950] opened 2021-04-09 22:03 UTC
**Game details**
 SLES-03627 Dexter's Laboratory - Mandark's Lab (Europe)
Redump Verified

**Description of the issue / bug**
Bootup Bios sound continues to play even after the bios screen is finished, it only seems to properly end once the intro cutscene finishes. tested it with both the US and PAL versions and it only seems to happen with the PAL version.

**Steps to reproduce**
Boot up the PAL version and listen as the bios bootup noise doesn't stop. It should keep going until the cutscene finishes and the first loading screen is done.  On the US version the noise should stop before the "Cartoon Network Interactive" bumper.

**Hardware/software**
i5 6600k
Geforce GTX 1070
Windows 10
Vulkan 

**Emulator version**
0.1-3754 Preview Build

**Comment by BloodRaynare** [comment] 2021-04-10 02:14
Seems like the same problems as #407

**Comment by stenzek** [comment] 2021-04-10 03:36
Has this been verified on console? Sounds like the PAL version isn't resetting the SPU but the US version is.

**Comment by stenzek** [comment] 2021-04-11 17:30
Duplicate of #407 - you can use fast boot as a workaround for games which don't reset SPU like this.

**Closed by stenzek** 2021-04-11 17:30 UTC
