### ISSUE TITLE
nightmare creatures ( playstation audio bug hangs when the video to the game starts to play

### ISSUE THREAD

**Issue by Cibomatto2002** [stenzek/duckstation#1199] opened 2020-12-12 01:07 UTC
After the playatation logo goes away and the video starts to play the audio from the playstation logo audio hangs it hangs until the game video stops and the game starts to load.  

Also i'm not sure but is the playstation logo cutting off to soon i think i remember it lasting longer but im not sure it has been a long time that i have seen it play.

I found a video of the boot up screen. https://www.youtube.com/watch?v=DIxUScfOQwg

**Comment by stenzek** [comment] 2020-12-12 01:10
Duplicate of https://github.com/stenzek/duckstation/issues/407

Use fast boot - it doesn't have this problem.

**Closed by stenzek** 2020-12-12 01:10 UTC

**Comment by Cibomatto2002** [comment] 2020-12-12 01:11
ok thanks
