### ISSUE TITLE
Fast Forward and Rewind for the BIOS CD player not implemented

### ISSUE THREAD

**Issue by Blackbird88** [stenzek/duckstation#874] opened 2020-09-22 12:19 UTC
While it plays Audio CDs perfectly, it has 100% guaranteed crash if you press either L2 or R2.
Note: I am more curious if this is something games can have problem with too. Whether this feature works or not isn't big deal 😀
![image](https://user-images.githubusercontent.com/4414625/93880957-8c007180-fcde-11ea-976b-c640ea9d96b8.png)

![image](https://user-images.githubusercontent.com/4414625/93880950-886cea80-fcde-11ea-907e-cd68639e5c79.png)

**Comment by stenzek** [comment] 2020-09-22 12:44
Duplicate of https://github.com/stenzek/duckstation/issues/610. I'll close the other one because it's from a deleted user and doesn't show up in search.

**Comment by stenzek** [comment] 2020-10-29 15:15
Implemented in https://github.com/stenzek/duckstation/commit/a6947fbc7086dccd4d70e1a2b6ad54df19b2235f

**Closed by stenzek** 2020-10-29 15:15 UTC
