### ISSUE TITLE
Emulator hangs when assigning shortcuts

### ISSUE THREAD

**Issue by andercard0** [stenzek/duckstation#767] opened 2020-08-16 20:07 UTC
okay, I was trying to assign a hotkey for fast-forward but after assign it DS freezes

To reproduce issue: load a game normally start to play go to configuration >
shortcut configuration (in my case was changing Fast Foward) so > General tab > 
click on the option so the emu starts to count waiting for a input I did choose a button. 

I did close the options in order to return to play, the game just freeze. 
There was no another option but to restart the emulation.

**Comment by stenzek** [comment] 2020-08-17 01:49
Can you reliably reproduce this? I can't seem to.

**Comment by andercard0** [comment] 2020-08-18 23:58
Sorry for lack of information, I'll enable log to file and attach here as soon it happens again.

**Comment by stenzek** [comment] 2020-09-14 14:40
Closing due to activity. If this is still happening please let me know.

**Closed by stenzek** 2020-09-14 14:40 UTC
