### ISSUE TITLE
Downsampling Adaptive issue

### ISSUE THREAD

**Issue by Alien-Grey** [stenzek/duckstation#1465] opened 2021-01-15 17:28 UTC
I've been using Downsampling set at Adaptive for some time without issues. With latest builds something seems wrong as Im getting stuttering. this already happens at the SONY boot screen. This only seems to happen with Downsampling set at Adaptive with Internal Resolution Scale set at Automatic based on window size and Crop set at All borders.

**Comment by stenzek** [comment] 2021-01-15 17:32
Try turning off sync to host refresh rate, vsync, check GPU load (downsampling can be expensive).

**Comment by Alien-Grey** [comment] 2021-01-15 17:36
Edited my post to add Crop set at All borders.

Vsync is disabled.

**Comment by Alien-Grey** [comment] 2021-01-16 13:20
With Internal Resolution Scale set at Automatic based on window size it always renders the boot screen at 2560 x 2032 pixels no matter what the screen resolution is. But I still don't understand why it only stutters with cropping set at All borders.

**Comment by stenzek** [comment] 2021-01-16 15:39
Can't seem to reproduce this on my end.

**Comment by Alien-Grey** [comment] 2021-01-16 15:47
The reason why I'm getting stuttering is because with Crop set at All borders it renders at 2 x the resolution that what it supposed to be and the poor GPU can't handle it. My screen resolution is 1280 x 720 pixels with Crop set to None or Only Overscan Area the image is rendered at 640 x 480 pixels. With Crop set at All Borders it renders it at 1280 x 960.

**Comment by stenzek** [comment] 2021-04-06 08:06
Closing as I was unable to reproduce any issue here.

**Closed by stenzek** 2021-04-06 08:06 UTC
