### ISSUE TITLE
macOS Vulkan fullscreen crashes.. Debug file here:

### ISSUE THREAD

**Issue by spotanjo3** [stenzek/duckstation#2193] opened 2021-05-30 10:14 UTC
I complied and built it. Everything's working fine but fullscreen crashes if I used Vulkan.  Here:

[duckstation vulkan fullscreen macOS crashes.zip](https://github.com/stenzek/duckstation/files/6566025/duckstation.vulkan.fullscreen.macOS.crashes.zip)

**Comment by stenzek** [comment] 2021-05-30 10:20
Duplicate of https://github.com/stenzek/duckstation/issues/1436 which is closed, since I can't debug a platform which I don't own.

**Closed by stenzek** 2021-05-30 10:20 UTC

**Comment by spotanjo3** [comment] 2021-05-30 10:25
Thank you. I understand. Sorry about your treated in that thread. He was stupid. Keep up the good work. Hopefully this zip file can be helpful with someone who is experience and own a macOS. Cheers.
