### ISSUE TITLE
Actual CD/backups support

### ISSUE THREAD

**Issue by VermillionFury007** [stenzek/duckstation#2271] opened 2021-06-17 01:51 UTC
It woud be cool if we could use actual fisical cds to run in the emulator...

**Comment by stenzek** [comment] 2021-06-17 02:47
You deleted the issue template.

Also duplicate of https://github.com/stenzek/duckstation/issues/1271

This isn't something I have any plans to implement at the moment. My intuition is that due to spinup/spindown it'll cause drastically inconsistent seek times, resulting in emulation hitches.

**Closed by stenzek** 2021-06-17 02:47 UTC
