### ISSUE TITLE
Xenogears (USA) Disc 1 Boss Fight Freeze

### ISSUE THREAD

**Issue by Djymm676** [stenzek/duckstation#2007] opened 2021-04-21 14:23 UTC
**Game details**
[SLUS-00664 Xenogears Disc 1 (USA)]

**Description of the issue / bug**
[Up til now everything worked fine. I had been using the same cheats the entire time and even with them disabled I run into the same problem. The game and music freeze at boss fight as soon as my character is shown. I was able to defeat this boss yesterday and the one right after but, ,froze on the third.]

**Controller Troubleshoot Report**
1. No
2. SDL

**Steps to reproduce**
[When loading from the memory card, get into the gear and go up the elevator, a cutscene will play out leading up to a boss fight, When the screen break effect happens, you'll see the boss moving around but as soon as the camera pans on your gear, it freezes.]

**Hardware/software**
Intel (R) Pentium (R) CPU G2030T @ 2.60 GHz  2.60 GHz
Intel (R) HD Graphics
Windows 8.1

**Emulator version**
[DuckStation 0.1-3128-g05545566 (dev)]

**Comment by stenzek** [comment] 2021-04-21 16:05
Could you please upload a memory card at this location?

**Comment by Djymm676** [comment] 2021-04-21 16:33
Here it is: 

[Xenogears (USA) (Disc 1)_1.zip](https://github.com/stenzek/duckstation/files/6352538/Xenogears.USA.Disc.1._1.zip)

**Comment by stenzek** [comment] 2021-04-21 17:33
Definitely a game crash. I have a suspicion this might be caused by the cheats creating an invalid/corrupted save - your memory card also crashes in the Mednafen emulator.

**Comment by Djymm676** [comment] 2021-04-21 17:57
Thanks for your help!

**Comment by stenzek** [comment] 2021-04-22 02:30
Closing since I'm almost certain this is a save issue, not an emulator bug.

**Closed by stenzek** 2021-04-22 02:30 UTC
Labels: Possibly Invalid
