### ISSUE TITLE
Vibration/Haptic feedback/Rumble for the DInput only Logitech Rumblepad 2. 

### ISSUE THREAD

**Issue by cloudbill** [stenzek/duckstation#2045] opened 2021-05-01 22:38 UTC
As the title describes I would like support for vibration/rumble/haptic feedback for the Logitech Rumblepad2 DInput only capable gamepad. It's an old gamepad that's only capable of DInput but it's still functioning and actually has working rumble support in Retroarch and Epsxe on Windows 10. Currently the gamepad works just fine in Duckstation using DInput in everything but vibration/rumble/haptic feedback. Here is a the Logitech link to the support page for the legacy gamepad (not that it will be of any help.):   
https://support.logi.com/hc/en-us/articles/360025263654--Product-Gallery-Rumblepad-2

**Comment by jpchow26** [comment] 2021-05-02 00:11
I have not used this, but try https://sourceforge.net/projects/xoutput/ to wrap your DInput controller into a XInput converted 360 pad

**Comment by cloudbill** [comment] 2021-05-02 00:30
I figured since DInput works in and of itself that Dinput haptic feedback should as well without using an external wrapper. Don't get me wrong...I'm not against trying the wrapper but I would much rather see Duckstation support DInput haptic feedback internally than to rely on an external wrapper.

**Comment by jpchow26** [comment] 2021-05-02 00:36
Likely won't happen. It's one developer building the vast majority of the application, therefore focus is on the most up to date hardware and APIs. (eg. Windows 7 isn't supported) Anything is possible (it's open source afterall) but likely isn't happening unless someone else wants to add Dinput support.

**Comment by stenzek** [comment] 2021-05-02 01:58
Duplicate of https://github.com/stenzek/duckstation/issues/1246

Not really interested in implementing this any time soon, the dinput API is quite clunky. But it shouldn't be too difficult if anyone else wanted to.

**Closed by stenzek** 2021-05-02 01:58 UTC

**Comment by Phantasm90** [comment] 2021-05-02 02:25
> (Also, SDL supports dinput vibration)

How do i enabled it though? I have a G-Shark GS-GP702 and the log says rumble is not supported

> I/SDLControllerInterface: Opened controller 0 (instance id 0, player id 0): G-Shark GS-GP702
> E(OpenGameController): Failed to create haptic left/right effect: Haptic: Effect not supported by haptic device.
> E(OpenGameController): No haptic rumble supported: Haptic: Effect not supported by haptic device.
> W(OpenGameController): Rumble is not supported on 'G-Shark GS-GP702'

**Comment by Phantasm90** [comment] 2021-05-27 01:24
If you still want to get rumble on your D-input device, try this https://github.com/stenzek/duckstation/issues/1246#issuecomment-849242081
