### ISSUE TITLE
Transparency is broken in High Heat Major League Baseball 2002 (USA)

### ISSUE THREAD

**Issue by ghost** [stenzek/duckstation#592] opened 2020-07-07 13:02 UTC
After the first loading screen, this screen appears. On real hardware the background is transparent and made up of horizontal lines. 

![Capture](https://user-images.githubusercontent.com/31968468/86785267-c4ac8980-c0a5-11ea-88fa-7112cf1f8ac3.PNG)

However in Duckstation this effect is broken with all renderers.

All hardware renderers look like this.

![SLUS-01244_2020-07-07_05-38-00](https://user-images.githubusercontent.com/31968468/86785352-df7efe00-c0a5-11ea-88cf-4c61bab82ff6.png)

The software renderer looks like this.

![Capture2](https://user-images.githubusercontent.com/31968468/86785425-f4f42800-c0a5-11ea-84c3-42afead2b1c5.PNG)

**Comment by stenzek** [comment] 2020-07-10 08:52
Seems like it might be transparency/blending related. May need 16-bit framebuffers.

Software looks correct, the background is probably more noticeable on the TV because of the gamma ramp.

**Comment by Shideravan** [comment] 2020-12-08 23:51
I can confirm that still happening as of 0.1-2499-g770dd5a6.

**Comment by stenzek** [comment] 2021-05-26 12:51
Marking this one as won't fix, the long term solution for these incompatibilities is a compute shader software renderer, which I am occasionally working on.

**Closed by stenzek** 2021-05-26 12:51 UTC
Labels: GPU
