### ISSUE TITLE
Game crashes randomly Soul Blade (USA) (v1.1)

### ISSUE THREAD

**Issue by Snake356** [stenzek/duckstation#1472] opened 2021-01-17 04:22 UTC
Soul Blade just crashes if you play it normally in the middle and the Duckstation crashes too. I play with the Soul Blade (USA) (v1.1). 

Why is it that it crashes?

**Comment by Kurayami7** [comment] 2021-01-17 04:39
What does the log say?

**Comment by stenzek** [comment] 2021-01-17 04:51
Where is it crashing? From a quick test here it seems fine.

**Comment by Alien-Grey** [comment] 2021-01-17 07:44
I can confirm that Soul Blade (Europe) - SCES-00577 works fine. Only one small issue and that is that the audio glitches a few times in the intro FMV. I've tried to fix that with changing settings but didn't find a fix for it yet. I know my image dump works fine as I also tried it with Mednafen PSX and had no issues.

**Comment by Kurayami7** [comment] 2021-01-17 07:51
Soul Blade (USA) works perfectly. The game doesn't crash and neither does the emulator. 

![SLUS-00240_2021-01-17_18-49-09](https://user-images.githubusercontent.com/77198254/104834658-02138e80-58f5-11eb-9b87-17774bcfb869.png)

**Comment by Alien-Grey** [comment] 2021-01-17 13:28
To play the intro FMV from Soul Blade (Europe) - SCES-00577 without glitches I,ve got to use force NTSC Timings (60Hz  on PAL). But that also makes the game run faster.

**Comment by Snake356** [comment] 2021-01-17 16:14
I tested the game briefly to see if it was going well, so everything goes fine at the opening. Then I tried Arcade and then at some point where I kept going on each stage it just crashed or the Duckstation closed automatically without an error message or anything else. But it only happens by chance somehow, sometimes I get ahead and sometimes not then crashes directly but also in training mode runs without problems. It actually happens when it changes the stage or something triggers a certain move in combat.

Could it be due to my settings?

> What does the log say?

Where can I see the log?

**Comment by Kurayami7** [comment] 2021-01-17 16:17
Advanced settings. Set log level to debug and choose "log to system console". If the game crashes the log should show an error message. 
![Capture](https://user-images.githubusercontent.com/77198254/104849016-b506db00-593b-11eb-9fd2-3e138526c0cb.PNG)

**Comment by stenzek** [comment] 2021-01-17 16:26
> To play the intro FMV from Soul Blade (Europe) - SCES-00577 without glitches I,ve got to use force NTSC Timings (60Hz on PAL). But that also makes the game run faster.

Seems to be working fine here.

@Snake356 Try switching to the interpreter in console settings. If that works, switch back to the recompiler, and try changing the "fast memory mode" in advanced settings from MMap to LUT.

**Comment by Snake356** [comment] 2021-01-17 16:29
> Advanced settings. Set log level to debug and choose "log to system console". If the game crashes the log should show an error message.
> 
> 
> So let me clarify, you're saying that while playing arcade mode in Soul Blade (USA), Duckstation will randomly close itself?

Exactly, that's what I mean by that. I don't know why this is happening either. I also tested it several times like 2 times and the game stopped and Duckstation closed automatically.

 
> 
> @Snake356 Try switching to the interpreter in console settings. If that works, switch back to the recompiler, and try changing the "fast memory mode" in advanced settings from MMap to LUT.

Ok, I'll try it out.

**Comment by Kurayami7** [comment] 2021-01-17 16:34
I'm up to stage 6 and it works fine so far. Does it happen with different characters?

**Comment by Alien-Grey** [comment] 2021-01-17 16:43
> > To play the intro FMV from Soul Blade (Europe) - SCES-00577 without glitches I,ve got to use force NTSC Timings (60Hz on PAL). But that also makes the game run faster.
> 
> Seems to be working fine here.
> 
> @Snake356 Try switching to the interpreter in console settings. If that works, switch back to the recompiler, and try changing the "fast memory mode" in advanced settings from MMap to LUT.

What do you mean with that?

For me the Intro FMV is running at 20 fps and that's why I tried forcing NTSC timings. That fixes the glitches.

**Comment by stenzek** [comment] 2021-01-17 16:46
> What do you mean with that?
> For me the Intro FMV is running at 20 fps and that's why I tried forcing NTSC timings. That fixes the glitches.

What glitches? 20fps looks like the intended framerate, and I see no difference between forcing NTSC and not.

**Comment by Snake356** [comment] 2021-01-17 17:06
I tried it again and then found that the widescreen hack was not activated. I then set this and now it works curiously without any problems.  It's strange that it crashes without a widescreen hack.

**Comment by stenzek** [comment] 2021-01-17 17:19
Known issue with upscaling on those stages. Works fine at 1x.

**Comment by Alien-Grey** [comment] 2021-01-18 09:17
> > What do you mean with that?
> > For me the Intro FMV is running at 20 fps and that's why I tried forcing NTSC timings. That fixes the glitches.
> 
> What glitches? 20fps looks like the intended framerate, and I see no difference between forcing NTSC and not.

That's strange because I tested it on three different computers and all had this glitch. If I force it to NTSC timings it plays it just fine but the clock is running faster in the game because of the 60 fps. Maybe I should try different settings because all tests were done with the same settings.

**Comment by stenzek** [comment] 2021-01-18 09:29
> That's strange because I tested it on three different computers and all had this glitch. If I force it to NTSC timings it plays it just fine but the clock is running faster in the game because of the 60 fps. Maybe I should try different settings because all tests were done with the same settings.

You still haven't said what the glitch actually is. Graphical? Audio? What is wrong?

**Comment by Alien-Grey** [comment] 2021-01-18 10:19
Audio skipping at 50Hz.

I captured the video to show you the difference between 50Hz and 60Hz and uploaded it to YouTube.

Link: https://www.youtube.com/watch?v=myI9ixGVxvA

**Comment by stenzek** [comment] 2021-01-20 02:42
Audio hitching should be fixed in https://github.com/stenzek/duckstation/commit/3c012ec6ef43d0dbdef6e5522efc9f77ab4a7648 (preview build).

**Comment by Alien-Grey** [comment] 2021-01-20 08:53
Thanks. 

I can confirm that it's fixed. I'm going to delete the video on youtube as it is no longer needed.

**Comment by Kurayami7** [comment] 2021-02-05 06:01
This can be closed. I played through the whole arcade mode with all enhancements off and the software renderer. The game didn't crash nor did Duckstation close itself, obviously.

**Comment by stenzek** [comment] 2021-02-05 06:06
Thanks for checking.

**Closed by stenzek** 2021-02-05 06:06 UTC
