### ISSUE TITLE
Pop'n Music 6; not showing selection menu upon losing on Free mode

### ISSUE THREAD

**Issue by Neorocket64** [stenzek/duckstation#404] opened 2020-05-06 14:41 UTC
Pop'n Music 6 [SLPM-87089]
![SLPM-87089_2020-05-06_21-16-52](https://user-images.githubusercontent.com/17949796/81189803-37838080-8fe1-11ea-8879-1e59f9b3af69.png)
result screen on free mode. upon losing, supposed to have menu to navigate
![SLPM-87089_2020-05-06_21-16-14](https://user-images.githubusercontent.com/17949796/81189895-56821280-8fe1-11ea-8c24-b061902e531d.png)
comparison to winning the game

the correct one has correct animation pop up as normal.
you can see the menu on losing in split second upon hiding "Stage Failed" and menu by pressing and holding (X) (to see the scores)

**Comment by stenzek** [comment] 2020-05-15 14:41
Probably related to DMA timing.

**Comment by stenzek** [comment] 2020-06-18 08:46
Looks like this might be fixed with the latest changes? Can you please confirm if this is still happening?

**Comment by stenzek** [comment] 2020-06-19 06:08
Confirmed fixed via Discord (interlacing must be enabled).

**Closed by stenzek** 2020-06-19 06:08 UTC
Labels: GPU
