### ISSUE TITLE
Broken graphics appear briefly during the opening of Dreams (Europe)

### ISSUE THREAD

**Issue by goodrain1992** [stenzek/duckstation#2726] opened 2021-11-13 07:24 UTC
**Game details**
[Serial Code, Region]
[SLES-00714] Dreams (Europe)

**Description of the issue / bug**
After you choose the language the screen transitions to the start menu and briefly shows this.

![SLES-00714_2021-11-13_18-11-31](https://user-images.githubusercontent.com/94057177/141609876-8c8fe5ae-23fa-44e6-9505-2a0c4ec36a32.png)

Once you choose start this briefly appears.

![SLES-00714_2021-11-13_18-12-11](https://user-images.githubusercontent.com/94057177/141609893-10e958d0-aceb-4085-bf76-3132f1d66770.png)

**Controller Troubleshoot Report**
No
Analog 

**Steps to reproduce**
Start the game and get to the start menu

**Enhancements information**
Tested with all enhancements off and software renderer.  Also happens with Vulkan.

**Hardware/software**
GTX 1080, intel i7, Windows 10
Tested with software and Vulkan

**Emulator version**
Duckstation 0.1 - 4815 - gf982a2a5

**Additional context**
Dump is confirmed accurate.

![dream](https://user-images.githubusercontent.com/94057177/141610021-53ebfdcc-dcca-4297-8621-091381fa7b87.PNG)

Here's a video of the game being played and the issue not happening.

https://www.youtube.com/watch?v=I-EpAJxsZuY&t=128s

**Comment by stenzek** [comment] 2021-11-13 07:37
Duplicate of https://github.com/stenzek/duckstation/issues/1801

Basically, it's got some parallels to beam racing, and would be very slow to emulate.

**Closed by stenzek** 2021-11-13 07:37 UTC
