### ISSUE TITLE
(Android) DuckStation not saving duckstation.log until fully closed

### ISSUE THREAD

**Issue by 6lackmag3** [stenzek/duckstation#2237] opened 2021-06-07 13:43 UTC
**Description of the issue / bug**
Emulator stops creating log file until app is force closed.

**Steps to reproduce**
Enable logging to file, start any game, close it, delete or move duckstation.log, start a game, close it, go into DS directory - log wont be created unless you force stop DuckStation.

**Enhancements information**
None.

**Hardware/software**
Android 10, sdm712

**Emulator version**
Currently 0.1-4195 but this applies to other versions too.

**Comment by stenzek** [comment] 2021-06-07 15:05
Working as intended, it doesn't flush until the native library is closer. That's why I have "close and restart the app" in the logging wiki page.

I guess I could flush on closing a game, but then it wouldn't log scanning related issues.

**Closed by stenzek** 2021-06-07 15:05 UTC

**Comment by 6lackmag3** [comment] 2021-06-07 15:28
> That's why I have "close and restart the app" in the logging wiki page.

Ah sorry, didn't see that.

A friend of mine with Shield tablet had been asking if you could please add 'Exit' button to completely close DuckStation. He's facing random crashes on compiling shaders after he switches renderer and the only solution so far is to force close the app.

**Comment by stenzek** [comment] 2021-06-07 15:33
Swiping the app away from the list should do that.

I believe having exit buttons is against android design guidelines, but I could be wrong.
