### ISSUE TITLE
[SLUS-01072] Evil Dead - Hail to the King (USA) (Disc 1) - Don't exit from inventary which softlocks the game.

### ISSUE THREAD

**Issue by Shideravan** [stenzek/duckstation#698] opened 2020-08-03 18:17 UTC
**Version**
0.1-1409-ge198e315

**Issue**
After begin the game, softlocks in inventary screen. The expected behavior is to exit the inventory screen and control Ash after press "Triangle button".

**Comment by stenzek** [comment] 2020-08-03 18:35
Duplicate of https://github.com/stenzek/duckstation/issues/698

**Comment by stenzek** [comment] 2020-08-03 18:36
... phone fail. I swear there was an open issue for this game

**Comment by stenzek** [comment] 2020-08-03 18:40
Okay I'm not going crazy : https://github.com/stenzek/duckstation/issues/214

It just doesn't show up in search for some reason, I guess because kurayami deleted his account. How strange.

**Comment by Shideravan** [comment] 2020-08-03 20:40
Yes, I'm searching before cheate new issues but didn't found that too. 
Do you think that's why I not found the [SLPS-02348] 20 seiki striker retsuden issue in the search too?

**Comment by stenzek** [comment] 2020-12-05 15:20
Fixed in https://github.com/stenzek/duckstation/commit/d75705689125df2134b29accdbd7028c76cf994e

**Closed by stenzek** 2020-12-05 15:20 UTC
