### ISSUE TITLE
downsampling adaptive without effecting text

### ISSUE THREAD

**Issue by ronnyc4** [stenzek/duckstation#1798] opened 2021-03-13 13:25 UTC
is it possible to make downsampling adaptive mode without effecting text? so it's only a effecting background image.
cause in epsxe 2.0.5 this is possible with setting texture filtering: extended and hi-res texture: none.

**Comment by stenzek** [comment] 2021-03-13 13:28
Duplicate of #1293.

**Closed** 2021-03-13 13:28 UTC
