### ISSUE TITLE
Battle Arena Toshinden (USA) vídeo accelerated!!!! In Duckstation emulator!

### ISSUE THREAD

**Issue by momoids** [stenzek/duckstation#841] opened 2020-09-11 21:24 UTC
Battle Arena Toshinden (USA) accelerated!!!! In Duckstation emulator!

Vídeo:
https://www.youtube.com/watch?v=hC4PD-tHTiw&feature=youtu.be

**Comment by DarkSwan86** [comment] 2020-09-13 09:45
Duplicate of #695 .

**Comment by stenzek** [comment] 2020-09-13 10:35
Closing as it is a duplicate.

As an aside, try using the interpreter, or forcing recompiler icache in the game properties.

**Closed by stenzek** 2020-09-13 10:35 UTC

**Comment by momoids** [comment] 2020-09-13 19:19
Ok! I'm Try..
