### ISSUE TITLE
Fighting Force (Europe) (En,Fr,De) (Demo and Full Version): Music Looping Issue

### ISSUE THREAD

**Issue by waspennator** [stenzek/duckstation#1952] opened 2021-04-10 10:22 UTC
**Game details**
SLED-00881 Fighting Force (Europe) (En,Fr,De) (Demo)
SLED-00731 Fighting Force (Europe) (En,Fr,De)
Redump Verified

**Description of the issue / bug**
Music doesn't seem to properly loop when it gets to the end, though oddly enough, it seems pausing and unpausing when it stops seems to fix it, tested with the demo version as well as the full version and it seems to happen on both.

**Steps to reproduce**
Start the first level and beat up all the starting goons, then instead of heading to the next area, sit and wait for the music to finish up, it shouldn't restart automatically, pausing and unpausing after this should fix it up and make it restart.

**Hardware/software**
i5 6600k
Geforce GTX 1070
Windows 10
Vulkan 

**Emulator version**
0.1-3760 Preview Build

**Additional context**
Skip to around 0:27 ish
[Fighting Force Pal Version Music Bug.zip](https://github.com/stenzek/duckstation/files/6289638/Fighting.Force.Pal.Version.Music.Bug.zip)

**Comment by stenzek** [comment] 2021-04-11 02:31
Relies on the next track getting returned in GetlocP.

Seems like a regression from 25d4060bcef572a263d8a4dccae93c22a5598de8 - either nocash's notes are incorrect here, or my simulating of the laser holding is incorrect - but from what I remember my tests only showed it jumping backwards, not forwards.

**Comment by waspennator** [comment] 2021-04-11 03:02
![Duckstation Log3](https://user-images.githubusercontent.com/78768499/114290671-7ebe9080-9a3e-11eb-8a4a-ab9bba622ec0.png)
Might as well dump the console log just incase, nothing notable seemed to pop up when the level started, though I did notice there seemed to be some CD-Rom Pause commands sprinkled alongside the read messages here and there, as far as I know though, nothing popped up in the console log when I was testing in the level itself, only before the level finished loading.

Only thing I know for sure is that when the game is paused and unpaused, that somehow fixes the music.

**Comment by stenzek** [comment] 2021-04-11 03:08
It's already fixed in https://github.com/stenzek/duckstation/commit/8df0496dc1729c513cf8adebc58970d202bdbb9b, just haven't pushed it to master yet because I have other changes to go in today as well.

**Closed** 2021-04-11 17:29 UTC

**Comment by waspennator** [comment] 2021-04-12 17:34
Was finally able to update to test the fix and yep, both the demo and the full version music loops properly once it ends.
