### ISSUE TITLE
Driver 2 Back on the Streets FPS drops

### ISSUE THREAD

**Issue by fox140cv** [stenzek/duckstation#2384] opened 2021-07-10 07:34 UTC
**Game details**
SLES-02997 / SLES-12997
Driver 2 - Back on the Streets (Spain)

**Description of the issue / bug**
frame drops, sometimes up to 7 fps

**Enhancements information**
all turned off 

**Hardware/software**
i5 6600k
nvidia gtx 1060
windows 10 x64
tested on all renderers including software with and without enhancements

**Emulator version**
0.1-4416-g24b4be51

**Additional context**
I tried it on my ps2 with the original cd and there is some downturn, but none that abrupt.
(By the way, when testing this game on the ps2, I have noticed that the vibration in duckstation does not work with the controller of ps2 or ps3, however it works in retroarch.)
![1](https://user-images.githubusercontent.com/79443698/125155573-360f9400-e161-11eb-97d4-23debf120743.png)

**Comment by stenzek** [comment] 2021-07-10 11:52
You should compare with PS1, not PS2 (as a few parts of the PS1 are emulated on PS2).

**Comment by fox140cv** [comment] 2021-07-10 18:37
I'll talk to a friend who has a PS1 to see if it has these steep fps drops. I remember I finished it about 20 years ago on my old PS1 and I even keep the save game and I don't remember any of this, thanks.

**Comment by diego-rbb-93** [comment] 2021-07-11 12:37
I have been playing the Spain version in the last two years while Duckstation evolved as im a BIG fan of it. Believe me, Stenzek did his best about pushing this one. Driver 2 is one of the worst coded games running on PS1. Have in mind you are running a PAL version, which helps making things worse with the framerate.

Your only chance to play Driver 2 to its limits, is using the ReDriver 2 PC mod build.

**Comment by stenzek** [comment] 2021-07-11 12:42
When I was messing around with D2 I did notice the occasion *large* frame rate drop when driving quickly, I put it down to the data not being streamed in quickly enough. In which case it's probably not a bug, since in almost all cases the emulator's CPU speed will be faster than the console, not slower.

**Comment by diego-rbb-93** [comment] 2021-07-11 12:44
"When I was messing around with D2 I did notice the occasion large frame rate drop when driving quickly"

Aaaand yeah, that was natural behaviour on consoles.

**Comment by stenzek** [comment] 2021-07-11 12:46
Yeah, makes sense. I only questioned it because I also fell through the world, but that was on a branch where I was implementing GTE timings, or it needed a rebuild due to struct layout changes. Video for reference: https://cdn.discordapp.com/attachments/695640472202379428/854978854443548712/Driver_2_USA_Disc_1_2021-06-17_17-00-03.mp4

**Comment by diego-rbb-93** [comment] 2021-07-11 12:51
Spoiler: That kind of thing can happen on console. Ive seen a lot of these glitches. Ofc, when this happened to you could perfectly be related to the changes needed to make the game work as it should.

Anyway, @fox140cv , I encourage you to test deeper. Recently I played again D2 (Spain) on my SD865 phone and I found out there was some kind of bug that made the game slowdown like hell when you drove in-game to east orientation (it was related to PGXP enhancements).

Make sure to add some CPU overclocking, will help (however, if you try to save the data in the game, turn it off, the Memory Card can't be detected on this game if Overclocking is on),

**Comment by stenzek** [comment] 2021-07-11 13:15
> however, if you try to save the data in the game, turn it off, the Memory Card can't be detected on this game if Overclocking is on

FYI, this is because the memory card code in the BIOS is **terrible** and uses busy loops for delays. We can probably fix that by scaling the pad timings based on the overclock.

**Comment by diego-rbb-93** [comment] 2021-07-11 16:46
Is it too hard to fix? I wouldn't ask you to lose time on it unless is easy to fix, but, the only thing you would prevent would be users adressing something is broken with Memory cards and saving, not like is something really needed for DS.

**Comment by fox140cv** [comment] 2021-07-11 22:23
Thanks for the answers, I even raised the overclocking to 130% and it continued with crashes so I decided to open the issue, but I did not notice any error with the memory card. Of all those that I am replaying, it is the first that is so unstable. I am learning a lot from this exciting hobby.

**Comment by stenzek** [comment] 2021-07-12 05:13
Closing as it seems to match the console behavior.

**Closed by stenzek** 2021-07-12 05:13 UTC
Labels: Needs Console Verification, Possibly Invalid
