### ISSUE TITLE
Mouse use issues

### ISSUE THREAD

**Issue by DD-Indeed** [stenzek/duckstation#824] opened 2020-09-05 14:17 UTC
Tested Alien Resurrection quickly and noticed that the option to use mouse would require some further work, so that you can actually look around 360 degrees you with the mouse. Right now, the mouse tracking is taken from the monitor's area, which is limited. So, for example, I can't turn more than 200 degrees with the character when using a mouse.

**Comment by stenzek** [comment] 2020-09-05 14:59
Duplicate of https://github.com/stenzek/duckstation/issues/739 ?

**Comment by stenzek** [comment] 2020-09-14 14:41
Duplicate of #739

**Closed by stenzek** 2020-09-14 14:41 UTC
