### ISSUE TITLE
Cutscenes in Scooby-Doo! Night of 100 Frights (USA) (Proto) stopped working because of a recent regression

### ISSUE THREAD

**Issue by Hector-Eli-Wood** [stenzek/duckstation#2374] opened 2021-07-06 23:56 UTC
**Game details**
Game: Scooby-Doo! Night of 100 Frights (USA) (Proto)
Serial: unknown
Hash: PSXEXE / HASH-49D084CD7B45381F

**Description of the issue / bug**
The game's opening cutscenes no longer play. The game just sits on a black screen for about 20 seconds before the level select screen appears. 

**Controller Troubleshoot Report**
1. Have you installed any drivers or wrappers on your system, or do you have any programs like Steam open?
No
2. Which controller backend are you using in general settings
Tested with both digital and analog. 

**Steps to reproduce**
Simply start the game. 

**Enhancements information**
Tested with all enhancements off and with all settings default. Also tested with both interpreter and recompiler. 

**Hardware/software**
Tested with all renderers. 

**Emulator version**
Duckstation 0.2-4410-gdadd3fd2

**Additional context**
As far as I can tell the game regressed with one of these two changes. In every build before these the cutscenes worked fine.

![Capture](https://user-images.githubusercontent.com/86927936/124679830-8809ad00-df08-11eb-9497-bf6cb1a77aeb.PNG)

![Capture2](https://user-images.githubusercontent.com/86927936/124679854-92c44200-df08-11eb-9d73-c56851d98bd2.PNG)

I have also tested the game on real hardware and in various other emulators and the cutscenes also work fine. 

My own computer specs. Let me know if you need any more information.

![speccy](https://user-images.githubusercontent.com/86927936/124680038-e9ca1700-df08-11eb-9790-3e4a44e27e6e.PNG)

**Comment by stenzek** [comment] 2021-07-07 01:27
Prototypes likely are not legal to distribute and are not supported. Duplicate of #2334.

**Closed by stenzek** 2021-07-07 01:27 UTC
