### ISSUE TITLE
[Windows] Output to 1p and 2p ports with one button input

### ISSUE THREAD

**Issue by KONA-cheese** [stenzek/duckstation#2230] opened 2021-06-06 08:01 UTC
Hello. I'm sorry for my bad English.

**Is your feature request related to a problem? Please describe.**
If it sets the same button as the gamepad button set on port 1 to port 2 in the controller settings, it will only be output to port 2.
If it does the same with keyboard, it will only be output to port 1.

**Describe the solution you'd like**
Want to be able to the input to be output to both 1p and 2p.

**Describe alternatives you've considered**
I'm sorry, but I can't think of an alternative. I understand that this is a feature that is only needed under special conditions.

**Additional context**
![gamepad](https://user-images.githubusercontent.com/85429940/120916909-6211a280-c6e7-11eb-941d-ab421f093fd8.png)
![keyboard](https://user-images.githubusercontent.com/85429940/120916993-c2a0df80-c6e7-11eb-9d96-5423d1028434.png)

**Comment by stenzek** [comment] 2021-07-21 03:39
Duplicate of https://github.com/stenzek/duckstation/issues/1603

**Closed by stenzek** 2021-07-21 03:39 UTC
Labels: Feature Request
