### ISSUE TITLE
Supersampling/downsampling?

### ISSUE THREAD

**Issue by n1ghttrap** [stenzek/duckstation#1308] opened 2020-12-25 21:47 UTC
This would be nice to have, a la the Beetle HW core. It's a good way of keeping the low polygon models and textures soft/ambiguous and jaggy free, without removing detail. Combined with the Royale shader, this looks fantastic in Beetle, and if it's not too much trouble I'd love to see it in Duckstation eventually.  I personally find methods such as texture filtering and raising the resolution to make the PS1's lack of detail stand out terribly. Thanks for your consideration.

**Comment by stenzek** [comment] 2020-12-26 01:27
Duplicate of https://github.com/stenzek/duckstation/issues/1187

**Closed by stenzek** 2020-12-26 01:27 UTC
