### ISSUE TITLE
Skullmonkeys ALL VERSIONS // Missing part of the foreground.

### ISSUE THREAD

**Issue by Zet-sensei** [stenzek/duckstation#334] opened 2020-04-24 01:11 UTC
Some layers aren't rendered after the first seconds of gameplay.
Tested on 0.1-723

![Skull](https://user-images.githubusercontent.com/52127625/80164427-3877e380-85d9-11ea-9b35-d4b4f177ac6c.jpg)

**Comment by stenzek** [comment] 2020-04-24 04:56
Duplicate of https://github.com/stenzek/duckstation/issues/128

**Closed by stenzek** 2020-04-24 04:56 UTC
