### ISSUE TITLE
Mouse wrapping/relative mode

### ISSUE THREAD

**Issue by Iniquitatis** [stenzek/duckstation#1314] opened 2020-12-26 07:44 UTC
**Is your feature request related to a problem? Please describe.**
The emulator has no option to wrap the cursor coordinates in the game window. Absence of the option makes some mouse-based FPS games (e.g., Quake II) a bit harder to play.

**Describe the solution you'd like**
Just a simple checkbox in the Controller Settings -> PlayStation Mouse, which toggles the option.
([SDL](https://wiki.libsdl.org/SDL_SetRelativeMouseMode) wiki page, just in case.)

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by stenzek** [comment] 2020-12-26 07:57
Duplicate of https://github.com/stenzek/duckstation/issues/739

**Closed by stenzek** 2020-12-26 07:57 UTC

**Comment by Iniquitatis** [comment] 2020-12-26 08:21
Ouch. Sorry!
