### ISSUE TITLE
Option to rename the games without changing the ISO file names.

### ISSUE THREAD

**Issue by chumwizard** [stenzek/duckstation#2307] opened 2021-06-23 22:14 UTC
**Is your feature request related to a problem? Please describe.**
Yes. I always find it annoying when the games are named "PlayStation Game (USA) (En, Fr, De, Es, It)" in the menu and I can't change it even when renaming the .ISO file in Windows Explorer. 

**Describe the solution you'd like**
In the properties tab on selected ISO, or just by right-clicking it. Add a rename option. 

**Describe alternatives you've considered**
Add a config file that stores different names for each game based on their SLUS or SCUS code.

**Additional context**
No other context, it's just to tidy up the game library and make it seem cleaner. Discord rich presence also displays it and it would be nice if it just comes off without the added region name junk.

**Comment by stenzek** [comment] 2021-06-24 01:57
Not interested in changing this. Dolphin works the same way.

Also, duplicate of https://github.com/stenzek/duckstation/issues/1077

**Closed by stenzek** 2021-06-24 01:57 UTC
