### ISSUE TITLE
Question about transparency effect in Gex 3 - Deep Cover Gecko (USA)

### ISSUE THREAD

**Issue by kurayami6** [stenzek/duckstation#290] opened 2020-04-14 16:45 UTC
In Duckstation when Gex stands in water his lower half becomes transparent. 

![SLUS-00806_2020-04-15_02-37-44](https://user-images.githubusercontent.com/31968468/79250916-cc073100-7ec2-11ea-9454-3d40a43938ad.png)

If he stands in water while in vampire form his entire lower body disappears.

![SLUS-00806_2020-04-15_01-39-40](https://user-images.githubusercontent.com/31968468/79250978-e3461e80-7ec2-11ea-9ba8-1d33d96a9e76.png)

Can anyone confirm that this happens on real hardware?

**Comment by HeroponRikiBestest** [comment] 2020-04-14 19:22
While I can't confirm anything; this seems like it could be intended behaviour. My guess is that they just disabled reflections on vampire gex because vampires and that extends to water. Again, I could be wrong.

**Comment by stenzek** [comment] 2020-04-29 06:57
Closing as seems to be working as intended. If you can show that the console does not behave this way, I will re-open and investigate.

**Closed by stenzek** 2020-04-29 06:57 UTC
