### ISSUE TITLE
Crash when plugging DualShock 4 MacOS

### ISSUE THREAD

**Issue by vanyaa1** [stenzek/duckstation#1117] opened 2020-11-29 12:45 UTC
The application crashes when you connect a gamepad via USB, while it is also connected via bluetooth.

Also almost all games freezing when cinematics are starting to play if  PGXP is on.

**Comment by stenzek** [comment] 2020-11-30 04:55
This sounds like it might be a SDL issue. Could you get a call stack? If I remember correctly, the error report might contain it.

Unfortunately I don't have a Mac environment to reproduce this on.

**Comment by vanyaa1** [comment] 2020-11-30 18:21
How to get call stack? I'm not a developer, but I'll try if it's not too difficult.

If you connect a gamepad via bluetooth and usb **before** launching the application, then app will not start at all. 
In this case, I can do a Force Quit and see some kind of report, which I attached to the comment. 
[report.txt](https://github.com/stenzek/duckstation/files/5617921/report.txt)


If I connect a DualShock while the application is running, then the application crashes, and instead of showing the report, it is simply offered to send it to Apple.

**Comment by stenzek** [comment] 2020-12-10 15:00
Thanks for the report, looks like it's getting stuck in initialization. I actually fixed this a few days ago (https://github.com/stenzek/duckstation/commit/fd6462263f343786d59f13e3978e9a0eb1b326f9) since I hit the same problem in Linux, hopefully the same fix will apply here.

**Comment by stenzek** [comment] 2021-04-07 11:11
Closing since this was likely fixed.

**Closed by stenzek** 2021-04-07 11:11 UTC
