### ISSUE TITLE
CD player visualiser freezing.

### ISSUE THREAD

**Issue by foxsevent** [stenzek/duckstation#1602] opened 2021-02-08 02:28 UTC
Please fix.
**Game details**
Audio disc

**Description of the issue / bug**
Freezes.

**Steps to reproduce**
Have a newer bios revision selected 700X or newer, boot up the bios, enter the CD player menu, change the disc to an audio disc start any track and press select.

**Enhancements information**
None

**Hardware/software**
Windows 10
i7 4470
Geforce 1650S
16GB DDR3
**Emulator version**
Newest

**Comment by stenzek** [comment] 2021-02-08 02:33
Duplicate of https://github.com/stenzek/duckstation/issues/900

**Closed by stenzek** 2021-02-08 02:33 UTC

**Comment by foxsevent** [comment] 2021-02-08 02:37
> Duplicate of #900

Apologies then, I tried searing for such threads but apparently used wrong phrases.
