### ISSUE TITLE
Instant freeze on older graphics hardware

### ISSUE THREAD

**Issue by Farlander-001** [stenzek/duckstation#1508] opened 2021-01-25 10:28 UTC
**Game details**
Virtually any game

**Description of the issue / bug**
Any game freezes on start. Audio is working

**Steps to reproduce**
Run any game

**Hardware/software**
Linux Mint XFCE 20.1
Intel Atom N570 (4) @ 1.667GHz
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Pineview M 
OpenGL version string: 1.4 Mesa 20.0.8
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 20.0.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
Software renderer

**Emulator version**
0.1.2975-gddcc29c8

**Additional context**
Earlier versions worked well with software renderer

**Comment by Farlander-001** [comment] 2021-01-25 10:43
Log attached

[duckstation.log](https://github.com/stenzek/duckstation/files/5865986/duckstation.log)

**Comment by Nucleoprotein** [comment] 2021-01-25 12:36
OpenGL 1.4/OpenGL ES 2.0 is not supported but this emulator.

**Comment by stenzek** [comment] 2021-01-25 13:31
In theory it should work with the software renderer. Try environment variable `PREFER_GLES_CONTEXT=1`. But l fear the CPU might be a bit too slow anyway.

**Comment by stenzek** [comment] 2021-01-25 13:33
Nevermind, checked the log, it's getting an es2 context. I'll try and see if I can reproduce this by forcing gles2 but I don't have any hardware this old :/, so you may have to bisect it

**Comment by Farlander-001** [comment] 2021-01-25 14:24
I can enable OpenGL 2.1, but this is still not enough for hardware renderer. As I mentioned, in previous version (I don't know what exact version, probably 2 months old) software renderer worked just fine. Can I do something to fix this?

**Comment by Farlander-001** [comment] 2021-01-25 14:40
I tried PREFER_GLES_CONTEXT=0 but es2 context has not changed. First game (Castlevania) loaded, but with no image. Second game (Mr. Driller) crashed emulator with SEGFAULT

Log attached
[duckstation.log](https://github.com/stenzek/duckstation/files/5867246/duckstation.log)

**Comment by Nucleoprotein** [comment] 2021-01-25 15:32
For HW renderer you need OpenGL 3.1/OpenGL ES 3.0.

**Comment by stenzek** [comment] 2021-01-25 17:51
Reproduced the crash at least, fix is in master.

Interlaced output will still be borked because GLES2 doesn't support row length, but as a workaround you can disable interlacing in enhancements.

**Comment by Farlander-001** [comment] 2021-01-26 07:57
Interlaced image is broken as expected, but still no image in progressive mode

![Broken interlaced image](https://user-images.githubusercontent.com/62428757/105816119-7b426e00-5fe6-11eb-8d32-b421f3a290ce.png)
![No progressive image](https://user-images.githubusercontent.com/62428757/105816123-7c739b00-5fe6-11eb-9602-cf588dd13981.png)

Log attached

[duckstation.log](https://github.com/stenzek/duckstation/files/5871913/duckstation.log)

**Comment by Farlander-001** [comment] 2021-01-26 08:44
It seems it was a driver issue. After system update progressive image is working as it should. Sorry)
![Driver issue](https://user-images.githubusercontent.com/62428757/105821166-1e968180-5fed-11eb-88ed-5eabc31ec2cf.png)

Can I close this issue?

Log attached (it can be useful, maybe)
[duckstation.log](https://github.com/stenzek/duckstation/files/5872147/duckstation.log)

**Comment by stenzek** [comment] 2021-01-26 16:48
Sure, if you like. I'll sort out interlacing at some point.

**Comment by stenzek** [comment] 2021-02-05 01:44
Interlaced output fixed in https://github.com/stenzek/duckstation/commit/d455b61d5ed6c5baf027b8a788a6a67e798aa6ac

**Closed by stenzek** 2021-02-05 01:44 UTC
